package com.yamone.english

object Age1113LessonCatalog {
    val lessons = listOf(
        Lesson(
            id = 301,
            title = "그게 핵심은 아닌 것 같아",
            emoji = "🎯",
            situation = "토론에서 핵심을 구분해 말할 때",
            target = "I don't think that's the main point.",
            meaning = "그게 핵심은 아닌 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내 생각엔 그게 가장 중요한 문제는 아니야.",
            accepted = listOf("I don't think that's the most important issue.", "I don't think that's the main point."),
            coachLine = "What do you think the main point is?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 1
        ),
        Lesson(
            id = 302,
            title = "예를 하나 들어줄래?",
            emoji = "🧩",
            situation = "설명을 더 구체적으로 듣고 싶을 때",
            target = "Could you give me an example?",
            meaning = "예를 하나 들어줄래?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "무슨 뜻인지 예를 들어 설명해줄래?",
            accepted = listOf("Could you give me an example of what you mean?", "Could you give me an example?"),
            coachLine = "Sure. Here's one.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 2
        ),
        Lesson(
            id = 303,
            title = "나는 조금 다르게 생각해",
            emoji = "💬",
            situation = "정중하게 다른 의견을 말할 때",
            target = "I see it a little differently.",
            meaning = "나는 조금 다르게 생각해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내 생각은 네 생각과 조금 달라.",
            accepted = listOf("I see it a little differently from you.", "I see it a little differently."),
            coachLine = "How do you see it?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 3
        ),
        Lesson(
            id = 304,
            title = "왜 그렇게 생각해?",
            emoji = "❓",
            situation = "상대 의견의 근거를 물을 때",
            target = "What makes you think that?",
            meaning = "왜 그렇게 생각해?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그렇게 생각하게 된 이유가 뭐야?",
            accepted = listOf("What makes you think that's true?", "What makes you think that?"),
            coachLine = "Let me explain.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 4
        ),
        Lesson(
            id = 305,
            title = "그건 생각 못 했네",
            emoji = "💡",
            situation = "새로운 관점을 들었을 때",
            target = "I hadn't thought of that.",
            meaning = "그건 생각 못 했네.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그런 관점은 생각해보지 못했어.",
            accepted = listOf("I hadn't thought about it that way.", "I hadn't thought of that."),
            coachLine = "Does that change your mind?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 5
        ),
        Lesson(
            id = 306,
            title = "근거를 한번 보자",
            emoji = "🔎",
            situation = "주장을 확인하기 위해 자료를 볼 때",
            target = "Let's look at the evidence.",
            meaning = "근거를 한번 보자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "자료를 보고 어떤 근거가 있는지 확인하자.",
            accepted = listOf("Let's look at the evidence before we decide.", "Let's look at the evidence."),
            coachLine = "What evidence should we check?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 6
        ),
        Lesson(
            id = 307,
            title = "설명이 좀 더 필요해",
            emoji = "📝",
            situation = "설명이 충분하지 않을 때",
            target = "We need a better explanation.",
            meaning = "설명이 좀 더 필요해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "왜 그런지 더 자세한 설명이 필요해.",
            accepted = listOf("We need a clearer explanation of why that happened.", "We need a better explanation."),
            coachLine = "What part needs more explanation?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 7
        ),
        Lesson(
            id = 308,
            title = "아직 확신은 없어",
            emoji = "🤔",
            situation = "의견이 완전히 정해지지 않았을 때",
            target = "I'm not completely sure yet.",
            meaning = "아직 완전히 확신은 없어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "아직 어느 쪽이 맞는지 확신은 없어.",
            accepted = listOf("I'm not completely sure which side is right yet.", "I'm not completely sure yet."),
            coachLine = "What are you unsure about?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 8
        ),
        Lesson(
            id = 309,
            title = "무슨 뜻으로 말하느냐에 따라 달라",
            emoji = "🔀",
            situation = "단어 의미에 따라 답이 달라질 때",
            target = "It depends on what you mean.",
            meaning = "무슨 뜻으로 말하느냐에 따라 달라.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "여기서 '성공'을 무슨 뜻으로 쓰는지에 따라 달라.",
            accepted = listOf("It depends on what you mean by success.", "It depends on what you mean."),
            coachLine = "What do you mean by that word?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 9
        ),
        Lesson(
            id = 310,
            title = "두 생각을 비교해보자",
            emoji = "⚖️",
            situation = "서로 다른 의견을 비교할 때",
            target = "Let's compare both ideas.",
            meaning = "두 생각을 비교해보자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "두 의견의 장단점을 비교해보자.",
            accepted = listOf("Let's compare the strengths and weaknesses of both ideas.", "Let's compare both ideas."),
            coachLine = "Which idea seems stronger?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 10
        ),
        Lesson(
            id = 311,
            title = "우선순위를 정해야 해",
            emoji = "📌",
            situation = "해야 할 일이 많을 때",
            target = "We need to set our priorities.",
            meaning = "우선순위를 정해야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "뭐부터 해야 할지 우선순위를 정하자.",
            accepted = listOf("We need to decide what our top priorities are.", "We need to set our priorities."),
            coachLine = "What's most important right now?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 11
        ),
        Lesson(
            id = 312,
            title = "마감이 생각보다 가까워",
            emoji = "⏳",
            situation = "마감일이 얼마 남지 않았을 때",
            target = "The deadline is closer than I thought.",
            meaning = "마감이 생각보다 가까워.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "프로젝트 마감이 생각보다 훨씬 가까워.",
            accepted = listOf("The project deadline is much closer than I thought.", "The deadline is closer than I thought."),
            coachLine = "How much time do we have left?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 12
        ),
        Lesson(
            id = 313,
            title = "역할을 나누자",
            emoji = "👥",
            situation = "팀 과제에서 역할을 정할 때",
            target = "Let's divide up the work.",
            meaning = "역할을 나누자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "각자 맡을 일을 정해서 나누자.",
            accepted = listOf("Let's divide up the work so everyone has a job.", "Let's divide up the work."),
            coachLine = "What do you want to handle?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 13
        ),
        Lesson(
            id = 314,
            title = "내가 이 부분 맡을게",
            emoji = "🙋",
            situation = "팀에서 맡을 일을 자원할 때",
            target = "I'll take care of this part.",
            meaning = "내가 이 부분 맡을게.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "자료 정리는 내가 맡을게.",
            accepted = listOf("I'll take care of organizing the information.", "I'll take care of this part."),
            coachLine = "What should I do?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 14
        ),
        Lesson(
            id = 315,
            title = "계획을 조금 바꿔야 할 것 같아",
            emoji = "🗓️",
            situation = "상황에 따라 계획을 수정할 때",
            target = "I think we need to adjust the plan.",
            meaning = "계획을 조금 바꿔야 할 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "시간이 부족해서 계획을 조금 수정해야 할 것 같아.",
            accepted = listOf("I think we need to adjust the plan because we're running out of time.", "I think we need to adjust the plan."),
            coachLine = "What should we change?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 15
        ),
        Lesson(
            id = 316,
            title = "중간에서 타협하자",
            emoji = "🤝",
            situation = "의견이 다를 때 절충안을 찾을 때",
            target = "Let's meet in the middle.",
            meaning = "중간에서 타협하자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "우리 둘 다 괜찮을 수 있는 방법을 찾자.",
            accepted = listOf("Let's find a compromise that works for both of us.", "Let's meet in the middle."),
            coachLine = "What would be a fair compromise?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 16
        ),
        Lesson(
            id = 317,
            title = "이 방법이 더 효율적일 것 같아",
            emoji = "⚙️",
            situation = "더 나은 방법을 제안할 때",
            target = "This way might be more efficient.",
            meaning = "이 방법이 더 효율적일 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이 순서로 하면 시간을 더 아낄 수 있을 것 같아.",
            accepted = listOf("This way might save us more time.", "This way might be more efficient."),
            coachLine = "Why do you think it's more efficient?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 17
        ),
        Lesson(
            id = 318,
            title = "지금 진행 상황 어때?",
            emoji = "📊",
            situation = "팀 과제 진행 상황을 확인할 때",
            target = "How are we doing so far?",
            meaning = "지금 진행 상황 어때?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "지금까지 계획대로 잘 진행되고 있어?",
            accepted = listOf("Are we still on track so far?", "How are we doing so far?"),
            coachLine = "We're doing okay, but we have a lot left.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 18
        ),
        Lesson(
            id = 319,
            title = "예상보다 오래 걸리고 있어",
            emoji = "⌛",
            situation = "일이 계획보다 늦어질 때",
            target = "It's taking longer than expected.",
            meaning = "예상보다 오래 걸리고 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "자료 찾는 데 예상보다 시간이 더 걸리고 있어.",
            accepted = listOf("Finding the information is taking longer than expected.", "It's taking longer than expected."),
            coachLine = "Do we need to change the schedule?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 19
        ),
        Lesson(
            id = 320,
            title = "끝나면 한번 검토하자",
            emoji = "✅",
            situation = "과제를 제출 전 확인할 때",
            target = "Let's review it when we're done.",
            meaning = "끝나면 한번 검토하자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "끝난 뒤에 빠진 게 없는지 같이 확인하자.",
            accepted = listOf("Let's review everything together when we're done.", "Let's review it when we're done."),
            coachLine = "What should we check?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 20
        ),
        Lesson(
            id = 321,
            title = "소외된 느낌이 들었어",
            emoji = "😕",
            situation = "친구들과 있을 때 배제된 느낌을 말할 때",
            target = "I felt left out.",
            meaning = "소외된 느낌이 들었어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "너희가 나만 빼고 얘기해서 소외된 느낌이 들었어.",
            accepted = listOf("I felt left out when you talked without me.", "I felt left out."),
            coachLine = "I didn't realize you felt that way.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 21
        ),
        Lesson(
            id = 322,
            title = "큰일로 만들고 싶진 않아",
            emoji = "🌿",
            situation = "갈등을 크게 키우고 싶지 않을 때",
            target = "I don't want this to become a big deal.",
            meaning = "이걸 큰일로 만들고 싶진 않아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "문제는 말하고 싶지만 싸우고 싶진 않아.",
            accepted = listOf("I want to talk about it, but I don't want it to become a big deal.", "I don't want this to become a big deal."),
            coachLine = "Then let's talk calmly.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 22
        ),
        Lesson(
            id = 323,
            title = "더 일찍 말했어야 했어",
            emoji = "🗣️",
            situation = "문제를 늦게 말한 것을 후회할 때",
            target = "I should've said something earlier.",
            meaning = "더 일찍 말했어야 했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "처음 불편했을 때 바로 말했어야 했어.",
            accepted = listOf("I should've said something when it first bothered me.", "I should've said something earlier."),
            coachLine = "Why didn't you say anything?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 23
        ),
        Lesson(
            id = 324,
            title = "오해를 풀자",
            emoji = "🧹",
            situation = "서로 잘못 이해한 상황을 정리할 때",
            target = "Let's clear this up.",
            meaning = "오해를 풀자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "누가 뭘 말했는지 차근차근 확인해서 오해를 풀자.",
            accepted = listOf("Let's clear this up by going over what actually happened.", "Let's clear this up."),
            coachLine = "Okay, let's start from the beginning.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 24
        ),
        Lesson(
            id = 325,
            title = "그건 내 선을 넘었어",
            emoji = "🚧",
            situation = "불편했던 행동의 경계를 말할 때",
            target = "That crossed a line for me.",
            meaning = "그건 내 선을 넘었어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 농담은 나한테는 좀 선을 넘었어.",
            accepted = listOf("That joke crossed a line for me.", "That crossed a line for me."),
            coachLine = "I didn't know it bothered you that much.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 25
        ),
        Lesson(
            id = 326,
            title = "그 얘기는 퍼뜨리지 않았으면 해",
            emoji = "🤫",
            situation = "개인적인 이야기를 지켜달라고 할 때",
            target = "I'd rather you didn't spread that around.",
            meaning = "그 얘기는 퍼뜨리지 않았으면 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그건 개인적인 얘기라 다른 사람에게 말하지 않았으면 해.",
            accepted = listOf("I'd rather you didn't tell other people about that.", "I'd rather you didn't spread that around."),
            coachLine = "Okay, I won't.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 26
        ),
        Lesson(
            id = 327,
            title = "소문만 듣고 판단하지 말자",
            emoji = "🧠",
            situation = "확인되지 않은 이야기에 휩쓸리지 않을 때",
            target = "Let's not judge based on rumors.",
            meaning = "소문만 듣고 판단하지 말자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "직접 확인하기 전에는 소문만 믿고 판단하지 말자.",
            accepted = listOf("Let's not judge anyone until we know what actually happened.", "Let's not judge based on rumors."),
            coachLine = "That's fair.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 27
        ),
        Lesson(
            id = 328,
            title = "내가 잘못 이해한 것 같아",
            emoji = "😓",
            situation = "상대 말을 오해했음을 인정할 때",
            target = "I think I misunderstood you.",
            meaning = "내가 잘못 이해한 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "네가 말한 의도를 내가 잘못 이해한 것 같아.",
            accepted = listOf("I think I misunderstood what you meant.", "I think I misunderstood you."),
            coachLine = "That's okay. Let me explain.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 28
        ),
        Lesson(
            id = 329,
            title = "신뢰를 다시 쌓고 싶어",
            emoji = "🧱",
            situation = "관계 회복 의지를 말할 때",
            target = "I want to rebuild the trust between us.",
            meaning = "우리 사이의 신뢰를 다시 쌓고 싶어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "시간이 걸리더라도 다시 믿을 수 있게 하고 싶어.",
            accepted = listOf("I want to rebuild the trust, even if it takes time.", "I want to rebuild the trust between us."),
            coachLine = "What would help?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 29
        ),
        Lesson(
            id = 330,
            title = "필요하면 내가 옆에 있을게",
            emoji = "🤍",
            situation = "친구를 정서적으로 지지할 때",
            target = "I'm here if you need me.",
            meaning = "필요하면 내가 옆에 있을게.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "얘기하고 싶으면 언제든 내가 들어줄게.",
            accepted = listOf("I'm here if you want someone to talk to.", "I'm here if you need me."),
            coachLine = "Thanks. That means a lot.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 30
        ),
        Lesson(
            id = 331,
            title = "그 얘기 어디서 들었어?",
            emoji = "📱",
            situation = "정보의 출처를 물을 때",
            target = "Where did you hear that?",
            meaning = "그 얘기 어디서 들었어?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 정보는 어디에서 본 거야?",
            accepted = listOf("Where did you get that information?", "Where did you hear that?"),
            coachLine = "I saw it online.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 31
        ),
        Lesson(
            id = 332,
            title = "그게 사실인지 어떻게 알아?",
            emoji = "🧐",
            situation = "정보의 신뢰성을 확인할 때",
            target = "How do we know that's true?",
            meaning = "그게 사실인지 어떻게 알아?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 주장이 맞다는 걸 어떻게 확인할 수 있어?",
            accepted = listOf("How can we check whether that claim is true?", "How do we know that's true?"),
            coachLine = "We should look for another source.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 32
        ),
        Lesson(
            id = 333,
            title = "그 출처는 믿기 어려울 수도 있어",
            emoji = "⚠️",
            situation = "출처의 신뢰성을 의심할 때",
            target = "That source might not be reliable.",
            meaning = "그 출처는 믿기 어려울 수도 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "누가 쓴 건지 모르니까 그 자료는 신뢰하기 어려울 수 있어.",
            accepted = listOf("That source might not be reliable because we don't know who wrote it.", "That source might not be reliable."),
            coachLine = "What makes a source reliable?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 33
        ),
        Lesson(
            id = 334,
            title = "다른 자료도 확인해보자",
            emoji = "🔍",
            situation = "한 출처에만 의존하지 않을 때",
            target = "Let's check another source.",
            meaning = "다른 자료도 확인해보자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "한 군데만 보지 말고 다른 자료도 비교해보자.",
            accepted = listOf("Let's check another source before we believe it.", "Let's check another source."),
            coachLine = "Which source should we use?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 34
        ),
        Lesson(
            id = 335,
            title = "두 자료 내용이 안 맞아",
            emoji = "📰",
            situation = "자료끼리 정보가 다를 때",
            target = "The two reports don't match.",
            meaning = "두 자료 내용이 안 맞아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "두 기사에서 말하는 숫자가 서로 달라.",
            accepted = listOf("The numbers in the two reports don't match.", "The two reports don't match."),
            coachLine = "Which one is correct?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 35
        ),
        Lesson(
            id = 336,
            title = "오해였을 수도 있어",
            emoji = "🔄",
            situation = "상황에 다른 설명 가능성을 생각할 때",
            target = "It could've been a misunderstanding.",
            meaning = "오해였을 수도 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 사람이 일부러 그런 게 아니라 오해였을 수도 있어.",
            accepted = listOf("It could've been a misunderstanding rather than something intentional.", "It could've been a misunderstanding."),
            coachLine = "How can we find out?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 36
        ),
        Lesson(
            id = 337,
            title = "설명은 하나만 있는 게 아니야",
            emoji = "🧩",
            situation = "여러 가능한 원인을 고려할 때",
            target = "There could be more than one explanation.",
            meaning = "설명은 하나만 있는 게 아니야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "왜 그런 일이 생겼는지 설명은 여러 가지일 수 있어.",
            accepted = listOf("There could be more than one explanation for what happened.", "There could be more than one explanation."),
            coachLine = "What are the possibilities?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 37
        ),
        Lesson(
            id = 338,
            title = "아직은 확신이 안 가",
            emoji = "🤨",
            situation = "근거가 부족해 동의하지 않을 때",
            target = "I'm not convinced yet.",
            meaning = "아직은 확신이 안 가.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "설명은 들었지만 아직 완전히 납득되진 않아.",
            accepted = listOf("I understand the explanation, but I'm not convinced yet.", "I'm not convinced yet."),
            coachLine = "What would convince you?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 38
        ),
        Lesson(
            id = 339,
            title = "그 조건이라면 말이 돼",
            emoji = "🧠",
            situation = "특정 조건에서 논리가 맞을 때",
            target = "That makes sense if that's true.",
            meaning = "그 조건이 맞다면 말이 돼.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 정보가 정확하다면 그 결론은 말이 돼.",
            accepted = listOf("That conclusion makes sense if the information is accurate.", "That makes sense if that's true."),
            coachLine = "So we need to check the information first.",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 39
        ),
        Lesson(
            id = 340,
            title = "정보가 더 필요해",
            emoji = "📚",
            situation = "결론을 내리기 전에 자료가 더 필요할 때",
            target = "We need more information before we decide.",
            meaning = "결정하기 전에 정보가 더 필요해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "지금 판단하기엔 자료가 부족해.",
            accepted = listOf("We don't have enough information to make a decision yet.", "We need more information before we decide."),
            coachLine = "What else do we need to know?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 40
        ),
        Lesson(
            id = 341,
            title = "이걸 더 잘하고 싶어",
            emoji = "🎯",
            situation = "자신의 학습 목표를 말할 때",
            target = "I want to get better at this.",
            meaning = "이걸 더 잘하고 싶어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "사람들 앞에서 영어로 말하는 걸 더 잘하고 싶어.",
            accepted = listOf("I want to get better at speaking English in front of people.", "I want to get better at this."),
            coachLine = "How are you going to practice?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 41
        ),
        Lesson(
            id = 342,
            title = "좋은 습관을 만들려고 해",
            emoji = "🌱",
            situation = "꾸준한 습관을 만들 때",
            target = "I'm trying to build a good habit.",
            meaning = "좋은 습관을 만들려고 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "매일 조금씩 읽는 습관을 만들려고 해.",
            accepted = listOf("I'm trying to build a habit of reading a little every day.", "I'm trying to build a good habit."),
            coachLine = "How is it going?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 42
        ),
        Lesson(
            id = 343,
            title = "자꾸 미루게 돼",
            emoji = "😅",
            situation = "해야 할 일을 반복해서 미룰 때",
            target = "I keep putting it off.",
            meaning = "자꾸 미루게 돼.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "해야 하는 걸 알면서도 자꾸 나중으로 미뤄.",
            accepted = listOf("I know I need to do it, but I keep putting it off.", "I keep putting it off."),
            coachLine = "Why do you think you keep delaying it?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 43
        ),
        Lesson(
            id = 344,
            title = "좀 더 꾸준해야 해",
            emoji = "📈",
            situation = "지속적인 노력이 필요하다고 느낄 때",
            target = "I need to be more consistent.",
            meaning = "좀 더 꾸준해야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "한 번 많이 하는 것보다 매일 조금씩 꾸준해야 해.",
            accepted = listOf("I need to be more consistent instead of doing a lot once in a while.", "I need to be more consistent."),
            coachLine = "What would help you stay consistent?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 44
        ),
        Lesson(
            id = 345,
            title = "느렸어도 발전은 했어",
            emoji = "🐢",
            situation = "진행이 느렸지만 발전했음을 인정할 때",
            target = "I made progress, even if it was slow.",
            meaning = "느렸어도 발전은 했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "생각보다 오래 걸렸지만 분명히 발전했어.",
            accepted = listOf("I made progress even though it took longer than I expected.", "I made progress, even if it was slow."),
            coachLine = "What improved the most?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 45
        ),
        Lesson(
            id = 346,
            title = "예전엔 다르게 생각했어",
            emoji = "🔁",
            situation = "생각이 변한 과정을 말할 때",
            target = "I used to think differently about it.",
            meaning = "예전엔 그걸 다르게 생각했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "전에는 실패하면 재능이 없는 줄 알았어.",
            accepted = listOf("I used to think making mistakes meant I wasn't good at something.", "I used to think differently about it."),
            coachLine = "What changed your mind?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 46
        ),
        Lesson(
            id = 347,
            title = "그 실수에서 많이 배웠어",
            emoji = "📘",
            situation = "실수에서 배운 점을 말할 때",
            target = "I learned a lot from that mistake.",
            meaning = "그 실수에서 많이 배웠어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 일을 통해 준비가 왜 중요한지 배웠어.",
            accepted = listOf("I learned how important preparation is from that mistake.", "I learned a lot from that mistake."),
            coachLine = "What did you learn?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 47
        ),
        Lesson(
            id = 348,
            title = "좀 더 어려운 걸 해보고 싶어",
            emoji = "⛰️",
            situation = "자신에게 도전하고 싶을 때",
            target = "I want to challenge myself more.",
            meaning = "좀 더 어려운 걸 해보고 싶어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이제 익숙해졌으니까 더 어려운 걸 해보고 싶어.",
            accepted = listOf("Now that I'm comfortable with this, I want to challenge myself more.", "I want to challenge myself more."),
            coachLine = "What kind of challenge?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 48
        ),
        Lesson(
            id = 349,
            title = "아직 목표에 도달한 건 아니야",
            emoji = "🛤️",
            situation = "과정 중임을 인정할 때",
            target = "I'm not where I want to be yet.",
            meaning = "아직 목표에 도달한 건 아니야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "아직 부족하지만 전보다 많이 나아졌어.",
            accepted = listOf("I'm not where I want to be yet, but I'm much better than before.", "I'm not where I want to be yet."),
            coachLine = "What do you want to improve next?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 49
        ),
        Lesson(
            id = 350,
            title = "여기까지 온 게 자랑스러워",
            emoji = "🏅",
            situation = "자신의 발전을 긍정적으로 돌아볼 때",
            target = "I'm proud of how far I've come.",
            meaning = "여기까지 온 게 자랑스러워.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "처음 시작했을 때와 비교하면 여기까지 온 게 자랑스러워.",
            accepted = listOf("I'm proud of how far I've come since I started.", "I'm proud of how far I've come."),
            coachLine = "What are you most proud of?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 50
        )
    )
}
