package com.yamone.english

object Age1113PronunciationQaCatalog {
    private val baseGuides = listOf(
        PronunciationQaGuide(301, "I don't THINK that's the MAIN POINT ↘", "아이 / 돈트 / 띵크 / 댓츠 / 더 / 메인 / 포인트", "아이 돈(트) ●띵크 댓츠 더 ●메인 포인트↘", "약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(302, "Could‿you GIVE me an ex●AM-ple ↗", "쿠드 / 유 / 기브 / 미 / 언 / 이그잼플", "쿠쥬 ●기미 언 이그●잼플↗", "약-약-강-약-약-강 ↗"),
        PronunciationQaGuide(303, "I SEE‿it a little ●DIFF-er-ent-ly ↘", "아이 / 씨 / 잇 / 어 / 리를 / 디프런틀리", "아이 ●씨이러 리를 ●디프런틀리↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(304, "What MAKES‿you THINK that ↘", "왓 / 메익스 / 유 / 띵크 / 댓", "왓 ●메익슈 ●띵크 댓↘", "약-강-약-강-약 ↘"),
        PronunciationQaGuide(305, "I HAD-n't THOUGHT of that ↘", "아이 / 해든트 / 쏫 / 어브 / 댓", "아이 ●해든 쏘러브 ●댓↘", "약-강-강-약-강 ↘"),
        PronunciationQaGuide(306, "Let's LOOK at the ●EV-i-dence ↘", "렛츠 / 룩 / 앳 / 디 / 에버던스", "렛츠 ●루커트 디 ●에버던스↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(307, "We NEED a better expla●NA-tion ↘", "위 / 니드 / 어 / 베러 / 엑스플러네이션", "위 ●니더 베러 엑스플러●네이션↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(308, "I'm NOT completely SURE yet ↘", "아임 / 낫 / 컴플리틀리 / 슈어 / 옛", "아임 ●낫 컴플리틀리 ●슈어 옛↘", "약-강-약-강-약 ↘"),
        PronunciationQaGuide(309, "It de●PENDS on what‿you MEAN ↘", "잇 / 디펜즈 / 온 / 왓 / 유 / 민", "잇 디●펜즈 안 왓츄 ●민↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(310, "Let's com●PARE both i●DEAS ↘", "렛츠 / 컴페어 / 보우쓰 / 아이디어즈", "렛츠 컴●페어 보우쓰 아이●디어즈↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(311, "We NEED to set our pri●OR-i-ties ↘", "위 / 니드 / 투 / 셋 / 아워 / 프라이오러리즈", "위 ●니드 터 셋 아워 프라이●오러리즈↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(312, "The DEAD-line is CLOS-er than I THOUGHT ↘", "더 / 데드라인 / 이즈 / 클로우서 / 댄 / 아이 / 쏫", "더 ●데드라인 이즈 ●클로우서 댄 아이 ●쏫↘", "약-강-약-강-약-약-강 ↘"),
        PronunciationQaGuide(313, "Let's di●VIDE up the WORK ↘", "렛츠 / 디바이드 / 업 / 더 / 워크", "렛츠 디●바이덥 더 ●워크↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(314, "I'll TAKE care‿of this PART ↘", "아일 / 테이크 / 케어 / 어브 / 디스 / 파트", "아일 ●테익 케러브 디스 ●파트↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(315, "I THINK we need to ad●JUST the PLAN ↘", "아이 / 띵크 / 위 / 니드 / 투 / 어저스트 / 더 / 플랜", "아이 ●띵크 위 니드 터 어●저스트 더 ●플랜↘", "약-강-약-약-약-강-약-강 ↘"),
        PronunciationQaGuide(316, "Let's MEET in the ●MID-dle ↘", "렛츠 / 미트 / 인 / 더 / 미들", "렛츠 ●미딘 더 ●미들↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(317, "This WAY might be more ef●FI-cient ↘", "디스 / 웨이 / 마잇 / 비 / 모어 / 이피션트", "디스 ●웨이 마잇 비 모어 이●피션트↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(318, "HOW are‿we DO-ing so FAR ↘", "하우 / 아 / 위 / 두잉 / 쏘 / 파", "●하워위 ●두잉 쏘 ●파↘", "강-약-약-강-약-강 ↘"),
        PronunciationQaGuide(319, "It's TAK-ing LONG-er than ex●PECT-ed ↘", "잇츠 / 테이킹 / 롱거 / 댄 / 익스펙티드", "잇츠 ●테이킹 ●롱거 댄 익스●펙티드↘", "약-강-강-약-강 ↘"),
        PronunciationQaGuide(320, "Let's re●VIEW‿it when we're DONE ↘", "렛츠 / 리뷰 / 잇 / 웬 / 위어 / 던", "렛츠 리●뷰윗 웬 위어 ●던↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(321, "I FELT LEFT OUT ↘", "아이 / 펠트 / 레프트 / 아웃", "아이 ●펠트 레프●타웃↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(322, "I don't WANT this to become a big DEAL ↘", "아이 / 돈트 / 원트 / 디스 / 투 / 비컴 / 어 / 빅 / 딜", "아이 돈 ●원트 디스 터 비컴 어 빅 ●딜↘", "약-약-강-약-약-약-약-약-강 ↘"),
        PronunciationQaGuide(323, "I SHOULD've said something EAR-li-er ↘", "아이 / 슈드어브 / 세드 / 썸띵 / 얼리어", "아이 ●슈더브 세드 썸띵 ●얼리어↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(324, "Let's CLEAR this UP ↘", "렛츠 / 클리어 / 디스 / 업", "렛츠 ●클리어 디스 ●업↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(325, "That CROSSED a LINE for me ↘", "댓 / 크로스트 / 어 / 라인 / 포 / 미", "댓 ●크로스트 어 ●라인 퍼 미↘", "약-강-약-강-약-약 ↘"),
        PronunciationQaGuide(326, "I'd RATH-er you didn't SPREAD that a●ROUND ↘", "아이드 / 래더 / 유 / 디든트 / 스프레드 / 댓 / 어라운드", "아이드 ●래더 유 디든 ●스프레드 댓 어●라운드↘", "약-강-약-약-강-약-강 ↘"),
        PronunciationQaGuide(327, "Let's NOT judge based on ●RU-mors ↘", "렛츠 / 낫 / 저지 / 베이스트 / 온 / 루머즈", "렛츠 ●낫 저지 베이스트 안 ●루머즈↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(328, "I THINK I misunder●STOOD you ↘", "아이 / 띵크 / 아이 / 미선더스투드 / 유", "아이 ●띵카이 미선더●스투드유↘", "약-강-약-강-약 ↘"),
        PronunciationQaGuide(329, "I WANT to re●BUILD the TRUST between us ↘", "아이 / 원트 / 투 / 리빌드 / 더 / 트러스트 / 비트윈 / 어스", "아이 ●워너 리●빌드 더 ●트러스트 비트위너스↘", "약-강-약-강-약-강-약-약 ↘"),
        PronunciationQaGuide(330, "I'm HERE if‿you NEED me ↘", "아임 / 히어 / 이프 / 유 / 니드 / 미", "아임 ●히어 이퓨 ●니드 미↘", "약-강-약-약-강-약 ↘"),
        PronunciationQaGuide(331, "WHERE did‿you HEAR that ↘", "웨어 / 디드 / 유 / 히어 / 댓", "●웨어 디쥬 ●히어 댓↘", "강-약-약-강-약 ↘"),
        PronunciationQaGuide(332, "HOW do‿we KNOW that's TRUE ↘", "하우 / 두 / 위 / 노우 / 댓츠 / 트루", "●하우 더위 ●노우 댓츠 ●트루↘", "강-약-약-강-약-강 ↘"),
        PronunciationQaGuide(333, "That SOURCE might not be re●LI-a-ble ↘", "댓 / 소어스 / 마잇 / 낫 / 비 / 릴라이어블", "댓 ●소어스 마잇 낫 비 리●라이어블↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(334, "Let's CHECK another SOURCE ↘", "렛츠 / 체크 / 어나더 / 소어스", "렛츠 ●체크 어나더 ●소어스↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(335, "The TWO reports don't MATCH ↘", "더 / 투 / 리포츠 / 돈트 / 매치", "더 ●투 리포츠 돈 ●매치↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(336, "It COULD've been a misunder●STAND-ing ↘", "잇 / 쿠드어브 / 빈 / 어 / 미선더스탠딩", "잇 ●쿠더브 비너 미선더●스탠딩↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(337, "There could be MORE than one expla●NA-tion ↘", "데어 / 쿠드 / 비 / 모어 / 댄 / 원 / 엑스플러네이션", "데어 쿠드 비 ●모어 댄 원 엑스플러●네이션↘", "약-약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(338, "I'm NOT con●VINCED yet ↘", "아임 / 낫 / 컨빈스트 / 옛", "아임 ●낫 컨●빈스트 옛↘", "약-강-강-약 ↘"),
        PronunciationQaGuide(339, "That MAKES SENSE if that's TRUE ↘", "댓 / 메익스 / 센스 / 이프 / 댓츠 / 트루", "댓 ●메익스 센스 이프 댓츠 ●트루↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(340, "We NEED more infor●MA-tion before we de●CIDE ↘", "위 / 니드 / 모어 / 인퍼메이션 / 비포어 / 위 / 디사이드", "위 ●니드 모어 인퍼●메이션 비포어 위 디●사이드↘", "약-강-약-강-약-약-강 ↘"),
        PronunciationQaGuide(341, "I WANT to get BET-ter at THIS ↘", "아이 / 원트 / 투 / 겟 / 베러 / 앳 / 디스", "아이 ●워너 겟 ●베러랫 ●디스↘", "약-강-약-약-강-약-강 ↘"),
        PronunciationQaGuide(342, "I'm TRY-ing to BUILD a good HAB-it ↘", "아임 / 트라잉 / 투 / 빌드 / 어 / 굿 / 해빗", "아임 ●트라잉 터 ●빌더 굿 ●해빗↘", "약-강-약-강-약-약-강 ↘"),
        PronunciationQaGuide(343, "I KEEP putting‿it OFF ↘", "아이 / 킵 / 푸팅 / 잇 / 오프", "아이 ●킵 푸링잇 ●오프↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(344, "I NEED to be more con●SIS-tent ↘", "아이 / 니드 / 투 / 비 / 모어 / 컨시스턴트", "아이 ●니드 터 비 모어 컨●시스턴트↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(345, "I MADE PRO-gress | even if it was SLOW ↘", "아이 / 메이드 / 프라그레스 / 이븐 / 이프 / 잇 / 워즈 / 슬로우", "아이 ●메이드 ●프라그레스 | 이븐 이핏 워즈 ●슬로우↘", "약-강-강 | 약-약-약-약-강 ↘"),
        PronunciationQaGuide(346, "I USED to think differently about‿it ↘", "아이 / 유즈드 / 투 / 띵크 / 디프런틀리 / 어바웃 / 잇", "아이 ●유스터 띵크 디프런틀리 어바우릿↘", "약-강-약-약-강-약-약 ↘"),
        PronunciationQaGuide(347, "I LEARNED a LOT from that mis●TAKE ↘", "아이 / 런드 / 어 / 랏 / 프럼 / 댓 / 미스테이크", "아이 ●런더 ●랏 프럼 댓 미스●테이크↘", "약-강-약-강-약-약-강 ↘"),
        PronunciationQaGuide(348, "I WANT to CHAL-lenge myself MORE ↘", "아이 / 원트 / 투 / 챌린지 / 마이셀프 / 모어", "아이 ●워너 ●챌린지 마이셀프 ●모어↘", "약-강-약-강-약-강 ↘"),
        PronunciationQaGuide(349, "I'm NOT where I want to BE yet ↘", "아임 / 낫 / 웨어 / 아이 / 원트 / 투 / 비 / 옛", "아임 ●낫 웨어라이 워너 ●비 옛↘", "약-강-약-약-약-약-강-약 ↘"),
        PronunciationQaGuide(350, "I'm PROUD of how FAR I've COME ↘", "아임 / 프라우드 / 어브 / 하우 / 파 / 아이브 / 컴", "아임 ●프라우더브 하우 ●파 아이브 ●컴↘", "약-강-약-약-강-약-강 ↘")
    )

    val guides: List<PronunciationQaGuide> =
        baseGuides + Age1113PronunciationQaExpansionCatalog.guides
}
