package com.yamone.english

object Age1113LessonExpansionCatalog {
    val lessons = listOf(
        Lesson(
            id = 351,
            title = "그 주장에는 약점이 있어",
            emoji = "🧠",
            situation = "주장의 약점을 지적할 때",
            target = "There's a weakness in that argument.",
            meaning = "그 주장에는 약점이 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 주장은 이 부분이 약한 것 같아.",
            accepted = listOf("I think that argument is weak in this area.", "There's a weakness in that argument."),
            coachLine = "What weakness do you see?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 51
        ),
        Lesson(
            id = 352,
            title = "그건 반대 근거가 될 수 있어",
            emoji = "↔️",
            situation = "반대되는 근거를 제시할 때",
            target = "That could be evidence against it.",
            meaning = "그건 반대 근거가 될 수 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 자료는 오히려 반대 근거가 될 수 있어.",
            accepted = listOf("That information could actually be evidence against the idea.", "That could be evidence against it."),
            coachLine = "Why do you think it counts against it?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 52
        ),
        Lesson(
            id = 353,
            title = "네 말의 일부는 동의해",
            emoji = "🤝",
            situation = "상대 의견 일부에 동의할 때",
            target = "I agree with part of what you're saying.",
            meaning = "네 말의 일부는 동의해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "네 말의 절반 정도는 동의해.",
            accepted = listOf("I agree with some of what you're saying.", "I agree with part of what you're saying."),
            coachLine = "Which part do you agree with?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 53
        ),
        Lesson(
            id = 354,
            title = "하지만 결론은 달라",
            emoji = "🔀",
            situation = "같은 사실에서 다른 결론을 낼 때",
            target = "But I reach a different conclusion.",
            meaning = "하지만 나는 다른 결론에 도달해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "같은 자료를 봐도 나는 결론이 조금 달라.",
            accepted = listOf("I see the same information, but I reach a different conclusion.", "But I reach a different conclusion."),
            coachLine = "How is your conclusion different?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 54
        ),
        Lesson(
            id = 355,
            title = "그 가정이 맞는지 확인해야 해",
            emoji = "🔎",
            situation = "주장의 전제를 확인할 때",
            target = "We need to check whether that assumption is true.",
            meaning = "그 가정이 맞는지 확인해야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 전제가 사실인지 먼저 확인해야 해.",
            accepted = listOf("We need to check whether that assumption is actually true.", "We need to check whether that assumption is true."),
            coachLine = "What assumption are we making?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 55
        ),
        Lesson(
            id = 356,
            title = "그건 좋은 반론이야",
            emoji = "💬",
            situation = "상대의 반론을 인정할 때",
            target = "That's a good counterargument.",
            meaning = "그건 좋은 반론이야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그건 내가 생각 못 한 좋은 반론이야.",
            accepted = listOf("That's a good counterargument I hadn't considered.", "That's a good counterargument."),
            coachLine = "Does it change your view?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 56
        ),
        Lesson(
            id = 357,
            title = "새 근거가 있으면 생각을 바꿀 수도 있어",
            emoji = "🔄",
            situation = "근거에 따라 의견을 바꿀 수 있음을 말할 때",
            target = "I might change my mind if there's new evidence.",
            meaning = "새 근거가 있으면 생각을 바꿀 수도 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "더 좋은 근거가 나온다면 생각을 바꿀 수도 있어.",
            accepted = listOf("I might change my mind if stronger evidence comes up.", "I might change my mind if there's new evidence."),
            coachLine = "What kind of evidence would change your mind?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 57
        ),
        Lesson(
            id = 358,
            title = "장단점을 따져보자",
            emoji = "⚖️",
            situation = "결정 전 장단점을 비교할 때",
            target = "Let's weigh the pros and cons before deciding.",
            meaning = "결정하기 전에 장단점을 따져보자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "두 선택의 장단점을 비교하고 결정하자.",
            accepted = listOf("Let's compare the pros and cons of both options before deciding.", "Let's weigh the pros and cons before deciding."),
            coachLine = "What's the biggest advantage?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 58
        ),
        Lesson(
            id = 359,
            title = "둘 다 완벽하진 않아",
            emoji = "🤷",
            situation = "두 선택 모두 단점이 있을 때",
            target = "Neither option is perfect.",
            meaning = "둘 다 완벽한 선택은 아니야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "두 방법 다 장점도 있고 문제도 있어.",
            accepted = listOf("Neither option is perfect; they both have drawbacks.", "Neither option is perfect."),
            coachLine = "Which drawback matters more?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 59
        ),
        Lesson(
            id = 360,
            title = "이 선택은 나중에 영향을 줄 수 있어",
            emoji = "⏳",
            situation = "현재 선택의 미래 영향을 말할 때",
            target = "This choice could affect us later.",
            meaning = "이 선택은 나중에 우리에게 영향을 줄 수 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "지금 결정이 다음 달 계획에도 영향을 줄 수 있어.",
            accepted = listOf("This decision could affect our plans next month too.", "This choice could affect us later."),
            coachLine = "How could it affect us later?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 60
        ),
        Lesson(
            id = 361,
            title = "결과까지 생각해야 해",
            emoji = "➡️",
            situation = "행동의 결과를 고려할 때",
            target = "We need to think about the consequences.",
            meaning = "결과까지 생각해야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "하기 전에 어떤 결과가 생길지도 생각해야 해.",
            accepted = listOf("We need to think about the consequences before we do it.", "We need to think about the consequences."),
            coachLine = "What consequences are you worried about?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 61
        ),
        Lesson(
            id = 362,
            title = "안 되면 대안이 있어야 해",
            emoji = "🛟",
            situation = "실패에 대비한 대안을 마련할 때",
            target = "We need a backup plan in case it doesn't work.",
            meaning = "안 되면 대안이 있어야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "첫 번째 방법이 실패하면 쓸 대안이 필요해.",
            accepted = listOf("We need a backup plan in case the first idea fails.", "We need a backup plan in case it doesn't work."),
            coachLine = "What's our backup plan?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 62
        ),
        Lesson(
            id = 363,
            title = "그 위험을 감수할 가치가 있어?",
            emoji = "⚠️",
            situation = "위험과 이득을 비교할 때",
            target = "Is it worth the risk?",
            meaning = "그 위험을 감수할 가치가 있어?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "얻는 것에 비해 위험을 감수할 만한지 생각해보자.",
            accepted = listOf("We should ask whether the benefit is worth the risk.", "Is it worth the risk?"),
            coachLine = "What could go wrong?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 63
        ),
        Lesson(
            id = 364,
            title = "쉬운 선택이 항상 최선은 아니야",
            emoji = "🧭",
            situation = "편한 선택과 좋은 선택을 구분할 때",
            target = "The easiest choice isn't always the best one.",
            meaning = "가장 쉬운 선택이 항상 최선은 아니야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "당장은 쉬워 보여도 그게 가장 좋은 방법은 아닐 수 있어.",
            accepted = listOf("The easiest choice now may not be the best choice overall.", "The easiest choice isn't always the best one."),
            coachLine = "What makes the harder choice better?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 64
        ),
        Lesson(
            id = 365,
            title = "단기적으로는 도움이 될 수 있어",
            emoji = "📆",
            situation = "단기 효과와 장기 효과를 구분할 때",
            target = "It might help in the short term.",
            meaning = "단기적으로는 도움이 될 수 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "지금은 도움이 되지만 오래가지는 않을 수도 있어.",
            accepted = listOf("It might help in the short term, but it may not last.", "It might help in the short term."),
            coachLine = "What about the long term?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 65
        ),
        Lesson(
            id = 366,
            title = "장기적으로 더 나을 수도 있어",
            emoji = "🌱",
            situation = "장기적 이점을 말할 때",
            target = "It could be better in the long run.",
            meaning = "장기적으로는 더 나을 수도 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "시간은 더 걸려도 장기적으로는 이 방법이 나을 수 있어.",
            accepted = listOf("It may take longer, but it could be better in the long run.", "It could be better in the long run."),
            coachLine = "Why would it be better later?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 66
        ),
        Lesson(
            id = 367,
            title = "누가 영향을 받는지도 생각하자",
            emoji = "👥",
            situation = "결정의 영향을 받는 사람을 고려할 때",
            target = "Let's think about who might be affected.",
            meaning = "누가 영향을 받는지도 생각하자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "우리 결정 때문에 다른 사람에게 어떤 영향이 갈지도 보자.",
            accepted = listOf("Let's think about how our decision might affect other people.", "Let's think about who might be affected."),
            coachLine = "Who could be affected?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 67
        ),
        Lesson(
            id = 368,
            title = "공정한 결정인지도 봐야 해",
            emoji = "⚖️",
            situation = "결정의 공정성을 따질 때",
            target = "We should also ask whether it's fair.",
            meaning = "그 결정이 공정한지도 봐야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "효율적인 것뿐 아니라 공정한지도 생각해야 해.",
            accepted = listOf("We should think about whether it's fair, not just efficient.", "We should also ask whether it's fair."),
            coachLine = "What would make it fair?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 68
        ),
        Lesson(
            id = 369,
            title = "새 정보가 있으면 결정을 바꿔도 돼",
            emoji = "🔁",
            situation = "새 정보에 따라 결정을 수정할 때",
            target = "It's okay to change a decision when new information comes in.",
            meaning = "새 정보가 있으면 결정을 바꿔도 돼.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "새 사실을 알게 되면 이전 결정을 바꾸는 것도 괜찮아.",
            accepted = listOf("It's okay to change your decision when you learn something new.", "It's okay to change a decision when new information comes in."),
            coachLine = "Would the new information change your choice?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 69
        ),
        Lesson(
            id = 370,
            title = "선택에 책임을 져야 해",
            emoji = "🎯",
            situation = "자신의 선택에 책임을 질 때",
            target = "We have to take responsibility for the choice.",
            meaning = "우리는 그 선택에 책임을 져야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "우리가 선택한 거라면 결과에도 책임을 져야 해.",
            accepted = listOf("If we make the choice, we have to take responsibility for the result.", "We have to take responsibility for the choice."),
            coachLine = "What responsibility would we have?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 70
        ),
        Lesson(
            id = 371,
            title = "문자는 오해하기 쉬워",
            emoji = "💬",
            situation = "문자 메시지에서 오해가 생길 때",
            target = "Text messages can be easy to misunderstand.",
            meaning = "문자는 오해하기 쉬워.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "표정이나 목소리가 없어서 문자는 오해하기 쉬워.",
            accepted = listOf("Text messages can be easy to misunderstand without tone of voice.", "Text messages can be easy to misunderstand."),
            coachLine = "What part was misunderstood?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 71
        ),
        Lesson(
            id = 372,
            title = "그 말은 다르게 들릴 수 있어",
            emoji = "📱",
            situation = "온라인 문장이 다르게 받아들여질 수 있을 때",
            target = "That message could come across differently.",
            meaning = "그 말은 다르게 들릴 수 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "네 의도와 다르게 그 문장은 차갑게 들릴 수도 있어.",
            accepted = listOf("That message could come across as colder than you intended.", "That message could come across differently."),
            coachLine = "How could you say it differently?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 72
        ),
        Lesson(
            id = 373,
            title = "올리기 전에 한번 생각해",
            emoji = "🧠",
            situation = "온라인 게시 전 신중할 필요가 있을 때",
            target = "Think before you post something online.",
            meaning = "온라인에 올리기 전에 한번 생각해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "나중에도 남을 수 있으니까 게시하기 전에 생각해.",
            accepted = listOf("Think before you post because it may stay online for a long time.", "Think before you post something online."),
            coachLine = "What should you think about first?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 73
        ),
        Lesson(
            id = 374,
            title = "개인정보는 함부로 공유하면 안 돼",
            emoji = "🔒",
            situation = "개인정보 보호를 말할 때",
            target = "You shouldn't share personal information carelessly.",
            meaning = "개인정보는 함부로 공유하면 안 돼.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "주소나 전화번호 같은 개인정보는 쉽게 올리면 안 돼.",
            accepted = listOf("You shouldn't post personal information like your address or phone number.", "You shouldn't share personal information carelessly."),
            coachLine = "What information should stay private?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 74
        ),
        Lesson(
            id = 375,
            title = "사진 올리기 전에 물어봐",
            emoji = "📷",
            situation = "다른 사람 사진 게시 동의를 구할 때",
            target = "Ask before posting someone else's photo.",
            meaning = "다른 사람 사진을 올리기 전에 물어봐.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "친구 사진을 올리려면 먼저 괜찮은지 물어봐야 해.",
            accepted = listOf("You should ask before posting a photo of someone else.", "Ask before posting someone else's photo."),
            coachLine = "Why should you ask first?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 75
        ),
        Lesson(
            id = 376,
            title = "채팅으로 싸우진 말자",
            emoji = "💢",
            situation = "메신저에서 갈등이 커질 때",
            target = "Let's not argue over text.",
            meaning = "채팅으로 싸우진 말자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "문자로 계속 싸우기보다 다른 방법으로 얘기하자.",
            accepted = listOf("Let's not keep arguing over text messages.", "Let's not argue over text."),
            coachLine = "How should we talk instead?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 76
        ),
        Lesson(
            id = 377,
            title = "직접 얘기하는 게 낫겠어",
            emoji = "🗣️",
            situation = "온라인 갈등을 직접 대화로 풀 때",
            target = "I think it'd be better to talk in person.",
            meaning = "직접 얘기하는 게 낫겠어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이 문제는 문자보다 직접 얘기하는 게 나을 것 같아.",
            accepted = listOf("I think it'd be better to talk about this in person.", "I think it'd be better to talk in person."),
            coachLine = "Why would that be better?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 77
        ),
        Lesson(
            id = 378,
            title = "그 글이 진짜인지 확인해보자",
            emoji = "🔍",
            situation = "온라인 게시물의 진위를 확인할 때",
            target = "Let's check whether that post is real.",
            meaning = "그 글이 진짜인지 확인해보자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "공유하기 전에 그 게시물이 진짜인지 확인하자.",
            accepted = listOf("Let's check whether that post is real before we share it.", "Let's check whether that post is real."),
            coachLine = "How can we check it?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 78
        ),
        Lesson(
            id = 379,
            title = "댓글에 바로 반응하진 않을래",
            emoji = "⏸️",
            situation = "화난 상태에서 댓글을 쓰지 않으려 할 때",
            target = "I'm not going to respond right away.",
            meaning = "바로 반응하진 않을래.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "화가 나 있으니까 댓글에 바로 답하지 않을래.",
            accepted = listOf("I'm upset, so I'm not going to respond right away.", "I'm not going to respond right away."),
            coachLine = "What will you do instead?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 79
        ),
        Lesson(
            id = 380,
            title = "온라인에서도 예의가 필요해",
            emoji = "🌐",
            situation = "온라인 소통의 예의를 말할 때",
            target = "We should be respectful online too.",
            meaning = "온라인에서도 예의가 필요해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "화면 너머에도 사람이 있으니까 온라인에서도 예의를 지켜야 해.",
            accepted = listOf("We should be respectful online because there are real people on the other side.", "We should be respectful online too."),
            coachLine = "What does being respectful online look like?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 80
        ),
        Lesson(
            id = 381,
            title = "이건 내가 직접 해볼래",
            emoji = "💪",
            situation = "스스로 일을 해결하고 싶을 때",
            target = "I want to handle this on my own.",
            meaning = "이건 내가 직접 해볼래.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이번 과제는 도움 없이 내가 먼저 해보고 싶어.",
            accepted = listOf("I want to try handling this assignment on my own first.", "I want to handle this on my own."),
            coachLine = "Do you want any help at all?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 81
        ),
        Lesson(
            id = 382,
            title = "필요하면 도움을 요청할게",
            emoji = "🙋",
            situation = "필요할 때 도움을 요청할 계획을 말할 때",
            target = "I'll ask for help if I need it.",
            meaning = "필요하면 도움을 요청할게.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "혼자 해보다가 막히면 도움을 요청할게.",
            accepted = listOf("I'll try it on my own, and I'll ask for help if I get stuck.", "I'll ask for help if I need it."),
            coachLine = "How will you know when to ask?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 82
        ),
        Lesson(
            id = 383,
            title = "내 일정은 내가 관리해야 해",
            emoji = "📅",
            situation = "스스로 시간 관리를 해야 할 때",
            target = "I need to manage my own schedule.",
            meaning = "내 일정은 내가 관리해야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "숙제와 활동 시간을 내가 직접 관리해야 해.",
            accepted = listOf("I need to manage my own schedule for homework and activities.", "I need to manage my own schedule."),
            coachLine = "How are you going to organize it?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 83
        ),
        Lesson(
            id = 384,
            title = "내 실수는 내가 고칠게",
            emoji = "🛠️",
            situation = "자신의 실수를 직접 바로잡으려 할 때",
            target = "I'll take responsibility for fixing my mistake.",
            meaning = "내 실수는 내가 고칠게.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내가 잘못한 거니까 내가 고칠 방법을 찾을게.",
            accepted = listOf("I'll take responsibility for fixing the mistake I made.", "I'll take responsibility for fixing my mistake."),
            coachLine = "What are you going to do?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 84
        ),
        Lesson(
            id = 385,
            title = "핑계 대고 싶진 않아",
            emoji = "🚫",
            situation = "변명 대신 책임을 지고 싶을 때",
            target = "I don't want to make excuses.",
            meaning = "핑계 대고 싶진 않아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "늦은 이유는 있지만 그걸 핑계로 삼고 싶진 않아.",
            accepted = listOf("I have reasons, but I don't want to use them as excuses.", "I don't want to make excuses."),
            coachLine = "What will you do differently?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 85
        ),
        Lesson(
            id = 386,
            title = "준비가 부족했어",
            emoji = "📚",
            situation = "결과가 좋지 않았던 이유를 돌아볼 때",
            target = "I wasn't prepared enough.",
            meaning = "준비가 부족했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이번에는 연습을 충분히 하지 못했어.",
            accepted = listOf("I wasn't prepared enough because I didn't practice much.", "I wasn't prepared enough."),
            coachLine = "How will you prepare next time?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 86
        ),
        Lesson(
            id = 387,
            title = "다음엔 미리 준비할게",
            emoji = "⏰",
            situation = "다음번에는 더 일찍 준비하려 할 때",
            target = "I'll prepare earlier next time.",
            meaning = "다음엔 미리 준비할게.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "다음 프로젝트는 마감 직전에 하지 않고 미리 시작할게.",
            accepted = listOf("I'll start the next project earlier instead of waiting until the last minute.", "I'll prepare earlier next time."),
            coachLine = "When will you start?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 87
        ),
        Lesson(
            id = 388,
            title = "내가 선택한 거니까 책임질게",
            emoji = "🎯",
            situation = "자신의 선택 결과를 받아들일 때",
            target = "It was my choice, so I'll take responsibility.",
            meaning = "내가 선택한 거니까 책임질게.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내 결정이었으니까 결과도 받아들일게.",
            accepted = listOf("It was my decision, so I'll take responsibility for the result.", "It was my choice, so I'll take responsibility."),
            coachLine = "Do you regret the choice?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 88
        ),
        Lesson(
            id = 389,
            title = "혼자 해결할 수 있는지 해볼게",
            emoji = "🧩",
            situation = "먼저 스스로 문제를 풀어보려 할 때",
            target = "I'll try to work it out on my own.",
            meaning = "혼자 해결할 수 있는지 해볼게.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "바로 도움을 요청하기 전에 내가 먼저 해결해볼게.",
            accepted = listOf("I'll try to work it out on my own before asking for help.", "I'll try to work it out on my own."),
            coachLine = "What will you try first?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 89
        ),
        Lesson(
            id = 390,
            title = "도움을 받을 때도 알아야 해",
            emoji = "🛟",
            situation = "도움을 요청해야 할 때를 아는 것이 중요할 때",
            target = "Knowing when to ask for help is important too.",
            meaning = "언제 도움을 요청할지도 알아야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "혼자 하는 것도 중요하지만 도움받을 때를 아는 것도 중요해.",
            accepted = listOf("Being independent is important, but knowing when to ask for help matters too.", "Knowing when to ask for help is important too."),
            coachLine = "When should you ask for help?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 90
        ),
        Lesson(
            id = 391,
            title = "요즘 이 분야가 궁금해",
            emoji = "🔬",
            situation = "새로운 분야에 관심이 생겼을 때",
            target = "I've been getting more interested in this lately.",
            meaning = "요즘 이 분야가 궁금해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "요즘 과학 실험에 관심이 생기기 시작했어.",
            accepted = listOf("I've been getting more interested in science experiments lately.", "I've been getting more interested in this lately."),
            coachLine = "What interests you about it?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 91
        ),
        Lesson(
            id = 392,
            title = "왜 그런 일이 일어나는지 알고 싶어",
            emoji = "❓",
            situation = "현상의 원인을 알고 싶을 때",
            target = "I want to understand why that happens.",
            meaning = "왜 그런 일이 일어나는지 알고 싶어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "단순히 답만 외우는 게 아니라 왜 그런지 알고 싶어.",
            accepted = listOf("I don't just want the answer; I want to understand why it happens.", "I want to understand why that happens."),
            coachLine = "What are you trying to understand?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 92
        ),
        Lesson(
            id = 393,
            title = "이건 내가 잘하는 것 같아",
            emoji = "⭐",
            situation = "자신의 강점을 발견할 때",
            target = "I think this is something I'm good at.",
            meaning = "이건 내가 잘하는 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "사람들에게 설명하는 건 내가 잘하는 것 같아.",
            accepted = listOf("I think explaining things to people is something I'm good at.", "I think this is something I'm good at."),
            coachLine = "What makes you think you're good at it?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 93
        ),
        Lesson(
            id = 394,
            title = "이 부분은 아직 어려워",
            emoji = "⛰️",
            situation = "자신에게 어려운 부분을 인식할 때",
            target = "This part still feels challenging.",
            meaning = "이 부분은 아직 어렵게 느껴져.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "생각을 바로 영어로 말하는 건 아직 어렵게 느껴져.",
            accepted = listOf("Speaking my thoughts in English still feels challenging.", "This part still feels challenging."),
            coachLine = "What makes it difficult?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 94
        ),
        Lesson(
            id = 395,
            title = "더 알아보고 싶어",
            emoji = "📚",
            situation = "관심 주제를 더 깊게 탐색하고 싶을 때",
            target = "I'd like to learn more about it.",
            meaning = "그것에 대해 더 알아보고 싶어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이 분야가 실제로 어떤 일을 하는지 더 알아보고 싶어.",
            accepted = listOf("I'd like to learn more about what people actually do in this field.", "I'd like to learn more about it."),
            coachLine = "How could you learn more?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 95
        ),
        Lesson(
            id = 396,
            title = "실제로 한번 해보고 싶어",
            emoji = "🧪",
            situation = "관심 분야를 체험하고 싶을 때",
            target = "I'd like to try this in real life.",
            meaning = "이걸 실제로 한번 해보고 싶어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "영상으로만 보지 말고 직접 한번 해보고 싶어.",
            accepted = listOf("I'd like to try this in real life instead of only watching videos about it.", "I'd like to try this in real life."),
            coachLine = "Where could you try it?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 96
        ),
        Lesson(
            id = 397,
            title = "내가 뭘 좋아하는지 알아가는 중이야",
            emoji = "🧭",
            situation = "자신의 관심사를 탐색할 때",
            target = "I'm still figuring out what I'm interested in.",
            meaning = "내가 뭘 좋아하는지 알아가는 중이야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "아직 한 가지로 정하진 않았고 여러 관심사를 알아가는 중이야.",
            accepted = listOf("I'm still exploring different interests instead of choosing just one.", "I'm still figuring out what I'm interested in."),
            coachLine = "What are you interested in so far?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 97
        ),
        Lesson(
            id = 398,
            title = "지금 다 결정할 필요는 없어",
            emoji = "🌱",
            situation = "진로·관심사를 서둘러 정하지 않을 때",
            target = "I don't have to decide everything right now.",
            meaning = "지금 당장 다 결정할 필요는 없어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "앞으로 뭘 할지 지금 전부 정할 필요는 없다고 생각해.",
            accepted = listOf("I don't think I have to decide my whole future right now.", "I don't have to decide everything right now."),
            coachLine = "What can you focus on now?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 98
        ),
        Lesson(
            id = 399,
            title = "여러 가지를 경험해보고 싶어",
            emoji = "🌍",
            situation = "다양한 경험을 통해 관심사를 찾고 싶을 때",
            target = "I want to explore different things.",
            meaning = "여러 가지를 경험해보고 싶어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내가 뭘 좋아하는지 알기 위해 여러 활동을 경험해보고 싶어.",
            accepted = listOf("I want to explore different activities to learn what I enjoy.", "I want to explore different things."),
            coachLine = "What would you like to try first?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 99
        ),
        Lesson(
            id = 400,
            title = "더 자신 있게 내 생각을 말하고 싶어",
            emoji = "🎤",
            situation = "자기표현 능력을 목표로 삼을 때",
            target = "I want to express myself more confidently.",
            meaning = "더 자신 있게 내 생각을 말하고 싶어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "영어로 내 의견을 더 자연스럽고 자신 있게 말하고 싶어.",
            accepted = listOf("I want to express my opinions in English more naturally and confidently.", "I want to express myself more confidently."),
            coachLine = "What would help you feel more confident?",
            course = CourseLevel.AGE_11_13,
            courseLessonNumber = 100
        )
    )
}
