package com.yamone.english

private data class Age1720ExpansionSeed(
    val id: Int,
    val title: String,
    val emoji: String,
    val situation: String,
    val target: String,
    val meaning: String,
    val ownPromptKo: String,
    val detailEnglish: String,
    val acceptedAlternative: String,
    val coachEnglish: String,
    val coachKorean: String,
    val followUpEnglish: String,
    val followUpKorean: String,
    val thinkingOrder: String,
    val rhythmEnglish: String
)

private object Age1720ExpansionContent {
    const val soundKorean = "천천히 의미 단위로 듣고 따라 말하세요."
    const val connectedNote = "미국식 실제 회화처럼 기능어는 약하게, 핵심어는 분명하게 두고 단어를 끊지 말고 의미 덩어리로 연결해 말해보세요."

    val seeds = listOf(
        Age1720ExpansionSeed(551, "조금 더 맥락을 알 수 있을까요?", "🧩", "업무 요청이 모호해서 먼저 맥락을 확인할 때", "Can I get a little more context on what you need?", "필요한 게 뭔지 맥락을 조금 더 알 수 있을까요?", "제가 해결해야 하는 문제가 정확히 뭔지 확인하고 싶어요.", "I just want to make sure I'm solving the right problem.", "Could you give me a little more context on what you need?", "Do you have any questions before you start?", "시작하기 전에 궁금한 점 있어요?", "What part would be helpful to clarify?", "어느 부분을 더 설명해주면 좋을까요?", "할 수 있을까 → 내가 얻는 것을 → 조금 더 많은 맥락을 → 네가 필요한 것에 대해", "Can I get‿a little more ●CONTEXT on what you need ↗"),
        Age1720ExpansionSeed(552, "초안은 제가 먼저 맡을게요", "📝", "팀에서 첫 초안을 맡겠다고 제안할 때", "I can take the first draft and send it by this afternoon.", "첫 초안은 제가 맡아서 오늘 오후까지 보낼 수 있어요.", "먼저 틀을 잡아서 팀이 검토하기 쉽게 만들게요.", "I'll put together a starting point so the team has something concrete to review.", "I can handle the first draft and send it this afternoon.", "Who wants to take the first pass at this?", "이거 첫 초안은 누가 맡을까요?", "When do you think you can send it?", "언제쯤 보낼 수 있을 것 같아요?", "나는 → 맡을 수 있어 → 첫 초안을 → 그리고 보낼 수 있어 → 오늘 오후까지", "I can take‿the‿first ●DRAFT and send‿it by this afternoon ↘"),
        Age1720ExpansionSeed(553, "막힌 부분이 있어서 먼저 확인하려고요", "🚧", "그대로 진행하기 전에 막힌 지점을 확인할 때", "I'm blocked on one part, so I wanted to check before I keep going.", "한 부분에서 막혀서 계속 진행하기 전에 확인하려고 했어요.", "추측해서 다시 하는 것보다 지금 확인하는 게 나을 것 같아요.", "I'd rather check now than guess and have to redo it later.", "I'm stuck on one part, so I wanted to check before I continue.", "How's the task going?", "작업은 어떻게 되어가고 있어요?", "What's holding you up?", "어느 부분에서 막혔어요?", "나는 → 막혀 있어 → 한 부분에서 → 그래서 확인하고 싶었어 → 계속 가기 전에", "I'm ●BLOCKED on one part, so I wanted‿to‿check before I keep ●GOING ↘"),
        Age1720ExpansionSeed(554, "이걸 다른 일보다 먼저 할까요?", "📌", "우선순위가 겹칠 때 무엇부터 할지 확인할 때", "Do you want me to prioritize this over the other task?", "이걸 다른 업무보다 우선해서 할까요?", "둘 다 오늘 끝내기는 어려워서 우선순위를 맞추고 싶어요.", "I probably can't finish both today, so I want to make sure I'm prioritizing the right one.", "Should I prioritize this over the other task?", "I need both of these moving today.", "오늘 두 업무 모두 진행이 필요해요.", "Which one are you planning to start with?", "어느 것부터 시작할 생각이에요?", "원해 → 네가 → 내가 우선하기를 → 이것을 → 다른 일보다", "Do you want me‿to‿pri●ORITIZE this over the other task ↗"),
        Age1720ExpansionSeed(555, "오늘은 늦게까지 가능하지만 매번은 어려워요", "🌙", "추가 근무는 가능하지만 지속적인 기대는 어렵다고 말할 때", "I can stay a little later today, but I can't make that a regular thing.", "오늘은 조금 늦게까지 있을 수 있지만 그걸 매번 하기는 어려워요.", "오늘 일정은 조정할 수 있지만 앞으로는 미리 알면 좋겠어요.", "I can adjust today, but going forward I'd need a little more notice.", "I can stay late today, but I can't do that on a regular basis.", "Could you stay a little longer tonight?", "오늘 조금 더 남아 있을 수 있을까요?", "Would that be okay for you?", "오늘은 괜찮을까요?", "나는 → 있을 수 있어 → 조금 더 늦게 → 오늘 → 하지만 할 수 없어 → 그것을 정기적으로", "I can stay‿a little ●LATER today, but I can't make that‿a regular ●THING ↘"),
        Age1720ExpansionSeed(556, "체크인을 내일 아침으로 옮길 수 있을까요?", "🗓️", "짧은 미팅 시간을 조정하고 싶을 때", "Could we move our check-in to tomorrow morning?", "우리 체크인을 내일 아침으로 옮길 수 있을까요?", "오늘 오후에는 집중해서 끝내야 할 일이 하나 있어요.", "I have something I need to finish without breaking focus this afternoon.", "Could we move our check-in to tomorrow morning instead?", "Does this afternoon still work for our check-in?", "오늘 오후 체크인 시간 괜찮아요?", "Is there a better time for you?", "더 나은 시간이 있나요?", "할 수 있을까 → 우리가 옮기는 것을 → 우리의 체크인을 → 내일 아침으로", "Could we move‿our ●CHECK-IN to tomorrow morning ↗"),
        Age1720ExpansionSeed(557, "아직 확실한 답을 하기엔 정보가 부족해요", "🔎", "정보가 부족한 상태에서 성급하게 답하지 않을 때", "I don't have enough information to give you a solid answer yet.", "아직 확실한 답을 드리기에는 정보가 충분하지 않아요.", "두 가지를 더 확인하고 나서 답하는 게 정확할 것 같아요.", "I want to verify two things before I give you a definite answer.", "I don't have enough information to give you a confident answer yet.", "Can you give me an answer on this now?", "이거 지금 답해줄 수 있어요?", "What do you still need to check?", "아직 뭘 더 확인해야 해요?", "나는 → 가지고 있지 않아 → 충분한 정보를 → 주기 위해 → 확실한 답을 → 아직", "I don't have‿enough infor●MATION to give you‿a solid ●ANSWER yet ↘"),
        Age1720ExpansionSeed(558, "제 부분은 끝났고 하나만 기다리고 있어요", "⏳", "자기 작업은 끝났지만 외부 입력을 기다릴 때", "I finished my part. I'm just waiting on one more thing.", "제 부분은 끝냈고 이제 한 가지만 더 기다리고 있어요.", "자료가 오면 바로 마지막 확인을 해서 넘길 수 있어요.", "Once that comes in, I can do the final check and send it over.", "My part is done. I'm just waiting on one last thing.", "Where are we on this?", "이거 지금 어디까지 됐어요?", "What's the last thing you're waiting for?", "마지막으로 기다리는 게 뭐예요?", "나는 → 끝냈어 → 내 부분을 → 나는 단지 기다리고 있어 → 한 가지를 더", "I ●FINISHED my part. I'm just waiting‿on one more ●THING ↘"),
        Age1720ExpansionSeed(559, "피드백 반영해서 새 버전 보낼게요", "🔁", "피드백을 받은 뒤 수정 계획을 확인할 때", "Thanks for the feedback. I'll revise it and send another version.", "피드백 감사합니다. 수정해서 새 버전을 보내겠습니다.", "말해준 두 부분부터 고친 다음 전체를 한 번 더 볼게요.", "I'll fix those two points first and then do one more pass through the whole thing.", "Thanks for the feedback. I'll make the changes and send a new version.", "I left a few notes on your draft.", "초안에 몇 가지 코멘트를 남겼어요.", "Do the changes make sense?", "수정할 내용은 이해됐어요?", "고마워 → 피드백에 대해 → 나는 수정할 거야 → 그것을 → 그리고 보낼 거야 → 다른 버전을", "Thanks for‿the‿●FEEDBACK. I'll re●VISE it and send‿another ●VERSION ↘"),
        Age1720ExpansionSeed(560, "기본을 익히면 더 큰 역할도 맡아보고 싶어요", "📈", "초기 적응 뒤 더 많은 책임을 원한다고 말할 때", "I'm interested in taking on more responsibility once I get the basics down.", "기본을 익히고 나면 더 많은 책임을 맡아보고 싶어요.", "지금은 정확하게 배우는 데 집중하고 그다음 범위를 넓히고 싶어요.", "For now I want to learn the process well, then gradually take on more.", "I'd like to take on more responsibility once I have the basics down.", "What are you hoping to learn here?", "여기에서 어떤 걸 배우고 싶어요?", "What would you like to take on later?", "나중에는 어떤 일을 맡아보고 싶어요?", "나는 → 관심 있어 → 맡는 것에 → 더 많은 책임을 → 내가 기본을 익히면", "I'm ●INTERESTED in taking‿on more respon●SIBILITY once I get‿the‿basics ●DOWN ↘"),

        Age1720ExpansionSeed(561, "큰돈 쓰기 전에 비상금을 만들고 있어", "💰", "소비보다 비상자금을 우선한다고 말할 때", "I'm trying to build an emergency fund before I spend on anything big.", "큰돈을 쓰기 전에 비상금을 만들려고 하고 있어.", "적어도 몇 달치 기본생활비는 먼저 따로 모아두고 싶어.", "I want to have a few months of basic expenses set aside first.", "I'm building an emergency fund before I make any big purchases.", "Are you still thinking about buying that laptop?", "그 노트북 아직 살 생각이야?", "What are you saving for first?", "우선 뭘 위해 저축하고 있어?", "나는 → 노력하고 있어 → 만드는 것을 → 비상금을 → 쓰기 전에 → 큰 것에", "I'm trying‿to‿build‿an e●MERGENCY fund before I spend‿on anything ●BIG ↘"),
        Age1720ExpansionSeed(562, "월 납입액보다 총비용도 보고 있어", "🧮", "할부나 구독의 전체 비용을 따질 때", "I can afford the monthly payment, but I'm looking at the total cost too.", "월 납입액은 감당할 수 있지만 총비용도 같이 보고 있어.", "당장은 싸 보여도 오래 내면 얼마나 되는지 계산해보려고 해.", "I want to see what it adds up to over the full term, not just this month.", "The monthly payment is manageable, but I'm also looking at the total cost.", "The monthly payment doesn't look too bad.", "월 납입액은 그렇게 나쁘지 않아 보이네.", "So what's making you hesitate?", "그럼 뭐 때문에 망설여?", "나는 → 감당할 수 있어 → 월 납입액을 → 하지만 보고 있어 → 총비용도", "I can af●FORD the monthly payment, but I'm looking‿at‿the ●TOTAL cost too ↘"),
        Age1720ExpansionSeed(563, "이 수수료가 뭔지 설명해줄 수 있나요?", "🧾", "청구서나 계약서의 수수료를 확인할 때", "Could you walk me through what this fee is for?", "이 수수료가 무엇 때문에 붙은 건지 설명해주실 수 있나요?", "항목 이름만 봐서는 어떤 비용인지 잘 모르겠어요.", "The label is pretty vague, so I'm not sure what I'm being charged for.", "Could you explain what this fee is for?", "Do you have a question about the bill?", "청구서 관련해서 궁금한 점 있으세요?", "Which charge are you asking about?", "어느 항목을 말씀하시는 건가요?", "할 수 있을까 → 네가 설명해주는 것을 → 이 수수료가 → 무엇을 위한 것인지", "Could you walk me through what this ●FEE is for ↗"),
        Age1720ExpansionSeed(564, "동의하기 전에 계약서를 읽어보고 싶어요", "📄", "계약이나 약관에 서명하기 전에 검토할 때", "I want to read the contract before I agree to anything.", "무엇이든 동의하기 전에 계약서를 읽어보고 싶어요.", "오늘 가져가서 확인하고 내일 답해도 될까요?", "I'd like to take it home, read it carefully, and get back to you tomorrow.", "I'd like to read the contract before I agree to anything.", "We can get this signed today if you're ready.", "준비되셨으면 오늘 바로 서명할 수 있어요.", "Is there anything specific you want to review?", "특별히 확인하고 싶은 부분이 있나요?", "나는 → 원해 → 읽는 것을 → 계약서를 → 내가 동의하기 전에 → 무엇이든", "I want‿to‿read‿the ●CONTRACT before I a●GREE to anything ↘"),
        Age1720ExpansionSeed(565, "마음이 바뀌면 보증금은 돌려받나요?", "🏦", "예약·임대·서비스의 보증금 환불 조건을 물을 때", "Is the deposit refundable if I change my mind?", "마음이 바뀌면 보증금을 환불받을 수 있나요?", "취소 시점에 따라 조건이 달라지는지도 알고 싶어요.", "I'd also like to know whether the refund depends on when I cancel.", "Would I get the deposit back if I change my mind?", "The deposit is due when you reserve it.", "예약할 때 보증금을 내셔야 해요.", "Are you worried about the cancellation policy?", "취소 규정이 궁금하신가요?", "인가 → 보증금이 → 환불 가능한 → 만약 내가 마음을 바꾸면", "Is the de●POSIT re●FUNDABLE if I change my mind ↗"),
        Age1720ExpansionSeed(566, "룸메이트랑 나누니까 비용을 문서로 받고 싶어요", "🏠", "공동 임대 비용을 명확히 남기고 싶을 때", "I'm splitting the rent with a roommate, so we need the costs in writing.", "룸메이트와 월세를 나누기 때문에 비용을 문서로 확인할 필요가 있어요.", "월세랑 공과금 중에 각각 누가 얼마를 내는지 명확히 하고 싶어요.", "We want to be clear about how the rent and utilities are divided.", "I'm sharing the rent with a roommate, so we'd like the costs in writing.", "Will both of you be on the lease?", "두 분 모두 계약서에 이름을 올리나요?", "What do you want listed separately?", "어떤 비용을 따로 표시하길 원하세요?", "나는 → 나누고 있어 → 월세를 → 룸메이트와 → 그래서 우리는 필요해 → 비용을 문서로", "I'm ●SPLITTING the rent with‿a roommate, so we need‿the‿costs in ●WRITING ↘"),
        Age1720ExpansionSeed(567, "세금으로 낼 돈은 따로 빼두고 있어", "🪙", "프리랜스나 단기소득에서 세금을 따로 관리할 때", "I'm setting aside money for taxes instead of treating it like spending money.", "쓸 돈처럼 생각하지 않고 세금 낼 돈을 따로 떼어두고 있어.", "돈이 들어올 때마다 일정 부분은 바로 다른 통장으로 옮겨.", "Whenever I get paid, I move part of it into a separate account right away.", "I'm putting money aside for taxes instead of treating all of it as spending money.", "You got paid for that freelance project, right?", "그 프리랜스 일 돈 받았지?", "How are you keeping track of it?", "그 돈은 어떻게 관리하고 있어?", "나는 → 따로 두고 있어 → 돈을 → 세금을 위해 → 다 쓸 돈처럼 다루는 대신", "I'm setting‿a●SIDE money for ●TAXES instead‿of treating‿it like spending ●MONEY ↘"),
        Age1720ExpansionSeed(568, "이번 달은 지출이 겹쳐서 줄여야 했어", "📉", "예상 밖 지출이 겹쳐 소비를 조정할 때", "I had to cut back this month because a few expenses came up at once.", "이번 달은 몇 가지 지출이 한꺼번에 생겨서 소비를 줄여야 했어.", "당분간 외식이랑 쇼핑을 조금 줄이려고 해.", "I'm cutting back on eating out and shopping for a couple of weeks.", "I had to spend less this month because several expenses came up at once.", "You haven't been going out much lately.", "요즘은 밖에 잘 안 나가네.", "Was there one big expense?", "큰 지출이 하나 있었어?", "나는 → 줄여야 했어 → 이번 달에 → 왜냐하면 몇 가지 지출이 → 한꺼번에 생겼어", "I had‿to‿cut ●BACK this month because‿a few ex●PENSES came‿up‿at ●ONCE ↘"),
        Age1720ExpansionSeed(569, "믿고 쓸 수 있으면 조금 더 내는 게 나아", "🛠️", "가격보다 신뢰성과 내구성을 우선할 때", "I'd rather pay a little more for something I can rely on.", "믿고 쓸 수 있는 거라면 조금 더 내는 편이 낫겠어.", "싼 걸 여러 번 바꾸는 것보다 오래 쓰는 게 좋을 것 같아.", "I'd rather buy it once and use it for a long time than keep replacing a cheap one.", "I'd rather spend a little more on something reliable.", "This one is cheaper.", "이게 더 싸네.", "Why are you leaning toward the other one?", "왜 다른 쪽이 더 끌려?", "나는 → 차라리 내고 싶어 → 조금 더 → 무언가에 → 내가 믿을 수 있는", "I'd rather pay‿a little ●MORE for something I can re●LY on ↘"),
        Age1720ExpansionSeed(570, "필요한 것과 그냥 원하는 걸 구분하는 중이야", "⚖️", "충동소비를 줄이기 위해 필요와 욕구를 구분할 때", "I'm learning to separate what I need from what I just want right now.", "지금 필요한 것과 그냥 당장 원하는 것을 구분하는 법을 배우고 있어.", "바로 사지 않고 하루 정도 두고 다시 생각해보려고 해.", "I'm trying to wait a day before I buy something that wasn't already planned.", "I'm learning to tell the difference between what I need and what I just want right now.", "Are you going to buy it?", "그거 살 거야?", "How do you decide now?", "요즘은 어떻게 결정해?", "나는 → 배우고 있어 → 구분하는 것을 → 내가 필요한 것과 → 내가 지금 그냥 원하는 것을", "I'm learning‿to‿●SEPARATE what I need from what I just ●WANT right now ↘"),

        Age1720ExpansionSeed(571, "나 빼고 계획한 게 서운했어", "🫥", "친구들이 자신을 빼고 약속을 잡아 서운함을 말할 때", "I felt left out when everyone made plans without telling me.", "다들 나한테 말도 없이 계획을 잡았을 때 소외된 기분이 들었어.", "꼭 같이 가야 했다는 게 아니라 아무 말도 없었던 게 서운했어.", "It's not that I had to be invited. It just hurt that nobody said anything.", "I felt left out when plans were made without anyone telling me.", "You've been quiet since yesterday. What's up?", "어제부터 조용한데 무슨 일이야?", "Was it about the plan we made?", "우리가 잡은 약속 때문이야?", "나는 → 느꼈어 → 소외된 것을 → 모두가 계획을 잡았을 때 → 나에게 말하지 않고", "I felt left ●OUT when everyone made ●PLANS without telling me ↘"),
        Age1720ExpansionSeed(572, "도와주는 건 괜찮지만 먼저 물어봐 줘", "🤝", "도움 요청 없이 자신의 시간이나 물건을 당연하게 쓰지 않길 바랄 때", "I don't mind helping, but I need you to ask me first.", "도와주는 건 괜찮지만 먼저 나한테 물어봐 줬으면 해.", "급한 일이더라도 내가 가능한지 먼저 확인해주면 좋겠어.", "Even if it's urgent, I want you to check whether I'm available first.", "I'm happy to help, but I need you to ask me first.", "I thought you wouldn't mind helping me with it.", "네가 도와주는 거 괜찮을 줄 알았어.", "Is it the helping part or the way I asked?", "도와주는 게 문제야, 아니면 내가 부탁한 방식이 문제야?", "나는 → 상관없어 → 돕는 것은 → 하지만 필요해 → 네가 먼저 묻는 것을", "I don't mind ●HELPING, but I need you‿to‿ask me ●FIRST ↘"),
        Age1720ExpansionSeed(573, "화났지만 문자로 싸우고 싶진 않아", "📱", "감정이 올라온 상황에서 문자 논쟁을 피할 때", "I was frustrated, but I don't want to argue over text.", "나도 답답했지만 문자로 싸우고 싶지는 않아.", "우리 둘 다 진정됐을 때 통화하거나 만나서 얘기하자.", "Let's talk when we're both calmer, either on the phone or in person.", "I was upset, but I don't want to argue over text.", "Why did you stop replying?", "왜 답장을 안 했어?", "Do you want to talk now?", "지금 얘기하고 싶어?", "나는 → 답답했어 → 하지만 원하지 않아 → 다투는 것을 → 문자로", "I was ●FRUSTRATED, but I don't wanna‿●ARGUE over text ↘"),
        Age1720ExpansionSeed(574, "더 커지기 전에 이거 정리하자", "🧯", "오해가 커지기 전에 바로 풀고 싶을 때", "Can we clear this up before it turns into something bigger?", "이 일이 더 커지기 전에 우리 정리할 수 있을까?", "서로 다르게 이해한 부분이 뭔지만 먼저 확인하자.", "Let's first figure out what each of us understood differently.", "Can we sort this out before it becomes a bigger issue?", "Things have felt weird between us all day.", "오늘 하루 종일 우리 사이가 이상했어.", "What do you think we misunderstood?", "우리가 뭘 다르게 이해한 것 같아?", "할 수 있을까 → 우리가 정리하는 것을 → 이것을 → 더 큰 일이 되기 전에", "Can we clear this ●UP before‿it turns into something ●BIGGER ↗"),
        Age1720ExpansionSeed(575, "농담인 건 알지만 그래도 불편했어", "😐", "상대의 농담이 선을 넘었다고 차분히 말할 때", "I get that you were joking, but it still bothered me.", "네가 농담한 건 알지만 그래도 나는 불편했어.", "의도는 이해하지만 다음에는 그런 식으로는 말하지 않았으면 해.", "I know you didn't mean it badly, but I'd rather you not joke about that next time.", "I know you were joking, but it still bothered me.", "I was just kidding earlier.", "아까는 그냥 농담이었어.", "What part bothered you?", "어느 부분이 불편했어?", "나는 → 이해해 → 네가 농담했다는 것을 → 하지만 그것은 여전히 → 나를 불편하게 했어", "I get that you were ●JOKING, but it still ●BOTHERED me ↘"),
        Age1720ExpansionSeed(576, "쌓아두지 말고 더 일찍 말했어야 했어", "🗣️", "불만을 참다가 늦게 말한 것을 인정할 때", "I should've said something earlier instead of letting it build up.", "쌓이게 두지 말고 내가 더 일찍 말했어야 했어.", "처음 불편했을 때 말했으면 이렇게까지 되지는 않았을 것 같아.", "If I'd said something when it first bothered me, it probably wouldn't have gotten this far.", "I should have brought it up earlier instead of letting it build up.", "I didn't know this had been bothering you for that long.", "이게 그렇게 오래 신경 쓰였는지 몰랐어.", "Why didn't you say something sooner?", "왜 더 빨리 말하지 않았어?", "나는 → 말했어야 했어 → 무언가를 → 더 일찍 → 그것이 쌓이게 두는 대신", "I should've said something ●EARLIER instead‿of letting‿it build ●UP ↘"),
        Age1720ExpansionSeed(577, "오늘은 조금 혼자 있고 내일 얘기하자", "🌿", "감정을 정리하기 위해 잠깐 거리를 두고 싶을 때", "I need a little space tonight. We can talk tomorrow.", "오늘 밤은 조금 혼자 있을 시간이 필요해. 내일 이야기하자.", "대화를 피하려는 게 아니라 지금은 생각을 정리하고 싶어.", "I'm not avoiding the conversation. I just want some time to clear my head first.", "I need some space tonight. We can talk tomorrow.", "Do you want to keep talking about this?", "이 얘기 계속할래?", "Are you asking for space or ending the conversation?", "잠깐 거리 두자는 거야, 아니면 대화를 끝내자는 거야?", "나는 → 필요해 → 약간의 공간이 → 오늘 밤 → 우리는 이야기할 수 있어 → 내일", "I need‿a little ●SPACE tonight. We can talk to●MORROW ↘"),
        Age1720ExpansionSeed(578, "다 동의해야 가까운 건 아니잖아", "🫶", "친한 관계에서도 의견 차이가 가능하다고 말할 때", "I don't think we need to agree on everything to be close.", "가깝게 지내려면 모든 것에 동의해야 하는 건 아니라고 생각해.", "이 문제에 생각이 달라도 서로 존중할 수 있으면 괜찮아.", "We can disagree on this and still respect each other.", "I don't think we have to agree on everything to be close.", "We keep seeing this differently.", "우리는 계속 이걸 다르게 보네.", "Does that bother you?", "그게 신경 쓰여?", "나는 → 생각하지 않아 → 우리가 필요하다고 → 모든 것에 동의하는 것을 → 가까워지기 위해", "I don't think we need‿to‿a●GREE on everything to be ●CLOSE ↘"),
        Age1720ExpansionSeed(579, "바뀌면 그냥 말해줘, 사라지지 말고", "📨", "약속이나 관계에서 갑자기 연락이 끊기는 대신 알려달라고 할 때", "If something changes, just tell me instead of disappearing.", "뭔가 바뀌면 그냥 말해줘. 갑자기 사라지지는 말고.", "계획이 바뀌는 건 괜찮은데 아무 연락이 없는 게 더 힘들어.", "Plans changing is fine. It's the silence that makes it hard.", "If things change, just tell me instead of disappearing.", "I know I went quiet for a few days.", "며칠 동안 내가 연락을 안 한 건 알아.", "What would you rather I do next time?", "다음에는 내가 어떻게 했으면 좋겠어?", "만약 → 무언가가 바뀌면 → 그냥 말해줘 → 나에게 → 사라지는 대신", "If something ●CHANGES, just tell me instead‿of disap●PEARING ↘"),
        Age1720ExpansionSeed(580, "솔직하되 날카롭게 들리진 않게 연습 중이야", "🎯", "의견을 직접 말하면서도 공격적으로 들리지 않게 하고 싶을 때", "I'm trying to be more direct without sounding harsh.", "날카롭게 들리지 않으면서 더 직접적으로 말하려고 연습 중이야.", "돌려 말하다가 오히려 더 헷갈리게 하는 습관을 고치고 싶어.", "I tend to soften things so much that my point gets lost, and I'm trying to change that.", "I'm trying to be direct without coming across as harsh.", "You were really clear about that today.", "오늘은 그 부분을 정말 분명하게 말했네.", "Is being direct uncomfortable for you?", "직접 말하는 게 불편해?", "나는 → 노력하고 있어 → 더 직접적이 되려고 → 거칠게 들리지 않으면서", "I'm trying‿to‿be more di●RECT without sounding ●HARSH ↘"),

        Age1720ExpansionSeed(581, "목표엔 동의하지만 방법은 잘 모르겠어", "🎯", "목표와 수단을 구분해 의견을 말할 때", "I agree with the goal. I'm just not sure this is the best way to get there.", "목표에는 동의하지만 이게 거기에 가는 가장 좋은 방법인지는 잘 모르겠어.", "같은 결과를 내면서 부작용은 적은 다른 방법도 비교해보고 싶어.", "I'd like to compare a few other options that might get the same result with fewer downsides.", "I agree with the goal, but I'm not sure this is the best way to achieve it.", "So are you against the idea?", "그럼 이 아이디어에 반대하는 거야?", "What part of the approach worries you?", "이 방법에서 어떤 부분이 걱정돼?", "나는 → 동의해 → 목표에 → 나는 단지 확신하지 않아 → 이것이 가장 좋은 방법인지 → 거기에 가는", "I a●GREE with‿the‿goal. I'm just not sure this is‿the‿best ●WAY to get there ↘"),
        Age1720ExpansionSeed(582, "그럴듯하지만 숫자 출처부터 보고 싶어", "📊", "통계가 인상적이지만 출처를 확인하고 싶을 때", "That sounds convincing at first, but I want to see where the numbers came from.", "처음엔 설득력 있게 들리지만 그 숫자가 어디서 왔는지 보고 싶어.", "표본이 누구였는지랑 조사 시점도 같이 확인해야 할 것 같아.", "I also want to know who was surveyed and when the data was collected.", "It sounds convincing, but I want to know where the numbers came from.", "Those numbers look pretty strong.", "저 숫자들은 꽤 강하게 보이네.", "What would you want to verify?", "뭘 확인하고 싶어?", "그것은 → 들려 → 설득력 있게 → 처음에는 → 하지만 나는 원해 → 보는 것을 → 숫자가 어디서 왔는지", "That sounds con●VINCING at first, but I want‿to‿see where‿the‿●NUMBERS came from ↘"),
        Age1720ExpansionSeed(583, "우린 같은 문제의 다른 부분을 말하는 것 같아", "🧭", "논쟁 중 서로 초점이 다름을 정리할 때", "I think we're talking about two different parts of the same problem.", "우리가 같은 문제의 서로 다른 두 부분을 말하고 있는 것 같아.", "네가 원인을 말한다면 나는 그 결과를 말하고 있는 것 같아.", "I think you're talking about the cause, while I'm talking about the effect.", "I think we're focusing on two different parts of the same problem.", "It sounds like we're disagreeing again.", "우리 또 의견이 다른 것 같네.", "Where do you think our points split?", "우리 관점이 어디서 갈린다고 생각해?", "나는 → 생각해 → 우리가 말하고 있다고 → 두 개의 다른 부분을 → 같은 문제의", "I think we're talking‿about two ●DIFFERENT parts‿of‿the same ●PROBLEM ↘"),
        Age1720ExpansionSeed(584, "입장 정하기 전에 전체 주장을 듣고 싶어", "👂", "일부만 듣고 결론 내리지 않으려 할 때", "I'd rather hear the full argument before I decide where I stand.", "내 입장을 정하기 전에 전체 주장을 듣는 편이 좋겠어.", "지금 들은 한 부분만으로 찬반을 정하고 싶지는 않아.", "I don't want to pick a side based on one part of the argument.", "I'd rather hear the whole argument before I decide where I stand.", "So what do you think about it?", "그래서 넌 어떻게 생각해?", "You haven't made up your mind yet?", "아직 생각을 정하지 않았어?", "나는 → 차라리 듣고 싶어 → 전체 주장을 → 내가 결정하기 전에 → 어디에 설지", "I'd rather hear‿the‿full ●ARGUMENT before I decide where I ●STAND ↘"),
        Age1720ExpansionSeed(585, "완전히 동의하진 않아도 왜 그런진 이해해", "🤔", "반대 입장도 감정과 배경은 이해한다고 말할 때", "I can understand why people feel that way even if I don't fully agree.", "완전히 동의하지 않더라도 사람들이 왜 그렇게 느끼는지는 이해할 수 있어.", "그 경험을 직접 한 사람이라면 그렇게 볼 수도 있을 것 같아.", "If someone has lived through that experience, I can see why they'd view it that way.", "I can see why people feel that way even though I don't fully agree.", "That side doesn't make any sense to me.", "나는 그쪽 입장이 전혀 이해가 안 돼.", "Is there any part of it you do understand?", "그래도 이해되는 부분은 있어?", "나는 → 이해할 수 있어 → 왜 사람들이 그렇게 느끼는지 → 비록 내가 완전히 동의하지 않아도", "I can under●STAND why people feel that way even‿if I don't fully a●GREE ↘"),
        Age1720ExpansionSeed(586, "뭐가 있으면 네 생각이 바뀔 것 같아?", "🔄", "토론에서 상대가 어떤 근거에 열려 있는지 물을 때", "What would change your mind about this?", "어떤 게 있으면 이 문제에 대한 네 생각이 바뀔 것 같아?", "어떤 자료나 실제 사례가 나오면 다시 생각해볼 수 있어? ", "Is there any evidence or real-world example that would make you reconsider it?", "What would make you change your mind about this?", "I'm pretty confident about my view on this.", "나는 이 문제에 대한 내 생각이 꽤 확실해.", "Are you open to anything changing your mind?", "생각이 바뀔 가능성은 있어?", "무엇이 → 바꿀까 → 네 생각을 → 이것에 대해", "What would change your ●MIND about this ↗"),
        Age1720ExpansionSeed(587, "사례 하나로 전체를 증명하긴 부족해", "🧪", "개별 사례와 일반화의 차이를 지적할 때", "I don't think one example is enough to prove the whole point.", "사례 하나만으로 전체 주장을 증명하기에는 충분하지 않다고 생각해.", "반대되는 사례도 있는지 보고 전체 패턴을 봐야 할 것 같아.", "I'd want to see whether there are counterexamples and what the broader pattern looks like.", "I don't think a single example is enough to prove the whole point.", "But this example clearly shows the problem.", "그래도 이 사례가 문제를 분명히 보여주잖아.", "What else would you want to see?", "그럼 뭘 더 보고 싶어?", "나는 → 생각하지 않아 → 하나의 사례가 충분하다고 → 증명하기에 → 전체 요점을", "I don't think one ex●AMPLE is enough‿to‿prove‿the‿whole ●POINT ↘"),
        Age1720ExpansionSeed(588, "결국 이건 손익이 같이 있어서 어려워", "⚖️", "정책이나 선택의 트레이드오프를 말할 때", "The trade-off is what makes this harder than it sounds.", "서로 얻고 잃는 점이 같이 있다는 게 이 문제를 말처럼 단순하지 않게 만들어.", "한쪽을 개선하면 다른 쪽에 비용이 생길 수 있어서 같이 봐야 해.", "Improving one side can create a cost somewhere else, so I think we have to look at both.", "The trade-off is what makes this more complicated than it sounds.", "This seems like an easy choice to me.", "나는 이게 쉬운 선택처럼 보여.", "What trade-off are you thinking about?", "어떤 손익을 생각하고 있어?", "그 트레이드오프가 → 만드는 것이야 → 이것을 더 어렵게 → 들리는 것보다", "The ●TRADE-OFF is what makes this harder than‿it ●SOUNDS ↘"),
        Age1720ExpansionSeed(589, "나도 예전엔 그렇게 생각했는데 더 알고 바뀌었어", "📚", "새 정보 때문에 기존 의견을 바꾼 경험을 말할 때", "I used to think that too, but my view changed after I learned more about it.", "나도 예전엔 그렇게 생각했지만 더 알아본 뒤에 생각이 바뀌었어.", "처음엔 단순한 문제라고 봤는데 배경을 알수록 그렇게만 보긴 어렵더라.", "At first it seemed simple, but the more context I learned, the harder it was to see it that way.", "I used to think that too, but I changed my view after learning more about it.", "I've always seen it this way.", "나는 늘 이렇게 생각해왔어.", "What changed your view?", "뭐가 네 생각을 바꿨어?", "나는 → 예전에 생각했어 → 그것을 또한 → 하지만 내 관점이 바뀌었어 → 내가 더 배운 뒤에 → 그것에 대해", "I used‿to‿think that ●TOO, but my view ●CHANGED after I learned more about‿it ↘"),
        Age1720ExpansionSeed(590, "싸우자는 게 아니라 네 생각 과정을 알고 싶어", "🕊️", "논쟁을 관계 싸움으로 만들지 않고 이유를 묻고 싶을 때", "I don't want to turn this into a fight. I'm trying to understand your reasoning.", "이걸 싸움으로 만들고 싶은 게 아니라 네가 그렇게 생각한 이유를 이해하려는 거야.", "결론보다 어떻게 거기까지 생각했는지가 궁금해.", "I'm more interested in how you got there than in arguing about the conclusion.", "I'm not trying to turn this into a fight. I want to understand your reasoning.", "Why are you pushing back so hard?", "왜 그렇게 강하게 반박하는 거야?", "Are you asking about my conclusion or how I got there?", "내 결론을 묻는 거야, 아니면 어떻게 생각했는지를 묻는 거야?", "나는 → 원하지 않아 → 이것을 싸움으로 바꾸는 것을 → 나는 노력하고 있어 → 이해하려고 → 네 추론을", "I don't wanna‿turn this into‿a ●FIGHT. I'm trying‿to‿understand your ●REASONING ↘"),

        Age1720ExpansionSeed(591, "시간만 채우는 일보다 기술이 쌓이는 일을 찾고 있어", "🧰", "첫 일자리에서 성장 가능성을 우선할 때", "I'm looking for work where I can build skills, not just fill time.", "그냥 시간을 채우는 게 아니라 기술을 쌓을 수 있는 일을 찾고 있어.", "돈도 중요하지만 다음 기회로 이어질 경험을 얻고 싶어.", "Pay matters, but I also want experience that gives me something useful for the next step.", "I'm looking for work where I can build skills, not just pass the time.", "What kind of job are you looking for?", "어떤 일을 찾고 있어?", "Is pay the main thing you're looking at?", "급여가 가장 중요한 조건이야?", "나는 → 찾고 있어 → 일을 → 내가 기술을 쌓을 수 있는 → 그냥 시간을 채우는 게 아니라", "I'm looking‿for‿●WORK where I can build ●SKILLS, not just fill time ↘"),
        Age1720ExpansionSeed(592, "장기 목표는 모르지만 다음에 배울 건 알아", "🧭", "진로 전체는 불확실해도 가까운 학습 목표는 있을 때", "I'm not sure what I want long term, but I know what I want to learn next.", "장기적으로 뭘 원하는지는 확실하지 않지만 다음에 뭘 배우고 싶은지는 알아.", "일단 데이터 분석을 제대로 해보고 그다음 방향을 다시 보려고 해.", "For now I want to get solid at data analysis, then reassess where I want to go.", "I'm not sure what I want long term, but I know what I want to learn next.", "Do you know what career you want?", "어떤 진로를 원하는지 알아?", "So what's your next step?", "그럼 다음 단계는 뭐야?", "나는 → 확신하지 않아 → 내가 원하는 것을 → 장기적으로 → 하지만 나는 알아 → 내가 다음에 배우고 싶은 것을", "I'm not sure what I want long ●TERM, but I know what I want‿to‿learn ●NEXT ↘"),
        Age1720ExpansionSeed(593, "포트폴리오에 결과보다 생각 과정도 보여주고 싶어", "🗂️", "포트폴리오에 문제 해결 과정을 드러내고 싶을 때", "I'm trying to make my portfolio show how I think, not just what I finished.", "포트폴리오가 완성 결과뿐 아니라 내가 어떻게 생각하는지도 보여주게 만들려고 해.", "왜 그렇게 결정했는지와 중간에 바꾼 부분도 같이 설명하려고 해.", "I'm adding why I made certain decisions and what I changed along the way.", "I want my portfolio to show how I think, not just what I finished.", "Your portfolio has a lot of finished projects.", "포트폴리오에 완성된 프로젝트가 많네.", "What do you want people to understand about your process?", "사람들이 네 과정에서 뭘 이해했으면 해?", "나는 → 노력하고 있어 → 내 포트폴리오가 보여주게 → 내가 어떻게 생각하는지 → 내가 끝낸 것만이 아니라", "I'm trying‿to‿make my port●FOLIO show how I ●THINK, not just what I finished ↘"),
        Age1720ExpansionSeed(594, "AI는 아이디어와 맹점 확인에 쓰되 결정은 내가 해", "🤖", "AI를 보조 도구로 사용하되 판단을 넘기지 않을 때", "I use AI to brainstorm and check my blind spots, but I still want the final decision to be mine.", "AI는 아이디어를 내고 놓친 점을 확인하는 데 쓰지만 최종 결정은 내가 하고 싶어.", "초안이나 선택지를 넓히는 데 도움받고 마지막에는 내가 근거를 보고 결정해.", "I use it to widen my options, then I review the reasoning and make the call myself.", "I use AI to brainstorm and catch blind spots, but I want the final decision to stay mine.", "How do you use AI when you're working?", "일할 때 AI를 어떻게 써?", "What do you avoid handing over to it?", "어떤 부분은 AI에 맡기지 않아?", "나는 → 사용해 → AI를 → 아이디어를 내고 맹점을 확인하려고 → 하지만 나는 원해 → 최종 결정이 내 것이기를", "I use ●AI to brainstorm‿and‿check my blind ●SPOTS, but I still want‿the‿final de●CISION to be mine ↘"),
        Age1720ExpansionSeed(595, "내가 설명 못하면 배운 걸로 치지 않아", "🧠", "AI나 검색으로 얻은 답을 실제 이해와 구분할 때", "If I can't explain the answer myself, I don't count it as something I learned.", "내가 그 답을 직접 설명할 수 없다면 배운 것으로 치지 않아.", "답을 본 다음 화면을 닫고 내 말로 다시 설명해보려고 해.", "After I see an answer, I close it and try to explain the idea again in my own words.", "If I can't explain it myself, I don't consider it something I've learned.", "You found the answer pretty quickly.", "답을 꽤 빨리 찾았네.", "How do you check whether you actually understand it?", "진짜 이해했는지는 어떻게 확인해?", "만약 → 내가 설명할 수 없다면 → 답을 → 나 스스로 → 나는 세지 않아 → 그것을 → 내가 배운 것으로", "If I can't ex●PLAIN the answer my●SELF, I don't count‿it‿as something I ●LEARNED ↘"),
        Age1720ExpansionSeed(596, "알림을 줄이니까 집중이 덜 끊겨", "🔕", "디지털 알림이 집중력을 깨는 것을 줄이려 할 때", "I'm cutting down on notifications because they break my focus more than I realized.", "생각보다 알림이 집중을 많이 끊어서 줄이고 있어.", "메신저는 정해진 시간에 확인하고 대부분의 푸시는 꺼두려고 해.", "I'm checking messages at set times and turning off most push alerts.", "I'm reducing notifications because they interrupt my focus more than I realized.", "Why did you turn off so many notifications?", "왜 알림을 그렇게 많이 껐어?", "Has it actually made a difference?", "실제로 차이가 있어?", "나는 → 줄이고 있어 → 알림을 → 왜냐하면 그것들이 끊어 → 나의 집중을 → 내가 깨달은 것보다 더", "I'm cutting‿down‿on notifi●CATIONS because they break my ●FOCUS more than I realized ↘"),
        Age1720ExpansionSeed(597, "할 일보다 에너지에 맞춰 주간 계획을 짜", "⚡", "집중도와 에너지 수준을 고려해 일정을 배치할 때", "I'm trying to plan my week around my energy, not just my to-do list.", "할 일 목록만 보는 게 아니라 내 에너지에 맞춰 일주일을 계획하려고 해.", "집중 필요한 건 오전에 두고 단순한 건 피곤한 시간대로 옮기고 있어.", "I'm putting deep-focus work earlier and saving simpler tasks for when my energy drops.", "I'm planning my week around my energy, not just my to-do list.", "Your schedule looks different lately.", "요즘 일정 짜는 방식이 달라 보이네.", "What changed about the way you plan?", "계획하는 방식에서 뭐가 바뀌었어?", "나는 → 노력하고 있어 → 계획하려고 → 나의 주를 → 나의 에너지를 중심으로 → 할 일 목록만이 아니라", "I'm trying‿to‿plan my ●WEEK around my ●ENERGY, not just my to-do list ↘"),
        Age1720ExpansionSeed(598, "계획대로 안 되는 일도 들어갈 여유가 필요해", "🧱", "일정을 너무 빽빽하게 잡지 않으려 할 때", "I need to leave some room for things that don't go according to plan.", "계획대로 되지 않는 일들을 위한 여유를 조금 남겨둘 필요가 있어.", "하루를 100% 채우면 작은 변수 하나에도 전체 일정이 무너지더라.", "When I schedule every minute, one small delay can throw off the whole day.", "I need to leave some room for things that don't go according to plan.", "Why are you leaving that block empty?", "왜 그 시간은 비워뒀어?", "Do unexpected things come up that often?", "예상 못 한 일이 그렇게 자주 생겨?", "나는 → 필요해 → 남겨두는 것을 → 약간의 여유를 → 계획대로 되지 않는 것들을 위해", "I need‿to‿leave some ●ROOM for things that don't go according‿to‿●PLAN ↘"),
        Age1720ExpansionSeed(599, "시간이 없을 땐 거절하는 게 조금씩 나아지고 있어", "🚫", "과부하를 막기 위해 요청을 거절하는 연습을 할 때", "I'm getting better at saying no when I don't actually have the time.", "실제로 시간이 없을 때는 거절하는 게 점점 나아지고 있어.", "예전엔 일단 수락하고 나중에 힘들어했는데 이제는 일정부터 확인해.", "I used to say yes first and struggle later. Now I check my schedule before I commit.", "I'm getting better at saying no when I really don't have the time.", "You turned that request down?", "그 부탁 거절했어?", "Was it hard to say no?", "거절하기 어려웠어?", "나는 → 나아지고 있어 → 아니라고 말하는 데 → 내가 실제로 시간이 없을 때", "I'm getting ●BETTER at saying ●NO when I don't actually have‿the‿●TIME ↘"),
        Age1720ExpansionSeed(600, "머릿속 번역 없이 실제 대화를 해내고 싶어", "🗨️", "배운 영어를 실제 즉흥 대화로 연결하고 싶을 때", "I want to be able to handle real conversations without translating everything in my head.", "머릿속에서 모든 걸 번역하지 않고 실제 대화를 해낼 수 있고 싶어.", "완벽한 문장을 만들기보다 아는 표현으로 바로 이어가는 연습을 하고 싶어.", "I want to respond with the English I have instead of stopping to build a perfect sentence in Korean first.", "I want to handle real conversations without translating everything in my head first.", "What's your biggest goal with English now?", "지금 영어에서 가장 큰 목표가 뭐야?", "What slows you down most in real conversations?", "실제 대화에서 가장 많이 느려지는 건 뭐야?", "나는 → 원해 → 할 수 있기를 → 실제 대화를 처리하는 것을 → 모든 것을 번역하지 않고 → 내 머릿속에서", "I want‿to‿be able‿to‿handle real conver●SATIONS without translating ●EVERYTHING in my head ↘")
    )

    private fun sectionFor(id: Int): Int = when (id) {
        in 551..560 -> 6
        in 561..570 -> 7
        in 571..580 -> 8
        in 581..590 -> 9
        else -> 10
    }

    fun closingLines(id: Int): List<DialogueLine> = when (sectionFor(id)) {
        6 -> listOf(
            DialogueLine("A", "Makes sense. Keep me posted.", "좋아요. 진행 상황 알려주세요."),
            DialogueLine("B", "Will do.", "그럴게요.")
        )
        7 -> listOf(
            DialogueLine("A", "That sounds like a solid plan.", "괜찮은 계획 같아."),
            DialogueLine("B", "I'm trying to be more intentional about it.", "좀 더 생각해서 결정하려고 하고 있어.")
        )
        8 -> listOf(
            DialogueLine("A", "Thanks for saying that directly.", "직접 말해줘서 고마워."),
            DialogueLine("B", "I wanted to be clear without making it a bigger issue.", "일을 더 키우지 않으면서 분명하게 말하고 싶었어.")
        )
        9 -> listOf(
            DialogueLine("A", "Fair point. I can see that.", "일리 있네. 그 관점은 이해돼."),
            DialogueLine("B", "Yeah, I just want to look at the whole picture.", "응, 나는 전체를 보고 판단하고 싶어.")
        )
        else -> listOf(
            DialogueLine("A", "That sounds practical.", "현실적인 방법 같아."),
            DialogueLine("B", "I'm trying to use it in a way that actually helps me grow.", "실제로 성장에 도움이 되는 방식으로 해보려고 해.")
        )
    }
}

object Age1720LessonExpansionCatalog {
    val lessons: List<Lesson> = Age1720ExpansionContent.seeds.mapIndexed { index, seed ->
        Lesson(
            id = seed.id,
            title = seed.title,
            emoji = seed.emoji,
            situation = seed.situation,
            target = seed.target,
            meaning = seed.meaning,
            soundEnglish = seed.rhythmEnglish,
            soundKorean = Age1720ExpansionContent.soundKorean,
            connectedNote = Age1720ExpansionContent.connectedNote,
            ownPromptKo = seed.ownPromptKo,
            accepted = listOf(seed.acceptedAlternative, seed.target),
            coachLine = seed.coachEnglish,
            course = CourseLevel.AGE_17_20,
            courseLessonNumber = 51 + index
        )
    }
}

object Age1720DialogueExpansionCatalog {
    val dialogues: List<LessonDialogue> = Age1720ExpansionContent.seeds.map { seed ->
        LessonDialogue(
            lessonId = seed.id,
            lines = listOf(
                DialogueLine("A", seed.coachEnglish, seed.coachKorean),
                DialogueLine("B", seed.target, seed.meaning),
                DialogueLine("A", seed.followUpEnglish, seed.followUpKorean),
                DialogueLine("B", seed.detailEnglish, seed.ownPromptKo)
            ) + Age1720ExpansionContent.closingLines(seed.id)
        )
    }
}

object Age1720ThinkingExpansionCatalog {
    val guides: List<ThinkingGuide> = Age1720ExpansionContent.seeds.map { seed ->
        ThinkingGuide(seed.id, seed.thinkingOrder)
    }
}

object Age1720PronunciationQaExpansionCatalog {
    val guides: List<PronunciationQaGuide> = Age1720ExpansionContent.seeds.map { seed ->
        val intonation = if (seed.rhythmEnglish.contains("↗")) "↗" else "↘"
        PronunciationQaGuide(
            lessonId = seed.id,
            rhythmEnglish = seed.rhythmEnglish,
            slowKorean = "천천히: ${seed.target}",
            naturalKorean = "자연스럽게 연결해서: ${seed.target}",
            rhythm = "핵심어 강세 · 기능어 약화 · 연결 발음 · 문장 끝 $intonation"
        )
    }
}

object Age1720CourseSectionExpansionCatalog {
    val sections = listOf(
        CourseSection(6, "51~60 · 인턴·첫 직장·업무 소통", 551..560),
        CourseSection(7, "61~70 · 돈·계약·독립 생활", 561..570),
        CourseSection(8, "71~80 · 관계·갈등·경계", 571..580),
        CourseSection(9, "81~90 · 의견·토론·정보 판단", 581..590),
        CourseSection(10, "91~100 · 진로·디지털·AI·자기관리", 591..600)
    )
}
