package com.yamone.english

object Age1113ThinkingExpansionCatalog {
    val guides = listOf(
        ThinkingGuide(351, "거기에는 → 약점이 있어 → 그 주장 안에"),
        ThinkingGuide(352, "그것은 → 될 수 있어 → 반대 근거가"),
        ThinkingGuide(353, "나는 → 동의해 → 일부에 → 네가 말하는 것의"),
        ThinkingGuide(354, "하지만 → 나는 → 도달해 → 다른 결론에"),
        ThinkingGuide(355, "우리는 → 확인해야 해 → 그 가정이 사실인지"),
        ThinkingGuide(356, "그것은 → 좋은 → 반론이야"),
        ThinkingGuide(357, "나는 → 바꿀 수도 있어 → 나의 생각을 → 새 근거가 있다면"),
        ThinkingGuide(358, "우리 → 따져보자 → 장단점을 → 결정하기 전에"),
        ThinkingGuide(359, "어느 선택도 → 아니야 → 완벽한"),
        ThinkingGuide(360, "이 선택은 → 영향을 줄 수도 있어 → 우리에게 → 나중에"),
        ThinkingGuide(361, "우리는 → 생각해야 해 → 결과에 대해서"),
        ThinkingGuide(362, "우리는 → 필요해 → 대안 계획이 → 안 될 경우에"),
        ThinkingGuide(363, "그것은 → 가치가 있어 → 그 위험을 감수할 만큼?"),
        ThinkingGuide(364, "가장 쉬운 선택이 → 항상 → 최선은 아니야"),
        ThinkingGuide(365, "그것은 → 도움이 될지도 몰라 → 단기적으로"),
        ThinkingGuide(366, "그것은 → 더 나을 수도 있어 → 장기적으로"),
        ThinkingGuide(367, "우리 → 생각하자 → 누가 영향을 받을지"),
        ThinkingGuide(368, "우리는 → 또한 물어야 해 → 그것이 공정한지"),
        ThinkingGuide(369, "괜찮아 → 결정을 바꾸는 것은 → 새 정보가 들어오면"),
        ThinkingGuide(370, "우리는 → 책임져야 해 → 그 선택에 대해"),
        ThinkingGuide(371, "문자 메시지는 → 오해하기 쉬울 수 있어"),
        ThinkingGuide(372, "그 메시지는 → 다르게 들릴 수도 있어"),
        ThinkingGuide(373, "생각해 → 네가 올리기 전에 → 무언가를 온라인에"),
        ThinkingGuide(374, "너는 → 공유하면 안 돼 → 개인정보를 → 함부로"),
        ThinkingGuide(375, "물어봐 → 올리기 전에 → 다른 사람의 사진을"),
        ThinkingGuide(376, "우리 → 싸우지 말자 → 문자로"),
        ThinkingGuide(377, "나는 → 생각해 → 직접 이야기하는 게 더 낫다고"),
        ThinkingGuide(378, "우리 → 확인하자 → 그 게시물이 진짜인지"),
        ThinkingGuide(379, "나는 → 하지 않을 거야 → 바로 반응하는 것을"),
        ThinkingGuide(380, "우리는 → 존중해야 해 → 온라인에서도"),
        ThinkingGuide(381, "나는 → 원해 → 처리하는 것을 → 이것을 → 혼자"),
        ThinkingGuide(382, "나는 → 요청할게 → 도움을 → 필요하면"),
        ThinkingGuide(383, "나는 → 관리해야 해 → 나의 일정을 → 스스로"),
        ThinkingGuide(384, "나는 → 책임질게 → 고치는 것을 → 나의 실수를"),
        ThinkingGuide(385, "나는 → 원하지 않아 → 핑계를 대는 것을"),
        ThinkingGuide(386, "나는 → 아니었어 → 충분히 준비된"),
        ThinkingGuide(387, "나는 → 준비할게 → 더 일찍 → 다음에는"),
        ThinkingGuide(388, "그것은 → 나의 선택이었어 → 그래서 나는 책임질게"),
        ThinkingGuide(389, "나는 → 해볼게 → 그것을 해결하는 것을 → 혼자"),
        ThinkingGuide(390, "아는 것은 → 중요해 → 언제 도움을 요청해야 하는지도"),
        ThinkingGuide(391, "나는 → 관심이 생기고 있어 → 이것에 → 요즘"),
        ThinkingGuide(392, "나는 → 원해 → 이해하는 것을 → 왜 그것이 일어나는지"),
        ThinkingGuide(393, "나는 → 생각해 → 이것이 → 내가 잘하는 것이라고"),
        ThinkingGuide(394, "이 부분은 → 여전히 느껴져 → 어렵게"),
        ThinkingGuide(395, "나는 → 더 배우고 싶어 → 그것에 대해"),
        ThinkingGuide(396, "나는 → 해보고 싶어 → 이것을 → 실제로"),
        ThinkingGuide(397, "나는 → 아직 알아가는 중이야 → 내가 무엇에 관심 있는지"),
        ThinkingGuide(398, "나는 → 필요 없어 → 모든 것을 결정할 → 지금 당장"),
        ThinkingGuide(399, "나는 → 원해 → 탐색하는 것을 → 여러 가지를"),
        ThinkingGuide(400, "나는 → 원해 → 표현하는 것을 → 나 자신을 → 더 자신 있게")
    )
}
