package com.yamone.english

object Age1416ThinkingCatalog {
    val guides = listOf(
        ThinkingGuide(401, "나는 → 이해할 수 있어 → 왜 네가 그렇게 말하는지"),
        ThinkingGuide(402, "그것은 → 꼭 그런 것은 아니야"),
        ThinkingGuide(403, "나는 → 이해해 → 네 요점을 → 하지만 → 문제 하나가 보여"),
        ThinkingGuide(404, "나는 → 생각하지 않아 → 그것이 그렇게 단순하다고"),
        ThinkingGuide(405, "우리는 → 놓치고 있을 수도 있어 → 무언가를"),
        ThinkingGuide(406, "그것은 → 들려 → 합리적으로 → 이론적으로"),
        ThinkingGuide(407, "실제로는 → 그것이 → 더 복잡할 수도 있어"),
        ThinkingGuide(408, "나는 → 기울고 있어 → 두 번째 선택 쪽으로"),
        ThinkingGuide(409, "나는 → 원하지 않아 → 성급하게 결론 내리는 것을"),
        ThinkingGuide(410, "우리 → 확인하자 → 우리가 같은 것을 말하고 있는지"),
        ThinkingGuide(411, "무엇을 → 실제로 해결하려고 하고 있어 → 우리는?"),
        ThinkingGuide(412, "우리는 → 고려해야 해 → 장단점 사이의 균형을"),
        ThinkingGuide(413, "나는 → 원하지 않아 → 서둘러 결정하는 것을"),
        ThinkingGuide(414, "나는 → 기꺼이 타협할 수 있어 → 그 부분에서는"),
        ThinkingGuide(415, "그것은 → 될 거야 → 절대 받아들이기 어려운 조건이 → 나에게"),
        ThinkingGuide(416, "나는 → 생각해 → 이것이 준다고 → 우리에게 가장 많은 유연성을"),
        ThinkingGuide(417, "우리는 → 포기해야 할 거야 → 무언가를 → 어느 쪽이든"),
        ThinkingGuide(418, "나는 → 확신하지 않아 → 이득이 비용보다 크다고"),
        ThinkingGuide(419, "만약 우리가 → 이것을 선택한다면 → 우리는 → 준비해야 해 → 그 결과에"),
        ThinkingGuide(420, "우리 → 열어두자 → 우리의 선택지를 → 지금은"),
        ThinkingGuide(421, "나는 → 필요해 → 약간의 거리를 → 지금"),
        ThinkingGuide(422, "나는 → 원하지 않아 → 중간에 끼는 것을"),
        ThinkingGuide(423, "나는 → 생각하지 않아 → 그것이 공정하다고 → 나에게"),
        ThinkingGuide(424, "나는 → 차라리 바라 → 네가 직접 묻기를 → 나에게"),
        ThinkingGuide(425, "나는 → 느꼈어 → 압박을 → 따라가야 한다는"),
        ThinkingGuide(426, "나는 → 말했어야 했어 → 더 일찍"),
        ThinkingGuide(427, "나는 → 원하지 않아 → 이것이 더 큰 갈등이 되는 것을"),
        ThinkingGuide(428, "나는 → 사과할 수 있어 → 내 부분에 대해 → 전부 책임지지 않으면서"),
        ThinkingGuide(429, "나는 → 원해 → 우리가 솔직하기를 → 상처 주지 않으면서"),
        ThinkingGuide(430, "나는 → 생각해 → 우리가 필요하다고 → 더 분명한 경계를"),
        ThinkingGuide(431, "나는 → 노력하고 있어 → 균형 맞추는 것을 → 학교와 다른 모든 것을"),
        ThinkingGuide(432, "나는 → 필요해 → 현실적으로 보는 것이 → 내가 가진 시간을"),
        ThinkingGuide(433, "나는 → 원하지 않아 → 약속하는 것을 → 내가 유지할 수 없는 일에"),
        ThinkingGuide(434, "나는 → 필요해 → 알아내는 것이 → 지금 무엇이 가장 중요한지"),
        ThinkingGuide(435, "나는 → 뒤처지고 있어 → 그리고 → 더 나은 계획이 필요해"),
        ThinkingGuide(436, "나는 → 노력하고 있어 → 일하는 것을 → 더 독립적으로"),
        ThinkingGuide(437, "나는 → 필요해 → 피드백을 요청하는 것이 → 너무 늦기 전에"),
        ThinkingGuide(438, "나는 → 몰라 → 정확히 → 내가 아직 무엇을 하고 싶은지"),
        ThinkingGuide(439, "나는 → 관심이 있어 → 여러 다른 길에"),
        ThinkingGuide(440, "나는 → 원해 → 선택하는 것을 → 나에게 맞는 것을 기준으로 → 멋져 보이는 것보다"),
        ThinkingGuide(441, "나는 → 원하지 않아 → 게시물 하나가 → 내 전체 의견을 만드는 것을"),
        ThinkingGuide(442, "무언가를 보여주는 방식은 → 바꿀 수 있어 → 우리가 반응하는 방식을"),
        ThinkingGuide(443, "우리는 → 구분해야 해 → 사실과 의견을"),
        ThinkingGuide(444, "이것은 → 사실일 수도 있어 → 하지만 → 나는 확인하고 싶어"),
        ThinkingGuide(445, "나는 → 생각해 → 소셜 미디어가 → 작은 문제를 키울 수 있다고"),
        ThinkingGuide(446, "그것은 → 쉬워 → 자신을 비교하는 것이 → 온라인의 다른 사람들과"),
        ThinkingGuide(447, "나는 → 아직 알아가는 중이야 → 내가 실제로 무엇을 생각하는지"),
        ThinkingGuide(448, "나는 → 원해 → 설명하는 것을 → 내 관점을 → 싸움으로 만들지 않고"),
        ThinkingGuide(449, "나는 → 더 나아지고 있어 → 내가 무슨 뜻인지 말하는 데"),
        ThinkingGuide(450, "나는 → 원해 → 내 영어가 → 내 말처럼 들리기를 → 번역한 문장처럼 말고")
    )
}
