package com.yamone.english

object Age1416ThinkingExpansionCatalog {
    val guides = listOf(
        ThinkingGuide(451, "무슨 근거가 → 뒷받침해 → 그 주장을?"),
        ThinkingGuide(452, "그것은 → 보여줘 → 상관관계를 → 꼭 인과관계는 아니야"),
        ThinkingGuide(453, "나는 → 확신하지 않아 → 그 예시가 → 전체 그림을 대표한다고"),
        ThinkingGuide(454, "무엇이야 → 가장 강한 주장이 → 반대쪽에서?"),
        ThinkingGuide(455, "그 지적은 → 만들게 해 → 내가 → 수정하고 싶게 → 내 입장을 → 조금"),
        ThinkingGuide(456, "우리 → 보자 → 무엇을 → 당연하다고 여기고 있는지"),
        ThinkingGuide(457, "나는 → 생각해 → 그 결론이 → 넘어간다고 → 근거가 보여주는 범위를"),
        ThinkingGuide(458, "그것은 → 더 정확할 거야 → 조건을 붙이는 것이 → 그 주장에"),
        ThinkingGuide(459, "무슨 근거가 → 보여줄까 → 내가 틀렸다는 것을?"),
        ThinkingGuide(460, "우리 → 시작하자 → 그 지점들로 → 우리가 동의하는"),
        ThinkingGuide(461, "우리 → 나누자 → 그 문제를 → 더 작은 단계들로"),
        ThinkingGuide(462, "우리 → 분명히 하자 → 누가 책임지는지 → 무엇을"),
        ThinkingGuide(463, "무엇이야 → 가장 큰 위험이 → 이 계획 안에서?"),
        ThinkingGuide(464, "우리는 → 필요해 → 실행 가능한 해결책이 → 완벽한 것이 아니라"),
        ThinkingGuide(465, "우리 → 넣자 → 중간 점검을 → 우리가 방향을 벗어났는지 보기 위해"),
        ThinkingGuide(466, "누군가 → 동의하지 않아도 → 우리 → 평가하자 → 그 아이디어 자체를"),
        ThinkingGuide(467, "말해줘 → 나에게 → 바로 → 만약 내가 → 놓치고 있다면 → 무언가를"),
        ThinkingGuide(468, "우리 → 듣자 → 그 사람들로부터 → 영향을 받는 → 결정하기 전에"),
        ThinkingGuide(469, "만약 팀이 → 막혀 있다면 → 이제는 → 바꿀 때야 → 우리의 접근 방식을"),
        ThinkingGuide(470, "좋은 리더는 → 필요하지 않아 → 가지고 있을 → 모든 답을"),
        ThinkingGuide(471, "우리 → 확인하자 → 누가 출처인지 → 먼저"),
        ThinkingGuide(472, "우리는 → 결론 내리면 안 돼 → 헤드라인만으로"),
        ThinkingGuide(473, "나는 → 보고 싶어 → 무엇이 말해졌는지 → 원래 맥락에서"),
        ThinkingGuide(474, "그것은 → 중요해 → 언제 → 이 정보가 → 발표되었는지가"),
        ThinkingGuide(475, "우리는 → 고려해야 해 → 가능성을 → 이것이 AI로 생성되었다는"),
        ThinkingGuide(476, "우리 → 확인해보자 → 그 이미지가 → 진짜인지"),
        ThinkingGuide(477, "그 알고리즘은 → 좁히고 있을 수도 있어 → 내가 보는 것을"),
        ThinkingGuide(478, "나의 피드는 → 대표하지 않아 → 세상 전체를"),
        ThinkingGuide(479, "나는 → 알고 싶어 → 왜 그들이 필요로 하는지 → 내 데이터를 → 내가 공유하기 전에"),
        ThinkingGuide(480, "우리는 → 필요해 → 균형이 → 편리함과 개인정보 보호 사이에"),
        ThinkingGuide(481, "우리 → 바꿔보자 → 큰 목표를 → 무언가로 → 내가 이번 주에 할 수 있는"),
        ThinkingGuide(482, "나는 → 보고 싶어 → 이 선택이 → 맞는지 → 나의 가치와"),
        ThinkingGuide(483, "내가 잘하는 것은 → 항상 같지 않아 → 내가 즐기는 것과"),
        ThinkingGuide(484, "나는 → 생각하고 싶어 → 무엇을 → 내가 실제로 배웠는지 → 이 경험에서"),
        ThinkingGuide(485, "이 선택은 → 결정할 필요가 없어 → 나의 전체 미래를"),
        ThinkingGuide(486, "나는 → 측정하고 싶어 → 진전을 → 나의 기준으로 → 비교가 아니라"),
        ThinkingGuide(487, "나는 → 필요해 → 만드는 것이 → 휴식을 → 계획의 일부로"),
        ThinkingGuide(488, "나는 → 지키고 싶어 → 시간을 → 집중해서 일하기 위한"),
        ThinkingGuide(489, "만약 내가 → 유지할 수 없다면 → 그 목표를 → 더 나아 → 규모를 줄이는 것이"),
        ThinkingGuide(490, "꾸준함은 → 더 중요해 → 완벽하게 시작하는 것보다"),
        ThinkingGuide(491, "사람들은 → 경험할 수 있어 → 같은 상황을 → 아주 다르게"),
        ThinkingGuide(492, "둘 다 → 중요해 → 의도와 영향이"),
        ThinkingGuide(493, "만약 누군가가 → 말한다면 → 불편하다고 → 우리는 → 먼저 들어야 해"),
        ThinkingGuide(494, "다수 의견은 → 아니야 → 자동으로 → 공정한"),
        ThinkingGuide(495, "우리는 → 또한 고려해야 해 → 무엇을 → 그 규칙이 이루려는지"),
        ThinkingGuide(496, "내가 가진 이점들은 → 이용 가능하지 않을 수도 있어 → 모두에게"),
        ThinkingGuide(497, "좋은 토론은 → 비판해 → 생각을 → 사람들이 아니라"),
        ThinkingGuide(498, "생각을 바꾸는 것은 → 될 수 있어 → 배움의 일부가 → 약점이 아니라"),
        ThinkingGuide(499, "나는 → 할 수 있어야 해 → 말하는 것을 → 나는 모른다고 → 내가 확신하지 않을 때"),
        ThinkingGuide(500, "나는 → 원해 → 내 목소리를 쓰는 것을 → 동시에 → 공간을 남기면서 → 다른 사람들을 위해")
    )
}
