package com.yamone.english

object Age1416LessonCatalog {
    val lessons = listOf(
        Lesson(
            id = 401,
            title = "그렇게 말하는 이유는 이해돼",
            emoji = "💬",
            situation = "상대 관점은 이해하지만 의견이 다를 수 있을 때",
            target = "I can see why you'd say that.",
            meaning = "네가 왜 그렇게 말하는지는 이해돼.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "네 입장에서는 왜 그렇게 생각하는지 이해돼.",
            accepted = listOf("I can see why you feel that way.", "I can see why you'd say that."),
            coachLine = "Do you agree with me, then?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 1
        ),
        Lesson(
            id = 402,
            title = "꼭 그렇다고 볼 수는 없어",
            emoji = "⚖️",
            situation = "상대 주장이 항상 맞는 것은 아니라고 말할 때",
            target = "That's not necessarily the case.",
            meaning = "꼭 그렇다고 볼 수는 없어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "항상 그런 건 아니라고 생각해.",
            accepted = listOf("I don't think that's always the case.", "That's not necessarily the case."),
            coachLine = "Why do you think not?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 2
        ),
        Lesson(
            id = 403,
            title = "무슨 말인진 알겠는데 문제가 하나 있어",
            emoji = "🧩",
            situation = "상대 의견을 인정하면서 문제점을 말할 때",
            target = "I get your point, but I see one problem.",
            meaning = "무슨 말인지는 알겠는데 문제가 하나 보여.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "네 말은 이해하지만 한 가지 걸리는 점이 있어.",
            accepted = listOf("I understand your point, but I see one issue.", "I get your point, but I see one problem."),
            coachLine = "What's the problem?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 3
        ),
        Lesson(
            id = 404,
            title = "그렇게 단순한 문제는 아닌 것 같아",
            emoji = "🤔",
            situation = "복잡한 문제를 단순화하고 싶지 않을 때",
            target = "I don't think it's that simple.",
            meaning = "그렇게 단순한 문제는 아닌 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이건 한 가지 이유만으로 설명할 수 있는 문제는 아닌 것 같아.",
            accepted = listOf("I don't think it's as simple as that.", "I don't think it's that simple."),
            coachLine = "What makes it more complicated?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 4
        ),
        Lesson(
            id = 405,
            title = "우리가 놓치고 있는 게 있을 수도 있어",
            emoji = "🔍",
            situation = "논의에서 빠진 요소가 있을 수 있다고 말할 때",
            target = "We may be overlooking something.",
            meaning = "우리가 뭔가 놓치고 있을 수도 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "결정하기 전에 놓친 부분이 없는지 다시 보자.",
            accepted = listOf("We might be missing something important.", "We may be overlooking something."),
            coachLine = "What do you think we're missing?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 5
        ),
        Lesson(
            id = 406,
            title = "이론적으로는 그럴듯해",
            emoji = "📘",
            situation = "아이디어가 이론상 괜찮다고 말할 때",
            target = "That sounds reasonable in theory.",
            meaning = "이론적으로는 그럴듯해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이론만 보면 좋은 생각처럼 들려.",
            accepted = listOf("That sounds good in theory.", "That sounds reasonable in theory."),
            coachLine = "What about in practice?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 6
        ),
        Lesson(
            id = 407,
            title = "실제로 해보면 더 복잡할 수도 있어",
            emoji = "🛠️",
            situation = "현실에서는 계획이 다르게 작동할 수 있을 때",
            target = "In practice, it might be more complicated.",
            meaning = "실제로 해보면 더 복잡할 수도 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "현실에서는 예상보다 문제가 더 많을 수도 있어.",
            accepted = listOf("In reality, it could be more complicated.", "In practice, it might be more complicated."),
            coachLine = "What problems do you expect?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 7
        ),
        Lesson(
            id = 408,
            title = "나는 두 번째 쪽으로 좀 기울고 있어",
            emoji = "↘️",
            situation = "두 선택지 중 하나를 조금 더 선호할 때",
            target = "I'm leaning toward the second option.",
            meaning = "나는 두 번째 선택 쪽으로 좀 기울고 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "아직 확정은 아니지만 두 번째 안이 조금 더 좋아 보여.",
            accepted = listOf("I'm leaning toward the second choice for now.", "I'm leaning toward the second option."),
            coachLine = "Why are you leaning that way?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 8
        ),
        Lesson(
            id = 409,
            title = "성급하게 결론 내리고 싶진 않아",
            emoji = "⏸️",
            situation = "정보가 부족해 바로 판단하고 싶지 않을 때",
            target = "I don't want to jump to conclusions.",
            meaning = "성급하게 결론 내리고 싶진 않아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "조금 더 알아보기 전에 단정 짓고 싶진 않아.",
            accepted = listOf("I don't want to make assumptions too quickly.", "I don't want to jump to conclusions."),
            coachLine = "What else do you want to know?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 9
        ),
        Lesson(
            id = 410,
            title = "우리가 같은 얘기를 하는지부터 확인하자",
            emoji = "🗣️",
            situation = "서로 다른 뜻으로 말하고 있을 수 있을 때",
            target = "Let's make sure we're talking about the same thing.",
            meaning = "우리가 같은 얘기를 하고 있는지부터 확인하자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "서로 같은 뜻으로 말하는 건지 먼저 확인하자.",
            accepted = listOf("Let's make sure we mean the same thing.", "Let's make sure we're talking about the same thing."),
            coachLine = "What do you mean by it?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 10
        ),
        Lesson(
            id = 411,
            title = "우리가 실제로 해결하려는 게 뭐지?",
            emoji = "🎯",
            situation = "문제의 핵심 목표를 다시 확인할 때",
            target = "What are we actually trying to solve?",
            meaning = "우리가 실제로 해결하려는 게 뭐지?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "방법 얘기 전에 우리가 어떤 문제를 풀려는지부터 정하자.",
            accepted = listOf("What problem are we actually trying to solve?", "What are we actually trying to solve?"),
            coachLine = "Good question. What's the real problem?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 11
        ),
        Lesson(
            id = 412,
            title = "장단점 사이의 균형을 봐야 해",
            emoji = "⚖️",
            situation = "선택의 득실을 함께 고려할 때",
            target = "We should consider the trade-offs.",
            meaning = "장단점 사이의 균형을 봐야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "한쪽 장점만 보지 말고 포기해야 하는 것도 생각하자.",
            accepted = listOf("We should think about the trade-offs before deciding.", "We should consider the trade-offs."),
            coachLine = "What would we be giving up?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 12
        ),
        Lesson(
            id = 413,
            title = "결정을 서두르고 싶진 않아",
            emoji = "🕰️",
            situation = "중요한 결정을 천천히 하고 싶을 때",
            target = "I don't want to rush into a decision.",
            meaning = "결정을 서두르고 싶진 않아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "중요한 일이니까 충분히 생각하고 정하고 싶어.",
            accepted = listOf("I don't want to make this decision too quickly.", "I don't want to rush into a decision."),
            coachLine = "How much time do you need?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 13
        ),
        Lesson(
            id = 414,
            title = "그 부분은 타협할 수 있어",
            emoji = "🤝",
            situation = "협상에서 양보 가능한 부분을 말할 때",
            target = "I'm willing to compromise on that.",
            meaning = "그 부분은 타협할 수 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 조건은 내가 조금 양보할 수 있어.",
            accepted = listOf("I'm willing to be flexible on that point.", "I'm willing to compromise on that."),
            coachLine = "What part can't you compromise on?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 14
        ),
        Lesson(
            id = 415,
            title = "그건 나한텐 절대 받아들이기 어려운 조건이야",
            emoji = "🚫",
            situation = "절대 양보하기 어려운 조건을 말할 때",
            target = "That would be a deal-breaker for me.",
            meaning = "그건 나한텐 받아들이기 어려운 결정적 조건이야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 조건이 들어가면 나는 동의하기 어려울 것 같아.",
            accepted = listOf("That would be something I couldn't accept.", "That would be a deal-breaker for me."),
            coachLine = "Why is that a deal-breaker?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 15
        ),
        Lesson(
            id = 416,
            title = "이 방법이 가장 유연한 것 같아",
            emoji = "🧭",
            situation = "변경 가능성이 큰 선택을 선호할 때",
            target = "I think this gives us the most flexibility.",
            meaning = "이게 우리에게 가장 많은 선택의 여지를 주는 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "상황이 바뀌어도 조정하기 쉬운 방법 같아.",
            accepted = listOf("I think this option gives us the most flexibility.", "I think this gives us the most flexibility."),
            coachLine = "Why does flexibility matter here?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 16
        ),
        Lesson(
            id = 417,
            title = "어느 쪽을 선택해도 뭔가는 포기해야 해",
            emoji = "↔️",
            situation = "선택마다 희생이 있을 때",
            target = "We'd have to give something up either way.",
            meaning = "어느 쪽을 선택해도 뭔가는 포기해야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "어떤 선택을 해도 완벽하게 다 가질 수는 없어.",
            accepted = listOf("Either way, we'd have to give something up.", "We'd have to give something up either way."),
            coachLine = "What are we willing to give up?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 17
        ),
        Lesson(
            id = 418,
            title = "이득이 비용보다 큰지는 잘 모르겠어",
            emoji = "💸",
            situation = "비용 대비 효과가 충분한지 의심될 때",
            target = "I'm not convinced the benefits outweigh the costs.",
            meaning = "이득이 비용보다 크다는 확신은 없어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "좋아 보이긴 하지만 비용만큼 가치가 있는진 모르겠어.",
            accepted = listOf("I'm not sure the benefits are worth the cost.", "I'm not convinced the benefits outweigh the costs."),
            coachLine = "What cost worries you most?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 18
        ),
        Lesson(
            id = 419,
            title = "이걸 선택하면 결과도 감당할 준비를 해야 해",
            emoji = "⚠️",
            situation = "선택의 결과를 책임져야 할 때",
            target = "If we choose this, we need to be ready for the consequences.",
            meaning = "이걸 선택하면 그 결과도 감당할 준비를 해야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "결정만 하고 결과는 외면할 수는 없어.",
            accepted = listOf("If we choose this, we have to accept the consequences too.", "If we choose this, we need to be ready for the consequences."),
            coachLine = "What consequences do you expect?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 19
        ),
        Lesson(
            id = 420,
            title = "일단 선택지를 열어두자",
            emoji = "🔓",
            situation = "지금 당장 하나로 확정하고 싶지 않을 때",
            target = "Let's keep our options open for now.",
            meaning = "일단은 선택지를 열어두자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "정보가 더 생길 때까지 하나로 확정하지 말자.",
            accepted = listOf("Let's keep our options open until we know more.", "Let's keep our options open for now."),
            coachLine = "When should we decide?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 20
        ),
        Lesson(
            id = 421,
            title = "지금은 혼자 있을 시간이 조금 필요해",
            emoji = "🌿",
            situation = "감정이 복잡해 잠시 거리를 두고 싶을 때",
            target = "I need a little space right now.",
            meaning = "지금은 혼자 있을 시간이 조금 필요해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "지금 바로 얘기하기보다 잠깐 생각할 시간이 필요해.",
            accepted = listOf("I need some space to think right now.", "I need a little space right now."),
            coachLine = "Do you want to talk later?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 21
        ),
        Lesson(
            id = 422,
            title = "나를 중간에 끼우지 않았으면 해",
            emoji = "↔️",
            situation = "두 사람 갈등 사이에 끼고 싶지 않을 때",
            target = "I don't want to be put in the middle.",
            meaning = "나를 중간에 끼우지 않았으면 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "너희 둘 문제를 내가 대신 해결하게 하진 않았으면 해.",
            accepted = listOf("I don't want to be caught in the middle of this.", "I don't want to be put in the middle."),
            coachLine = "What would you like us to do instead?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 22
        ),
        Lesson(
            id = 423,
            title = "그건 나한테 공평하지 않은 것 같아",
            emoji = "⚖️",
            situation = "자신에게 불공정한 상황을 말할 때",
            target = "I don't think that's fair to me.",
            meaning = "그건 나한테 공평하지 않은 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "나한테만 책임을 다 주는 건 공평하지 않은 것 같아.",
            accepted = listOf("I don't think it's fair to put all of that on me.", "I don't think that's fair to me."),
            coachLine = "What would feel fair?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 23
        ),
        Lesson(
            id = 424,
            title = "다른 사람 통해 듣기보다 나한테 직접 물어봐",
            emoji = "🗨️",
            situation = "소문 대신 직접 확인해달라고 할 때",
            target = "I'd rather you ask me directly.",
            meaning = "다른 사람한테 듣기보다 나한테 직접 물어봤으면 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내 얘기라면 다른 사람 말보다 나한테 먼저 확인해줘.",
            accepted = listOf("I'd rather you ask me directly instead of hearing it from someone else.", "I'd rather you ask me directly."),
            coachLine = "Okay. What actually happened?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 24
        ),
        Lesson(
            id = 425,
            title = "나도 모르게 따라가야 할 것 같은 압박을 느꼈어",
            emoji = "😣",
            situation = "친구 압박 때문에 원하지 않는 선택을 했을 때",
            target = "I felt pressured to go along with it.",
            meaning = "나도 같이 따라가야 할 것 같은 압박을 느꼈어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "싫었지만 분위기 때문에 동의해야 할 것 같았어.",
            accepted = listOf("I felt pressured to agree even though I wasn't comfortable.", "I felt pressured to go along with it."),
            coachLine = "What made you feel pressured?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 25
        ),
        Lesson(
            id = 426,
            title = "내가 더 일찍 내 의견을 말했어야 했어",
            emoji = "🗣️",
            situation = "불편했지만 말하지 않은 것을 후회할 때",
            target = "I should've spoken up sooner.",
            meaning = "내가 더 일찍 말했어야 했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "불편하다고 느꼈을 때 바로 의견을 말했어야 했어.",
            accepted = listOf("I should've said something sooner.", "I should've spoken up sooner."),
            coachLine = "Why didn't you speak up?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 26
        ),
        Lesson(
            id = 427,
            title = "이게 더 큰 싸움으로 번지진 않았으면 해",
            emoji = "🕊️",
            situation = "갈등 확대를 막고 싶을 때",
            target = "I don't want this to turn into a bigger conflict.",
            meaning = "이게 더 큰 갈등으로 번지진 않았으면 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "문제는 해결하고 싶지만 싸움이 커지는 건 원하지 않아.",
            accepted = listOf("I want to solve this without turning it into a bigger fight.", "I don't want this to turn into a bigger conflict."),
            coachLine = "How can we keep it calm?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 27
        ),
        Lesson(
            id = 428,
            title = "내 잘못은 사과할 수 있지만 전부 내 탓은 아니야",
            emoji = "⚖️",
            situation = "자신의 책임과 상대 책임을 구분할 때",
            target = "I can apologize for my part without taking all the blame.",
            meaning = "내 잘못은 사과할 수 있지만 전부 내 탓을 할 수는 없어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내가 잘못한 부분은 인정하지만 모든 책임을 질 수는 없어.",
            accepted = listOf("I can own my part without taking responsibility for everything.", "I can apologize for my part without taking all the blame."),
            coachLine = "What part do you take responsibility for?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 28
        ),
        Lesson(
            id = 429,
            title = "솔직하되 상처 주지는 않았으면 해",
            emoji = "💛",
            situation = "정직함과 배려를 함께 지키고 싶을 때",
            target = "I want us to be honest without being hurtful.",
            meaning = "우리 서로 솔직하되 상처 주는 말은 하지 않았으면 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "기분을 숨기진 말되 공격적으로 말하진 말자.",
            accepted = listOf("I want us to be honest without attacking each other.", "I want us to be honest without being hurtful."),
            coachLine = "How can we say it honestly but kindly?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 29
        ),
        Lesson(
            id = 430,
            title = "우리 사이에 좀 더 분명한 선이 필요한 것 같아",
            emoji = "🚧",
            situation = "관계에서 경계를 명확히 하고 싶을 때",
            target = "I think we need clearer boundaries.",
            meaning = "우리 사이에 좀 더 분명한 경계가 필요한 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "어떤 건 괜찮고 어떤 건 불편한지 서로 분명히 말해야 할 것 같아.",
            accepted = listOf("I think we need clearer boundaries about what's okay and what's not.", "I think we need clearer boundaries."),
            coachLine = "What boundary do you want to set?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 30
        ),
        Lesson(
            id = 431,
            title = "학교랑 다른 일들을 균형 맞추려고 하고 있어",
            emoji = "📚",
            situation = "학업과 활동을 함께 관리하려 할 때",
            target = "I'm trying to balance school and everything else.",
            meaning = "학교랑 다른 일들을 균형 맞추려고 하고 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "공부, 활동, 쉬는 시간을 다 너무 무리하지 않게 맞추고 싶어.",
            accepted = listOf("I'm trying to balance school, activities, and time to rest.", "I'm trying to balance school and everything else."),
            coachLine = "What's hardest to balance?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 31
        ),
        Lesson(
            id = 432,
            title = "내가 가진 시간을 현실적으로 봐야 해",
            emoji = "⏳",
            situation = "시간 계획을 과하게 잡지 않으려 할 때",
            target = "I need to be realistic about how much time I have.",
            meaning = "내가 실제로 쓸 수 있는 시간을 현실적으로 봐야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "하고 싶은 걸 다 넣기보다 가능한 시간을 따져봐야 해.",
            accepted = listOf("I need to be realistic about what I can fit into my schedule.", "I need to be realistic about how much time I have."),
            coachLine = "How much time do you actually have?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 32
        ),
        Lesson(
            id = 433,
            title = "계속 못 할 일을 덜컥 맡고 싶진 않아",
            emoji = "📌",
            situation = "지속하기 어려운 약속을 피하고 싶을 때",
            target = "I don't want to commit to something I can't keep up with.",
            meaning = "계속 유지할 수 없는 일을 맡고 싶진 않아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "처음만 열심히 하고 나중에 못 할 약속은 하고 싶지 않아.",
            accepted = listOf("I don't want to commit to something I won't be able to maintain.", "I don't want to commit to something I can't keep up with."),
            coachLine = "What could you realistically commit to?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 33
        ),
        Lesson(
            id = 434,
            title = "지금 뭐가 가장 중요한지 정리해야 해",
            emoji = "🎯",
            situation = "여러 일 중 우선순위를 다시 정할 때",
            target = "I need to figure out what matters most right now.",
            meaning = "지금 뭐가 가장 중요한지 정리해야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "다 급해 보이지만 지금 먼저 해야 할 걸 정해야 해.",
            accepted = listOf("I need to decide what matters most right now.", "I need to figure out what matters most right now."),
            coachLine = "What's your top priority?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 34
        ),
        Lesson(
            id = 435,
            title = "밀리고 있어서 더 나은 계획이 필요해",
            emoji = "📉",
            situation = "학업 일정이 밀려 계획을 다시 세울 때",
            target = "I'm falling behind, and I need a better plan.",
            meaning = "계속 밀리고 있어서 더 나은 계획이 필요해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이대로 가면 더 늦어질 것 같아서 계획을 다시 짜야 해.",
            accepted = listOf("I'm falling behind, so I need to change how I'm managing my time.", "I'm falling behind, and I need a better plan."),
            coachLine = "What's making you fall behind?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 35
        ),
        Lesson(
            id = 436,
            title = "좀 더 스스로 해보려고 해",
            emoji = "💪",
            situation = "학업을 더 독립적으로 하려 할 때",
            target = "I'm trying to work more independently.",
            meaning = "좀 더 스스로 해보려고 하고 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "바로 답을 물어보기보다 먼저 내가 해결해보려고 해.",
            accepted = listOf("I'm trying to solve more things on my own before asking for answers.", "I'm trying to work more independently."),
            coachLine = "How is that going?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 36
        ),
        Lesson(
            id = 437,
            title = "너무 늦기 전에 피드백을 받아야 해",
            emoji = "📝",
            situation = "과제 초기에 피드백을 받고 싶을 때",
            target = "I need to ask for feedback before it's too late.",
            meaning = "너무 늦기 전에 피드백을 받아야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "다 끝낸 다음보다 중간에 방향이 맞는지 확인하고 싶어.",
            accepted = listOf("I want to get feedback before I finish the whole thing.", "I need to ask for feedback before it's too late."),
            coachLine = "Who will you ask?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 37
        ),
        Lesson(
            id = 438,
            title = "아직 정확히 뭘 하고 싶은지는 모르겠어",
            emoji = "🧭",
            situation = "진로를 확정하지 못했을 때",
            target = "I don't know exactly what I want to do yet.",
            meaning = "아직 정확히 뭘 하고 싶은지는 모르겠어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "관심 있는 건 있지만 미래를 하나로 정하진 못했어.",
            accepted = listOf("I have some interests, but I don't know exactly what I want to do yet.", "I don't know exactly what I want to do yet."),
            coachLine = "What are you interested in?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 38
        ),
        Lesson(
            id = 439,
            title = "서로 다른 길 몇 가지가 다 흥미로워",
            emoji = "🌐",
            situation = "여러 진로 분야에 동시에 관심이 있을 때",
            target = "I'm interested in several different paths.",
            meaning = "나는 서로 다른 몇 가지 길에 관심이 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "과학도 좋고 디자인도 좋아서 아직 하나만 고르기 어려워.",
            accepted = listOf("I'm interested in several different paths, so I don't want to choose too early.", "I'm interested in several different paths."),
            coachLine = "What paths are you considering?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 39
        ),
        Lesson(
            id = 440,
            title = "멋져 보이는 것보다 나한테 맞는 걸 고르고 싶어",
            emoji = "⭐",
            situation = "외부 평가보다 자신에게 맞는 선택을 하고 싶을 때",
            target = "I want to choose based on what fits me, not just what sounds impressive.",
            meaning = "멋져 보이는 것보다 나한테 맞는 걸 기준으로 고르고 싶어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "남들이 좋다고 하는 것보다 내가 잘 맞는 방향을 찾고 싶어.",
            accepted = listOf("I want to choose what fits me, not just what other people think sounds impressive.", "I want to choose based on what fits me, not just what sounds impressive."),
            coachLine = "What fits you best?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 40
        ),
        Lesson(
            id = 441,
            title = "게시물 하나만 보고 전체 의견을 정하고 싶진 않아",
            emoji = "📱",
            situation = "단일 게시물로 판단하지 않으려 할 때",
            target = "I don't want one post to shape my whole opinion.",
            meaning = "게시물 하나가 내 전체 생각을 정하게 하고 싶진 않아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "한 영상만 보고 주제 전체를 판단하고 싶지는 않아.",
            accepted = listOf("I don't want one video to shape my whole view of the issue.", "I don't want one post to shape my whole opinion."),
            coachLine = "What else would you look at?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 41
        ),
        Lesson(
            id = 442,
            title = "어떻게 보여주느냐에 따라 반응이 달라질 수 있어",
            emoji = "📰",
            situation = "프레이밍이 감정에 영향을 줄 때",
            target = "The way something is presented can change how we react to it.",
            meaning = "어떻게 보여주느냐에 따라 우리가 다르게 반응할 수 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "같은 사실도 어떤 식으로 보여주느냐에 따라 느낌이 달라질 수 있어.",
            accepted = listOf("The way information is presented can affect how people react to it.", "The way something is presented can change how we react to it."),
            coachLine = "Can you give an example?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 42
        ),
        Lesson(
            id = 443,
            title = "사실과 의견을 구분해야 해",
            emoji = "🔍",
            situation = "정보에서 사실과 의견을 분리할 때",
            target = "We should separate facts from opinions.",
            meaning = "사실과 의견을 구분해야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이 글에서 확인된 사실과 작성자의 의견을 따로 보자.",
            accepted = listOf("We should separate what we know from what someone thinks.", "We should separate facts from opinions."),
            coachLine = "Which part is a fact?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 43
        ),
        Lesson(
            id = 444,
            title = "맞을 수도 있지만 확인은 해보고 싶어",
            emoji = "✅",
            situation = "가능성은 인정하지만 검증하고 싶을 때",
            target = "This could be true, but I want to verify it.",
            meaning = "이게 사실일 수도 있지만 확인은 해보고 싶어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그럴듯해 보여도 다른 출처로 확인하고 싶어.",
            accepted = listOf("It sounds possible, but I want to verify it with another source.", "This could be true, but I want to verify it."),
            coachLine = "How would you verify it?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 44
        ),
        Lesson(
            id = 445,
            title = "소셜 미디어가 작은 문제를 더 크게 만들 수도 있어",
            emoji = "📣",
            situation = "온라인 확산이 갈등을 키울 수 있을 때",
            target = "I think social media can amplify small problems.",
            meaning = "소셜 미디어가 작은 문제를 크게 키울 수도 있다고 생각해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "원래 작은 일이 공유되면서 훨씬 크게 보일 수도 있어.",
            accepted = listOf("I think social media can make a small issue feel much bigger than it is.", "I think social media can amplify small problems."),
            coachLine = "Why does that happen?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 45
        ),
        Lesson(
            id = 446,
            title = "온라인에서는 다른 사람과 자신을 비교하기 쉬워",
            emoji = "📲",
            situation = "온라인 비교로 자신감이 흔들릴 때",
            target = "It's easy to compare yourself to people online.",
            meaning = "온라인에서는 다른 사람과 자신을 비교하기 쉬워.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "사람들이 좋은 순간만 올리니까 내 삶과 비교하기 쉬워.",
            accepted = listOf("It's easy to compare yourself to people who only post their best moments.", "It's easy to compare yourself to people online."),
            coachLine = "How does that affect people?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 46
        ),
        Lesson(
            id = 447,
            title = "나도 아직 이 문제에 대해 내가 뭘 생각하는지 정리 중이야",
            emoji = "💭",
            situation = "복잡한 주제에 대한 의견을 형성 중일 때",
            target = "I'm still figuring out what I actually think about it.",
            meaning = "나도 아직 이 문제에 대해 내가 실제로 어떻게 생각하는지 정리 중이야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "다른 의견을 더 듣고 나서 내 생각을 정하고 싶어.",
            accepted = listOf("I'm still figuring out what I think, so I want to hear more perspectives.", "I'm still figuring out what I actually think about it."),
            coachLine = "What are you still unsure about?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 47
        ),
        Lesson(
            id = 448,
            title = "내 의견을 싸움으로 만들지 않고 설명하고 싶어",
            emoji = "🗣️",
            situation = "논쟁 없이 자신의 의견을 설명하고 싶을 때",
            target = "I want to explain my view without turning it into an argument.",
            meaning = "내 의견을 싸움으로 만들지 않고 설명하고 싶어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "의견이 달라도 공격하지 않고 내 생각을 말하고 싶어.",
            accepted = listOf("I want to explain my view without making the conversation hostile.", "I want to explain my view without turning it into an argument."),
            coachLine = "What would keep it respectful?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 48
        ),
        Lesson(
            id = 449,
            title = "내가 무슨 뜻인지 말하는 게 점점 나아지고 있어",
            emoji = "📈",
            situation = "자기표현 능력의 성장을 느낄 때",
            target = "I'm getting better at saying what I mean.",
            meaning = "내가 무슨 뜻인지 제대로 말하는 게 점점 나아지고 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "예전보다 내 생각을 덜 돌려 말하고 더 분명히 표현할 수 있어.",
            accepted = listOf("I'm getting better at expressing what I actually mean.", "I'm getting better at saying what I mean."),
            coachLine = "What has helped you improve?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 49
        ),
        Lesson(
            id = 450,
            title = "번역한 문장 말고 내 말처럼 들리는 영어를 하고 싶어",
            emoji = "🎤",
            situation = "자연스러운 자기 영어를 목표로 할 때",
            target = "I want my English to sound like me, not like a translated sentence.",
            meaning = "내 영어가 번역한 문장처럼 말고 내 말처럼 들렸으면 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "한국어 문장을 바꾸는 게 아니라 영어로 바로 내 생각을 말하고 싶어.",
            accepted = listOf("I want to express my thoughts directly in English instead of translating first.", "I want my English to sound like me, not like a translated sentence."),
            coachLine = "What would make your English sound more natural?",
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = 50
        )
    )
}
