package com.yamone.english

object Age1113ThinkingCatalog {
    private val baseGuides = listOf(
        ThinkingGuide(301, "나는 → 생각하지 않아 → 그것이 핵심이라고"),
        ThinkingGuide(302, "해줄 수 있어 → 너가 주는 것을 → 나에게 → 예를 하나?"),
        ThinkingGuide(303, "나는 → 봐 → 그것을 → 조금 다르게"),
        ThinkingGuide(304, "무엇이 → 만들었어 → 너를 → 그렇게 생각하게?"),
        ThinkingGuide(305, "나는 → 생각해본 적이 없었어 → 그것을"),
        ThinkingGuide(306, "우리 → 보자 → 그 근거를"),
        ThinkingGuide(307, "우리는 → 필요해 → 더 나은 설명이"),
        ThinkingGuide(308, "나는 → 아니야 → 완전히 확신하는 → 아직"),
        ThinkingGuide(309, "그것은 → 달라져 → 네가 의미하는 것에 따라"),
        ThinkingGuide(310, "우리 → 비교하자 → 두 생각을"),
        ThinkingGuide(311, "우리는 → 필요해 → 정하는 것이 → 우리의 우선순위를"),
        ThinkingGuide(312, "그 마감은 → 더 가까워 → 내가 생각했던 것보다"),
        ThinkingGuide(313, "우리 → 나누자 → 그 일을"),
        ThinkingGuide(314, "나는 → 맡을게 → 이 부분을"),
        ThinkingGuide(315, "나는 → 생각해 → 우리가 조정해야 한다고 → 계획을"),
        ThinkingGuide(316, "우리 → 만나자 → 중간에서"),
        ThinkingGuide(317, "이 방법은 → 더 효율적일지도 몰라"),
        ThinkingGuide(318, "어떻게 → 하고 있어 → 우리는 → 지금까지?"),
        ThinkingGuide(319, "그것은 → 걸리고 있어 → 더 오래 → 예상보다"),
        ThinkingGuide(320, "우리 → 검토하자 → 그것을 → 끝났을 때"),
        ThinkingGuide(321, "나는 → 느꼈어 → 소외된"),
        ThinkingGuide(322, "나는 → 원하지 않아 → 이것이 큰일이 되는 것을"),
        ThinkingGuide(323, "나는 → 말했어야 했어 → 무언가를 → 더 일찍"),
        ThinkingGuide(324, "우리 → 정리하자 → 이것을"),
        ThinkingGuide(325, "그것은 → 넘었어 → 선을 → 나에게"),
        ThinkingGuide(326, "나는 → 차라리 바라 → 네가 퍼뜨리지 않기를 → 그것을"),
        ThinkingGuide(327, "우리 → 판단하지 말자 → 소문에 근거해서"),
        ThinkingGuide(328, "나는 → 생각해 → 내가 너를 오해했다고"),
        ThinkingGuide(329, "나는 → 원해 → 다시 쌓는 것을 → 우리 사이의 신뢰를"),
        ThinkingGuide(330, "나는 → 여기 있어 → 만약 네가 나를 필요로 한다면"),
        ThinkingGuide(331, "어디서 → 들었어 → 너는 → 그것을?"),
        ThinkingGuide(332, "어떻게 → 알아 → 우리는 → 그것이 사실인지?"),
        ThinkingGuide(333, "그 출처는 → 아닐지도 몰라 → 신뢰할 만한"),
        ThinkingGuide(334, "우리 → 확인하자 → 다른 출처를"),
        ThinkingGuide(335, "그 두 보고서는 → 맞지 않아"),
        ThinkingGuide(336, "그것은 → 오해였을 수도 있어"),
        ThinkingGuide(337, "있을 수도 있어 → 하나보다 많은 → 설명이"),
        ThinkingGuide(338, "나는 → 아니야 → 설득된 → 아직"),
        ThinkingGuide(339, "그것은 → 말이 돼 → 만약 그것이 사실이라면"),
        ThinkingGuide(340, "우리는 → 필요해 → 더 많은 정보가 → 결정하기 전에"),
        ThinkingGuide(341, "나는 → 원해 → 더 잘하게 되는 것을 → 이것을"),
        ThinkingGuide(342, "나는 → 노력하고 있어 → 만드는 것을 → 좋은 습관을"),
        ThinkingGuide(343, "나는 → 계속 → 미루고 있어 → 그것을"),
        ThinkingGuide(344, "나는 → 필요해 → 더 꾸준해지는 것이"),
        ThinkingGuide(345, "나는 → 만들었어 → 발전을 → 비록 느렸더라도"),
        ThinkingGuide(346, "나는 → 예전에는 생각했어 → 그것을 → 다르게"),
        ThinkingGuide(347, "나는 → 배웠어 → 많은 것을 → 그 실수에서"),
        ThinkingGuide(348, "나는 → 원해 → 도전하는 것을 → 나 자신에게 → 더"),
        ThinkingGuide(349, "나는 → 아직 아니야 → 내가 원하는 곳에"),
        ThinkingGuide(350, "나는 → 자랑스러워 → 내가 여기까지 온 것이")
    )

    val guides: List<ThinkingGuide> =
        baseGuides + Age1113ThinkingExpansionCatalog.guides
}
