package com.yamone.english

object Age1416PronunciationQaCatalog {
    val guides = listOf(
        PronunciationQaGuide(401, "I can SEE why you'd ●SAY that ↘", "아이 / 캔 / 씨 / 와이 / 유드 / 세이 / 댓", "아이 컨 ●씨 와이유드 ●세이 댓↘", "약-약-강-약-약-강-약 ↘"),
        PronunciationQaGuide(402, "That's not NEC-es-SAR-i-ly the ●CASE ↘", "댓츠 / 낫 / 네서세럴리 / 더 / 케이스", "댓츠 낫 네서●세럴리 더 ●케이스↘", "약-약-강-약-강 ↘"),
        PronunciationQaGuide(403, "I GET your POINT | but I see one ●PROB-lem ↘", "아이 / 겟 / 유어 / 포인트 / 벗 / 아이 / 씨 / 원 / 프라블럼", "아이 ●겟츄어 ●포인트 | 버라이 씨 원 ●프라블럼↘", "약-강-약-강 | 약-약-약-약-강 ↘"),
        PronunciationQaGuide(404, "I don't THINK it's that ●SIM-ple ↘", "아이 / 돈트 / 띵크 / 잇츠 / 댓 / 심플", "아이 돈 ●띵킷츠 댓 ●심플↘", "약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(405, "We may be over●LOOK-ing SOME-thing ↘", "위 / 메이 / 비 / 오버루킹 / 썸띵", "위 메이 비 오버●루킹 ●썸띵↘", "약-약-약-강-강 ↘"),
        PronunciationQaGuide(406, "That SOUNDS REA-son-a-ble in ●THE-o-ry ↘", "댓 / 사운즈 / 리저너블 / 인 / 띠어리", "댓 ●사운즈 ●리저너블 인 ●띠어리↘", "약-강-강-약-강 ↘"),
        PronunciationQaGuide(407, "In PRAC-tice | it might be more ●COM-pli-cat-ed ↘", "인 / 프랙티스 / 잇 / 마잇 / 비 / 모어 / 컴플리케이티드", "인 ●프랙티스 | 잇 마잇 비 모어 ●컴플리케이티드↘", "약-강 | 약-약-약-약-강 ↘"),
        PronunciationQaGuide(408, "I'm LEAN-ing toward the SEC-ond ●OP-tion ↘", "아임 / 리닝 / 터워드 / 더 / 세컨드 / 압션", "아임 ●리닝 터워드 더 세컨드 ●압션↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(409, "I don't WANT to JUMP to con●CLU-sions ↘", "아이 / 돈트 / 원트 / 투 / 점프 / 투 / 컨클루전즈", "아이 돈 ●워너 ●점프 터 컨●클루전즈↘", "약-약-강-약-강-약-강 ↘"),
        PronunciationQaGuide(410, "Let's make SURE we're TALK-ing about the SAME THING ↘", "렛츠 / 메이크 / 슈어 / 위어 / 토킹 / 어바웃 / 더 / 세임 / 띵", "렛츠 메익 ●슈어 위어 ●토킹 어바웃 더 ●세임 띵↘", "약-약-강-약-강-약-약-강-강 ↘"),
        PronunciationQaGuide(411, "WHAT are we AC-tu-al-ly trying to ●SOLVE ↘", "왓 / 아 / 위 / 액츄얼리 / 트라잉 / 투 / 솔브", "●워러위 ●액츄얼리 트라잉 터 ●솔브↘", "강-약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(412, "We should con●SID-er the TRADE-offs ↘", "위 / 슈드 / 컨시더 / 더 / 트레이드오프스", "위 슈드 컨●시더 더 ●트레이드오프스↘", "약-약-강-약-강 ↘"),
        PronunciationQaGuide(413, "I don't WANT to RUSH into a de●CI-sion ↘", "아이 / 돈트 / 원트 / 투 / 러쉬 / 인투 / 어 / 디시전", "아이 돈 ●워너 ●러쉬 인투 어 디●시전↘", "약-약-강-약-강-약-약-강 ↘"),
        PronunciationQaGuide(414, "I'm WILL-ing to ●COM-pro-mise on that ↘", "아임 / 윌링 / 투 / 캄프러마이즈 / 온 / 댓", "아임 ●윌링 터 ●캄프러마이즈 온 댓↘", "약-강-약-강-약-약 ↘"),
        PronunciationQaGuide(415, "That would be a ●DEAL-break-er for ME ↘", "댓 / 우드 / 비 / 어 / 딜브레이커 / 포 / 미", "댓 우드 비 어 ●딜브레이커 퍼 ●미↘", "약-약-약-약-강-약-강 ↘"),
        PronunciationQaGuide(416, "I THINK this gives us the most flex-i●BIL-i-ty ↘", "아이 / 띵크 / 디스 / 기브즈 / 어스 / 더 / 모스트 / 플렉서빌러티", "아이 ●띵크 디스 기브저스 더 모스트 플렉서●빌러리↘", "약-강-약-약-약-약-약-강 ↘"),
        PronunciationQaGuide(417, "We'd HAVE to give SOME-thing UP either WAY ↘", "위드 / 해브 / 투 / 기브 / 썸띵 / 업 / 이더 / 웨이", "위드 ●해프 터 기브 썸띵 ●업 이더 ●웨이↘", "약-강-약-약-약-강-약-강 ↘"),
        PronunciationQaGuide(418, "I'm not con●VINCED the BEN-e-fits out●WEIGH the COSTS ↘", "아임 / 낫 / 컨빈스트 / 더 / 베너핏츠 / 아웃웨이 / 더 / 코스츠", "아임 낫 컨●빈스트 더 ●베너핏츠 아웃●웨이 더 ●코스츠↘", "약-약-강-약-강-강-약-강 ↘"),
        PronunciationQaGuide(419, "If we CHOOSE this | we need to be READY for the ●CON-se-quen-ces ↘", "이프 / 위 / 추즈 / 디스 / 위 / 니드 / 투 / 비 / 레디 / 포 / 더 / 칸서퀀시즈", "이프 위 ●추즈 디스 | 위 니드 터 비 ●레디 퍼 더 ●칸서퀀시즈↘", "약-약-강-약 | 약-약-약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(420, "Let's KEEP our OP-tions OPEN for NOW ↘", "렛츠 / 킵 / 아워 / 압션즈 / 오픈 / 포 / 나우", "렛츠 ●킵 아워 ●압션즈 ●오픈 퍼 ●나우↘", "약-강-약-강-강-약-강 ↘"),
        PronunciationQaGuide(421, "I NEED a little SPACE right NOW ↘", "아이 / 니드 / 어 / 리를 / 스페이스 / 라잇 / 나우", "아이 ●니더 리를 ●스페이스 라잇 ●나우↘", "약-강-약-약-강-약-강 ↘"),
        PronunciationQaGuide(422, "I don't WANT to be PUT in the ●MID-dle ↘", "아이 / 돈트 / 원트 / 투 / 비 / 풋 / 인 / 더 / 미들", "아이 돈 ●워너 비 ●푸린 더 ●미들↘", "약-약-강-약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(423, "I don't THINK that's FAIR to ME ↘", "아이 / 돈트 / 띵크 / 댓츠 / 페어 / 투 / 미", "아이 돈 ●띵크 댓츠 ●페어 터 ●미↘", "약-약-강-약-강-약-강 ↘"),
        PronunciationQaGuide(424, "I'd RATH-er you ASK me di●RECT-ly ↘", "아이드 / 래더 / 유 / 애스크 / 미 / 더렉틀리", "아이드 ●래더 유 ●애스크 미 더●렉틀리↘", "약-강-약-강-약-강 ↘"),
        PronunciationQaGuide(425, "I FELT PRES-sured to go a●LONG with it ↘", "아이 / 펠트 / 프레셔드 / 투 / 고 / 얼롱 / 위드 / 잇", "아이 ●펠트 ●프레셔드 터 고 어●롱 위딧↘", "약-강-강-약-약-강-약-약 ↘"),
        PronunciationQaGuide(426, "I SHOULD've SPO-ken UP ●SOON-er ↘", "아이 / 슈드어브 / 스포큰 / 업 / 수너", "아이 ●슈더브 ●스포큰 업 ●수너↘", "약-강-강-약-강 ↘"),
        PronunciationQaGuide(427, "I don't WANT this to turn into a BIG-ger ●CON-flict ↘", "아이 / 돈트 / 원트 / 디스 / 투 / 턴 / 인투 / 어 / 비거 / 칸플릭트", "아이 돈 ●원트 디스 터 턴 인투 어 ●비거 ●칸플릭트↘", "약-약-강-약-약-약-약-약-강-강 ↘"),
        PronunciationQaGuide(428, "I can a●POL-o-gize for my PART | without taking all the ●BLAME ↘", "아이 / 캔 / 어팔러자이즈 / 포 / 마이 / 파트 / 위다웃 / 테이킹 / 올 / 더 / 블레임", "아이 컨 어●팔러자이즈 퍼 마이 ●파트 | 위다웃 테이킹 올 더 ●블레임↘", "약-약-강-약-약-강 | 약-약-약-약-강 ↘"),
        PronunciationQaGuide(429, "I WANT us to be HON-est | without being ●HURT-ful ↘", "아이 / 원트 / 어스 / 투 / 비 / 아너스트 / 위다웃 / 비잉 / 허트풀", "아이 ●원터스 터 비 ●아너스트 | 위다웃 비잉 ●허트풀↘", "약-강-약-약-약-강 | 약-약-강 ↘"),
        PronunciationQaGuide(430, "I THINK we need CLEAR-er ●BOUND-a-ries ↘", "아이 / 띵크 / 위 / 니드 / 클리어러 / 바운더리즈", "아이 ●띵크 위 니드 ●클리어러 ●바운더리즈↘", "약-강-약-약-강-강 ↘"),
        PronunciationQaGuide(431, "I'm TRY-ing to BAL-ance SCHOOL and EV-ry-thing ELSE ↘", "아임 / 트라잉 / 투 / 밸런스 / 스쿨 / 앤드 / 에브리띵 / 엘스", "아임 ●트라잉 터 ●밸런스 ●스쿨 앤 에브리띵 ●엘스↘", "약-강-약-강-강-약-약-강 ↘"),
        PronunciationQaGuide(432, "I NEED to be re-al●IS-tic about how much TIME I HAVE ↘", "아이 / 니드 / 투 / 리얼리스틱 / 어바웃 / 하우 / 머치 / 타임 / 아이 / 해브", "아이 ●니드 터 리얼●리스틱 어바웃 하우 머치 ●타임 아이 ●해브↘", "약-강-약-강-약-약-약-강-약-강 ↘"),
        PronunciationQaGuide(433, "I don't WANT to com●MIT to something I can't KEEP UP with ↘", "아이 / 돈트 / 원트 / 투 / 커밋 / 투 / 썸띵 / 아이 / 캔트 / 킵 / 업 / 위드", "아이 돈 ●워너 커●밋 터 썸띵 아이 캔트 ●킵업 윗↘", "약-약-강-약-강-약-약-약-약-강-강-약 ↘"),
        PronunciationQaGuide(434, "I NEED to figure OUT what MAT-ters most right NOW ↘", "아이 / 니드 / 투 / 피겨 / 아웃 / 왓 / 매터즈 / 모스트 / 라잇 / 나우", "아이 ●니드 터 피겨●아웃 왓 ●매터즈 모스트 라잇 ●나우↘", "약-강-약-약-강-약-강-약-약-강 ↘"),
        PronunciationQaGuide(435, "I'm FALL-ing be●HIND | and I need a BET-ter PLAN ↘", "아임 / 폴링 / 비하인드 / 앤드 / 아이 / 니드 / 어 / 베러 / 플랜", "아임 ●폴링 비●하인드 | 앤 아이 니더 ●베러 ●플랜↘", "약-강-강 | 약-약-약-약-강-강 ↘"),
        PronunciationQaGuide(436, "I'm TRY-ing to WORK more in-de●PEND-ent-ly ↘", "아임 / 트라잉 / 투 / 워크 / 모어 / 인더펜던틀리", "아임 ●트라잉 터 ●워크 모어 인더●펜던틀리↘", "약-강-약-강-약-강 ↘"),
        PronunciationQaGuide(437, "I NEED to ASK for FEED-back before it's too LATE ↘", "아이 / 니드 / 투 / 애스크 / 포 / 피드백 / 비포어 / 잇츠 / 투 / 레잇", "아이 ●니드 터 ●애스크 퍼 ●피드백 비포어 잇츠 투 ●레잇↘", "약-강-약-강-약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(438, "I don't KNOW ex●ACT-ly what I want to DO yet ↘", "아이 / 돈트 / 노우 / 이그잭틀리 / 왓 / 아이 / 원트 / 투 / 두 / 옛", "아이 돈 ●노우 이그●잭틀리 왓 아이 워너 ●두 옛↘", "약-약-강-강-약-약-약-약-강-약 ↘"),
        PronunciationQaGuide(439, "I'm ●IN-ter-est-ed in SEV-er-al different PATHS ↘", "아임 / 인터레스티드 / 인 / 세버럴 / 디프런트 / 패쓰", "아임 ●인트러스티드 인 ●세버럴 디프런트 ●패쓰↘", "약-강-약-강-약-강 ↘"),
        PronunciationQaGuide(440, "I WANT to CHOOSE based on what FITS me | not just what sounds im●PRES-sive ↘", "아이 / 원트 / 투 / 추즈 / 베이스트 / 온 / 왓 / 핏츠 / 미 / 낫 / 저스트 / 왓 / 사운즈 / 임프레시브", "아이 ●워너 ●추즈 베이스트 온 왓 ●핏츠 미 | 낫 저스트 왓 사운즈 임●프레시브↘", "약-강-약-강-약-약-약-강-약 | 약-약-약-약-강 ↘"),
        PronunciationQaGuide(441, "I don't WANT one POST to shape my whole o●PIN-ion ↘", "아이 / 돈트 / 원트 / 원 / 포스트 / 투 / 쉐입 / 마이 / 홀 / 어피니언", "아이 돈 ●원 원 ●포스트 터 쉐입 마이 홀 어●피니언↘", "약-약-강-약-강-약-약-약-약-강 ↘"),
        PronunciationQaGuide(442, "The WAY something is pre●SENT-ed can change how we re●ACT to it ↘", "더 / 웨이 / 썸띵 / 이즈 / 프리젠티드 / 캔 / 체인지 / 하우 / 위 / 리액트 / 투 / 잇", "더 ●웨이 썸띵 이즈 프리●젠티드 컨 체인지 하우 위 리●액트 터 잇↘", "약-강-약-약-강-약-약-약-약-강-약-약 ↘"),
        PronunciationQaGuide(443, "We should ●SEP-a-rate FACTS from o●PIN-ions ↘", "위 / 슈드 / 세퍼레잇 / 팩츠 / 프럼 / 어피니언즈", "위 슈드 ●세퍼레잇 ●팩츠 프럼 어●피니언즈↘", "약-약-강-강-약-강 ↘"),
        PronunciationQaGuide(444, "This could be TRUE | but I want to ●VER-i-fy it ↘", "디스 / 쿠드 / 비 / 트루 / 벗 / 아이 / 원트 / 투 / 베러파이 / 잇", "디스 쿠드 비 ●트루 | 버라이 ●워너 ●베러파이잇↘", "약-약-약-강 | 약-약-강-약-강-약 ↘"),
        PronunciationQaGuide(445, "I THINK social ME-di-a can ●AM-pli-fy small PROB-lems ↘", "아이 / 띵크 / 소셜 / 미디어 / 캔 / 앰플러파이 / 스몰 / 프라블럼즈", "아이 ●띵크 소셜 ●미디어 컨 ●앰플러파이 스몰 ●프라블럼즈↘", "약-강-약-강-약-강-약-강 ↘"),
        PronunciationQaGuide(446, "It's EA-sy to com●PARE yourself to people on●LINE ↘", "잇츠 / 이지 / 투 / 컴페어 / 유어셀프 / 투 / 피플 / 온라인", "잇츠 ●이지 터 컴●페어 유어셀프 터 피플 온●라인↘", "약-강-약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(447, "I'm STILL figuring OUT what I AC-tu-al-ly THINK about it ↘", "아임 / 스틸 / 피겨링 / 아웃 / 왓 / 아이 / 액츄얼리 / 띵크 / 어바웃 / 잇", "아임 ●스틸 피겨링●아웃 왓 아이 ●액츄얼리 ●띵커바우릿↘", "약-강-약-강-약-약-강-강-약-약 ↘"),
        PronunciationQaGuide(448, "I WANT to ex●PLAIN my VIEW | without turning it into an ●AR-gu-ment ↘", "아이 / 원트 / 투 / 익스플레인 / 마이 / 뷰 / 위다웃 / 터닝 / 잇 / 인투 / 언 / 아규먼트", "아이 ●워너 익스●플레인 마이 ●뷰 | 위다웃 터닝잇 인투 언 ●아규먼트↘", "약-강-약-강-약-강 | 약-약-약-약-약-강 ↘"),
        PronunciationQaGuide(449, "I'm GET-ting BET-ter at saying what I MEAN ↘", "아임 / 게팅 / 베러 / 앳 / 세잉 / 왓 / 아이 / 민", "아임 ●게링 ●베러랫 세잉 왓 아이 ●민↘", "약-강-강-약-약-약-약-강 ↘"),
        PronunciationQaGuide(450, "I WANT my ENG-lish to sound like ME | not like a translated ●SEN-tence ↘", "아이 / 원트 / 마이 / 잉글리시 / 투 / 사운드 / 라이크 / 미 / 낫 / 라이크 / 어 / 트랜슬레이티드 / 센턴스", "아이 ●원 마이 ●잉글리시 터 사운드 라이크 ●미 | 낫 라이커 트랜슬레이티드 ●센턴스↘", "약-강-약-강-약-약-약-강 | 약-약-약-약-강 ↘")
    )
}
