package com.yamone.english

object Age1416LessonExpansionCatalog {
    private data class Seed(
        val number: Int, val title: String, val emoji: String, val situation: String,
        val target: String, val meaning: String, val ownPromptKo: String,
        val acceptedVariant: String, val coachLine: String,
        val supportEnglish: String, val supportKorean: String
    )

    private val seeds = listOf(
        Seed(51, "그 주장을 뒷받침하는 근거가 뭐야?", "🔎", "주장의 근거를 구체적으로 확인할 때", "What evidence supports that claim?", "그 주장을 뒷받침하는 근거가 뭐야?", "그 주장을 믿기 전에 어떤 근거가 있는지 확인하고 싶어.", "What evidence do we have to support that claim?", "What kind of evidence would convince you?", "I'd like to see where the claim came from and whether the evidence is reliable.", "그 주장이 어디서 나왔고 근거가 믿을 만한지 보고 싶어."),
        Seed(52, "상관관계가 있다고 원인이라는 뜻은 아니야", "🔗", "두 현상이 함께 나타난다고 원인으로 단정할 때", "That shows a correlation, not necessarily causation.", "그건 상관관계를 보여주는 거지, 꼭 인과관계라는 뜻은 아니야.", "둘이 같이 변한다고 해서 하나가 다른 하나의 원인이라고 바로 말하긴 어려워.", "Those two things are related, but that doesn't prove one caused the other.", "What else could explain the pattern?", "There could be another factor affecting both of them.", "둘 다에 영향을 주는 다른 요인이 있을 수도 있어."),
        Seed(53, "그 예시가 전체를 대표하진 않을 수도 있어", "🧩", "한 사례를 전체로 일반화하려 할 때", "I'm not sure that example represents the whole picture.", "그 예시가 전체 상황을 대표한다고는 확신 못 하겠어.", "사례 하나만 보고 모든 경우가 그렇다고 판단하고 싶진 않아.", "One example might not represent everyone or every situation.", "What would give us a fuller picture?", "We'd need more examples from different people and situations.", "다른 사람들과 상황에서 나온 사례를 더 봐야 할 것 같아."),
        Seed(54, "반대쪽의 가장 강한 주장은 뭘까?", "↔️", "반대 입장을 공정하게 이해하고 싶을 때", "What's the strongest argument on the other side?", "반대쪽에서 가장 강한 주장은 뭐라고 생각해?", "내 생각만 확인하지 말고 반대 입장에서 가장 설득력 있는 점도 보고 싶어.", "What's the best argument someone on the other side could make?", "Why is it important to consider that?", "If I understand the strongest objection, I can judge my own view more fairly.", "가장 강한 반론을 이해해야 내 입장도 더 공정하게 볼 수 있어."),
        Seed(55, "그 지적 때문에 내 입장을 조금 수정해야겠어", "📝", "좋은 반론을 듣고 자신의 입장을 조정할 때", "That point makes me want to revise my position a little.", "그 지적 때문에 내 입장을 조금 수정하고 싶어.", "핵심 생각은 같지만 그 부분은 인정해서 내 주장을 조금 바꾸고 싶어.", "That point changes part of how I see the issue.", "Does it change your whole view?", "Not completely, but it changes how strongly I'd make one part of the argument.", "전부는 아니지만 한 부분을 얼마나 강하게 주장할지는 달라져."),
        Seed(56, "우리가 당연하다고 가정하는 게 뭔지 보자", "🧠", "논의 속 숨은 전제를 확인할 때", "Let's look at what we're taking for granted.", "우리가 당연하다고 가정하고 있는 게 뭔지 보자.", "논의를 시작하기 전에 사실이라고 전제한 것부터 확인하자.", "Let's identify the assumptions we're making without noticing.", "What assumption stands out to you?", "We're assuming everyone has the same priorities, and that may not be true.", "모두가 같은 우선순위를 가진다고 가정하고 있는데 아닐 수도 있어."),
        Seed(57, "그 결론은 근거보다 너무 멀리 간 것 같아", "📏", "자료보다 과도한 결론이 나왔을 때", "I think that conclusion goes beyond what the evidence shows.", "그 결론은 근거가 보여주는 것보다 너무 멀리 간 것 같아.", "자료가 말해주는 범위까지만 결론을 내리는 게 좋겠어.", "I think the claim is stronger than the evidence can support.", "Which part goes too far?", "The evidence shows a small effect, but the conclusion says it always happens.", "근거는 작은 효과만 보여주는데 결론은 항상 그렇다고 말하고 있어."),
        Seed(58, "그 주장에는 조건을 붙이는 게 더 정확해", "🎯", "너무 단정적인 표현을 더 정확하게 다듬을 때", "It would be more accurate to qualify that claim.", "그 주장에 조건을 붙여 말하는 게 더 정확할 거야.", "'항상'이라고 하기보다 어떤 경우에 그런지 말하는 편이 정확해.", "It would be more accurate to make the claim less absolute.", "How would you qualify it?", "I'd say it happens in some cases, especially under certain conditions.", "일부 경우, 특히 특정 조건에서 그렇다고 말하겠어."),
        Seed(59, "내가 틀렸다는 걸 보여줄 근거는 뭘까?", "🧪", "자신의 생각을 반증할 수 있는 조건을 생각할 때", "What evidence would show that I'm wrong?", "내가 틀렸다는 걸 보여줄 근거는 뭘까?", "내 생각과 반대되는 결과가 나오면 무엇을 인정해야 하는지 미리 생각해보고 싶어.", "What evidence would make me reconsider my conclusion?", "Why ask that about your own view?", "It keeps me from only looking for information that agrees with me.", "내 생각과 맞는 정보만 찾는 걸 막아줘."),
        Seed(60, "우리가 동의하는 부분부터 정리하자", "🤝", "논쟁에서 공통점을 먼저 찾을 때", "Let's start with the points we agree on.", "우리가 동의하는 부분부터 정리하자.", "차이점만 보기 전에 서로 같은 생각을 가진 부분부터 확인하자.", "Let's begin with what we already agree about.", "How could that help?", "It gives us common ground before we work through the disagreement.", "의견 차이를 다루기 전에 공통 기반을 만들 수 있어."),
        Seed(61, "문제를 더 작은 단계로 나누자", "🧱", "복잡한 문제를 실행 가능한 단계로 나눌 때", "Let's break the problem into smaller steps.", "문제를 더 작은 단계로 나누자.", "한꺼번에 해결하려 하지 말고 지금 할 수 있는 단계부터 나눠보자.", "Let's divide the problem into smaller, manageable steps.", "What should the first step be?", "First, let's define exactly what needs to be finished today.", "먼저 오늘 끝내야 하는 게 정확히 뭔지 정하자."),
        Seed(62, "누가 무엇을 맡을지 분명히 하자", "📋", "팀 역할이 겹치거나 빠질 수 있을 때", "Let's make it clear who's responsible for what.", "누가 무엇을 맡을지 분명히 하자.", "일이 겹치거나 빠지지 않도록 담당을 정확히 정하자.", "Let's clarify who owns each part of the work.", "What needs to be assigned first?", "We should assign the research, the draft, and the final check separately.", "조사, 초안, 최종 확인을 따로 맡기면 좋겠어."),
        Seed(63, "이 계획의 가장 큰 위험 요소가 뭐야?", "⚠️", "계획을 시작하기 전에 실패 가능성을 점검할 때", "What's the biggest risk in this plan?", "이 계획에서 가장 큰 위험 요소가 뭐야?", "잘될 거라는 생각만 하지 말고 가장 먼저 틀어질 수 있는 부분을 보자.", "What is most likely to cause this plan to fail?", "What risk do you see?", "The schedule is so tight that one delay could affect everything else.", "일정이 너무 빡빡해서 한 번 늦어지면 전부 영향을 받을 수 있어."),
        Seed(64, "완벽한 답보다 실행 가능한 답이 필요해", "🛠️", "시간과 자원이 제한된 문제를 해결할 때", "We need a workable solution, not a perfect one.", "완벽한 답보다 실제로 실행 가능한 해결책이 필요해.", "지금 할 수 있는 범위에서 작동하는 방법부터 만들자.", "We need something we can actually use, even if it isn't perfect.", "What makes a solution workable here?", "It has to fit our time, budget, and the people we actually have.", "우리 시간과 예산, 실제 인원으로 할 수 있어야 해."),
        Seed(65, "중간 점검 지점을 만들자", "✅", "장기 계획이 잘 가는지 중간에 확인할 때", "Let's build in a checkpoint to see if we're off track.", "방향이 틀어졌는지 볼 수 있게 중간 점검 지점을 만들자.", "끝까지 간 뒤에야 문제를 알지 않도록 중간 확인을 넣자.", "Let's schedule a checkpoint so we can catch problems early.", "When should we check our progress?", "After the first draft, we should review what's working and what isn't.", "첫 초안 뒤에 잘되는 것과 아닌 걸 확인하자."),
        Seed(66, "반대해도 아이디어 자체는 따로 보자", "💡", "사람에 대한 감정과 아이디어 평가를 분리할 때", "Even if someone disagrees, let's evaluate the idea itself.", "누군가 반대하더라도 아이디어 자체는 따로 평가해보자.", "누가 말했는지보다 그 생각이 실제로 괜찮은지 보자.", "Let's judge the idea on its merits, not on who suggested it.", "Why separate the person from the idea?", "A useful idea can still be useful even when we disagree with the person.", "그 사람과 의견이 달라도 좋은 아이디어는 좋은 아이디어일 수 있어."),
        Seed(67, "내가 놓친 게 있으면 바로 말해줘", "👀", "팀원에게 빠진 부분을 적극적으로 알려달라고 할 때", "Tell me right away if I'm missing something.", "내가 놓친 부분이 있으면 바로 말해줘.", "내가 다 보고 있다고 생각하지 말고 빠진 게 보이면 바로 알려줘.", "Please point it out if you notice something I've overlooked.", "Are you open to being corrected?", "Yes. I'd rather fix a mistake early than defend it for no reason.", "응. 괜히 방어하기보다 실수를 일찍 고치는 게 나아."),
        Seed(68, "결정 전에 영향을 받는 사람들 말을 듣자", "👥", "결정의 당사자 의견을 반영해야 할 때", "Let's hear from the people affected before we decide.", "결정하기 전에 영향을 받는 사람들의 의견을 듣자.", "우리끼리 정하기보다 실제로 영향을 받는 사람들에게 먼저 물어보자.", "Let's ask the people who will actually be affected before making the decision.", "What could we learn from them?", "They may see problems or needs that we can't see from here.", "우리 위치에서는 보이지 않는 문제나 필요를 알 수 있어."),
        Seed(69, "팀이 막혔다면 방법을 바꿀 때야", "🔄", "같은 방식으로 계속 진전이 없을 때", "If the team is stuck, it's time to change our approach.", "팀이 막혔다면 방법을 바꿀 때야.", "계속 같은 방법만 반복하지 말고 다른 방식으로 시도해보자.", "If we're not making progress, we should try a different approach.", "What would you change first?", "I'd simplify the plan and test one part before doing everything.", "계획을 단순하게 하고 전체 전에 한 부분부터 시험해보겠어."),
        Seed(70, "좋은 리더가 모든 답을 알 필요는 없어", "🧭", "리더십을 통제보다 조율로 볼 때", "A good leader doesn't need to have every answer.", "좋은 리더는 모든 답을 혼자 알고 있을 필요가 없어.", "리더는 다 아는 사람보다 좋은 질문을 하고 팀의 답을 모을 수 있는 사람이면 돼.", "A good leader can ask strong questions and use the team's knowledge.", "Then what does a leader need to do?", "They need to listen, make decisions, and help the team move forward.", "듣고 결정하고 팀이 앞으로 가게 도와야 해."),
        Seed(71, "출처가 누구인지부터 확인하자", "📰", "온라인 정보의 신뢰도를 판단할 때", "Let's check who the source is first.", "출처가 누구인지부터 확인하자.", "내용만 보기 전에 누가 왜 올린 정보인지 먼저 보자.", "Let's find out who published it before we trust the claim.", "What do you want to know about the source?", "I want to know who they are, what evidence they use, and whether they have a reason to mislead us.", "누구인지, 어떤 근거를 쓰는지, 왜곡할 이유가 있는지 보고 싶어."),
        Seed(72, "헤드라인만 보고 결론 내리면 안 돼", "🗞️", "자극적인 제목만 보고 내용을 판단하려 할 때", "We shouldn't draw conclusions from the headline alone.", "헤드라인만 보고 결론을 내려선 안 돼.", "제목은 관심을 끌려고 단순화될 수 있으니 본문까지 보자.", "A headline can oversimplify the story, so we should read the full article.", "Why can headlines be misleading?", "They often leave out context to get attention.", "관심을 끌려고 중요한 맥락을 빼는 경우가 있어."),
        Seed(73, "원래 맥락에서 무슨 말이었는지 보고 싶어", "🎬", "짧게 잘린 인용이나 영상을 확인할 때", "I want to see what was said in the original context.", "원래 맥락에서 무슨 말이었는지 보고 싶어.", "짧은 클립만 보지 말고 앞뒤 내용까지 확인하고 싶어.", "I want to see the full clip or original statement, not just a short excerpt.", "What could the missing context change?", "It could change the meaning or explain why the person said it.", "뜻이 달라지거나 왜 그런 말을 했는지 설명될 수 있어."),
        Seed(74, "이 정보가 언제 나온 건지도 중요해", "📅", "오래된 정보를 현재 사실처럼 사용할 때", "It matters when this information was published.", "이 정보가 언제 나온 건지도 중요해.", "지금도 맞는 정보인지 보려면 작성 날짜를 확인해야 해.", "The date matters because the information may no longer be current.", "Why would the date change your judgment?", "Rules, numbers, or circumstances may have changed since it was published.", "그 뒤로 규칙이나 수치, 상황이 달라졌을 수 있어."),
        Seed(75, "AI가 만든 내용일 가능성도 생각해야 해", "🤖", "온라인 글·이미지·음성의 생성 여부를 의심할 때", "We should consider the possibility that this was generated by AI.", "이게 AI로 생성됐을 가능성도 생각해야 해.", "자연스러워 보여도 실제 사람이 만든 것인지 확인할 필요가 있어.", "We shouldn't assume something is authentic just because it looks realistic.", "How would that change what you do next?", "I'd look for the original source and independent confirmation.", "원본 출처와 다른 독립적인 확인 자료를 찾겠어."),
        Seed(76, "그 이미지가 진짜인지 확인해보자", "🖼️", "조작되거나 맥락이 바뀐 이미지를 검증할 때", "Let's verify whether that image is authentic.", "그 이미지가 진짜인지 확인해보자.", "이미지가 실제인지, 다른 사건 사진을 가져온 건 아닌지 확인하자.", "Let's check whether the image is real and being used in the right context.", "What would you check first?", "I'd look for the earliest reliable source and other copies of the image.", "가장 이른 믿을 만한 출처와 같은 이미지의 다른 사용 사례를 보겠어."),
        Seed(77, "알고리즘이 내가 보는 걸 좁힐 수도 있어", "🧠", "추천 알고리즘이 정보 범위를 제한할 수 있을 때", "The algorithm might be narrowing what I see.", "알고리즘이 내가 보는 범위를 좁히고 있을 수도 있어.", "비슷한 내용만 계속 추천되면 다른 관점을 놓칠 수 있어.", "If I keep seeing similar content, the algorithm may be limiting my perspective.", "What could you do about that?", "I can deliberately look for reliable sources with different perspectives.", "다른 관점을 가진 믿을 만한 출처를 일부러 찾아볼 수 있어."),
        Seed(78, "내 피드가 세상 전체를 보여주는 건 아니야", "🌐", "개인화된 피드를 현실 전체로 착각하지 않으려 할 때", "My feed doesn't represent the whole world.", "내 피드가 세상 전체를 대표하는 건 아니야.", "내가 자주 보는 게시물이 모두의 생각이나 경험이라고 볼 수는 없어.", "What I see in my feed doesn't represent everyone's experience or opinion.", "Why is that easy to forget?", "Because repeated posts can make one view feel more common than it really is.", "비슷한 글을 반복해서 보면 실제보다 흔한 생각처럼 느껴질 수 있어."),
        Seed(79, "개인정보를 주기 전에 왜 필요한지 알고 싶어", "🔐", "서비스가 개인정보를 요구할 때", "I want to know why they need my data before I share it.", "개인정보를 주기 전에 왜 필요한지 알고 싶어.", "필수인지, 어디에 쓰는지 모르는 정보는 바로 주고 싶지 않아.", "I don't want to share personal information until I know how it will be used.", "What would you check?", "I'd check what data is required, how long it's kept, and who can access it.", "어떤 정보가 필수인지, 얼마나 보관하는지, 누가 접근하는지 확인하겠어."),
        Seed(80, "편리함과 개인정보 보호 사이에 균형이 필요해", "⚖️", "디지털 서비스 편의와 프라이버시를 함께 고려할 때", "We need a balance between convenience and privacy.", "편리함과 개인정보 보호 사이에 균형이 필요해.", "기능이 편해도 필요 이상으로 개인정보를 내줄 필요는 없어.", "Convenience matters, but we shouldn't give up more privacy than necessary.", "What balance would feel reasonable?", "I'd share only the data the feature truly needs and keep the rest private.", "기능에 정말 필요한 정보만 제공하고 나머지는 비공개로 두겠어."),
        Seed(81, "큰 목표를 이번 주 행동으로 바꿔보자", "🎯", "막연한 장기 목표를 바로 실행 가능한 계획으로 만들 때", "Let's turn the big goal into something I can do this week.", "큰 목표를 이번 주에 할 수 있는 행동으로 바꿔보자.", "먼 미래 계획보다 이번 주에 실제로 할 일을 하나 정하고 싶어.", "Let's turn the long-term goal into one concrete action for this week.", "What action would be small enough to start?", "I can spend thirty focused minutes on it three times this week.", "이번 주에 세 번, 30분씩 집중해서 해볼 수 있어."),
        Seed(82, "이 선택이 내 가치와 맞는지 보고 싶어", "🧭", "중요한 선택을 자신의 가치 기준으로 판단할 때", "I want to see whether this choice matches my values.", "이 선택이 내 가치와 맞는지 보고 싶어.", "남들이 좋아하는 선택보다 내가 중요하게 생각하는 것과 맞는지 보고 싶어.", "I want to judge the choice by what matters to me, not only by what looks successful.", "Which value matters most here?", "Having enough time for people and work I care about matters a lot to me.", "내가 소중하게 생각하는 사람과 일에 쓸 시간이 있는 게 중요해."),
        Seed(83, "잘하는 것과 좋아하는 게 꼭 같진 않아", "🎨", "진로에서 능력과 흥미를 구분해 생각할 때", "What I'm good at isn't always the same as what I enjoy.", "내가 잘하는 것과 좋아하는 게 항상 같은 건 아니야.", "잘하는 분야라고 해서 오래 하고 싶은 분야라는 뜻은 아니야.", "Being good at something doesn't automatically mean I want to build my future around it.", "How could that affect your choice?", "I want to consider both ability and genuine interest before I decide.", "결정하기 전에 능력과 진짜 흥미를 둘 다 보고 싶어."),
        Seed(84, "이 경험에서 실제로 뭘 배웠는지 생각해볼래", "🌱", "활동 후 배운 점을 구체적으로 돌아볼 때", "I want to think about what I actually learned from this experience.", "이 경험에서 내가 실제로 뭘 배웠는지 생각해보고 싶어.", "결과만 보지 말고 내가 어떤 점에서 달라졌는지 돌아보고 싶어.", "I want to reflect on how this experience changed what I know or how I work.", "What did you learn about yourself?", "I learned that I do better when I ask for feedback earlier.", "피드백을 일찍 받을수록 더 잘한다는 걸 배웠어."),
        Seed(85, "지금 선택이 평생 결정일 필요는 없어", "🛤️", "진로 선택을 지나치게 최종 결정처럼 느낄 때", "This choice doesn't have to decide my whole future.", "이 선택이 내 평생의 미래를 결정할 필요는 없어.", "지금 선택하고 나중에 더 알게 되면 방향을 바꿀 수도 있어.", "I can make a choice now and still change direction as I learn more.", "Does that make the decision easier?", "Yes. It lets me choose thoughtfully without pretending I know everything already.", "응. 모든 걸 안다고 생각하지 않아도 신중하게 선택할 수 있어."),
        Seed(86, "비교보다 내 기준으로 진전을 보고 싶어", "📈", "다른 사람과 비교하느라 자신감을 잃을 때", "I want to measure progress by my own standards, not by comparison.", "비교보다 내 기준으로 진전을 보고 싶어.", "다른 사람 속도보다 내가 전보다 나아졌는지에 집중하고 싶어.", "I want to focus on whether I'm improving, not on whether I'm ahead of someone else.", "What standard would you use?", "I'd compare my work with where I was a month ago and with the goals I set.", "한 달 전의 나와 내가 세운 목표를 기준으로 보겠어."),
        Seed(87, "쉬는 것도 계획의 일부로 넣어야 해", "🌿", "과도한 일정으로 지치기 전에 회복 시간을 확보할 때", "I need to make rest part of the plan.", "쉬는 것도 계획의 일부로 넣어야 해.", "쉬는 시간을 남은 시간 취급하지 말고 미리 일정에 넣고 싶어.", "I need to schedule rest instead of treating it as whatever time is left over.", "Why plan rest in advance?", "Because I make worse decisions and work less effectively when I'm exhausted.", "지치면 판단도 나빠지고 효율도 떨어지기 때문이야."),
        Seed(88, "집중할 시간을 따로 지키고 싶어", "⏱️", "알림과 방해 없이 중요한 일에 집중할 때", "I want to protect time for focused work.", "집중해서 일할 시간을 따로 지키고 싶어.", "중요한 일을 할 때는 알림과 다른 일을 잠깐 끊어두고 싶어.", "I want to block out time when I can work without notifications or interruptions.", "How will you protect that time?", "I'll silence notifications and tell people when I'll be available again.", "알림을 끄고 언제 다시 연락 가능한지 알려둘 거야."),
        Seed(89, "유지 못 할 목표라면 규모를 줄이는 게 나아", "📉", "목표가 너무 커서 계속 실패할 때", "If I can't sustain the goal, it's better to scale it down.", "목표를 유지할 수 없다면 규모를 줄이는 게 나아.", "크게 잡고 포기하기보다 작게 줄여서 계속하고 싶어.", "I'd rather make the goal smaller and keep going than make it huge and quit.", "What would a smaller version look like?", "Instead of an hour every day, I could start with twenty minutes four days a week.", "매일 한 시간 대신 주 4일 20분부터 시작할 수 있어."),
        Seed(90, "완벽한 시작보다 꾸준함이 더 중요해", "🔁", "새 습관을 완벽하게 하려다 포기하기 쉬울 때", "Consistency matters more than starting perfectly.", "완벽하게 시작하는 것보다 꾸준히 이어가는 게 더 중요해.", "처음부터 다 잘하려고 하기보다 계속 돌아오는 습관을 만들고 싶어.", "I'd rather keep showing up imperfectly than quit because I missed one day.", "How do you stay consistent after a bad day?", "I restart the next day instead of treating one miss as a failure.", "하루 놓쳤다고 실패로 보지 않고 다음 날 다시 시작해."),
        Seed(91, "같은 상황도 사람마다 다르게 경험할 수 있어", "👥", "자신의 경험을 모두의 경험으로 일반화하지 않으려 할 때", "People can experience the same situation very differently.", "사람들은 같은 상황도 아주 다르게 경험할 수 있어.", "나한테 괜찮았다고 해서 다른 사람도 똑같이 느꼈다고 생각하면 안 돼.", "My experience isn't automatically the same as everyone else's.", "Why might their experience be different?", "They may have different needs, backgrounds, or things at stake.", "필요나 배경, 걸려 있는 것이 다를 수 있어."),
        Seed(92, "의도와 영향은 둘 다 중요해", "⚖️", "좋은 의도였지만 상대에게 상처를 준 상황을 볼 때", "Both intention and impact matter.", "의도와 실제 영향은 둘 다 중요해.", "나쁜 뜻이 없었다는 것과 상대가 상처받았다는 사실을 함께 봐야 해.", "We should consider what someone meant and what effect their actions actually had.", "What if the intention was good?", "A good intention matters, but it doesn't erase the impact on someone else.", "좋은 의도는 중요하지만 다른 사람에게 준 영향을 없애진 않아."),
        Seed(93, "누군가 불편하다고 하면 먼저 들어야 해", "👂", "상대가 경계나 불편함을 표현했을 때", "If someone says they're uncomfortable, we should listen first.", "누군가 불편하다고 말하면 먼저 들어야 해.", "바로 변명하기보다 왜 불편했는지 먼저 듣는 게 좋겠어.", "Instead of defending ourselves immediately, we should first understand what felt wrong to them.", "What should happen after listening?", "Then we can ask what would help and decide what needs to change.", "그다음 무엇이 도움이 될지 묻고 바꿀 점을 정할 수 있어."),
        Seed(94, "다수 의견이라고 자동으로 공정한 건 아니야", "🗳️", "다수결 결과와 공정성을 구분해야 할 때", "A majority opinion isn't automatically fair.", "다수 의견이라고 해서 자동으로 공정한 건 아니야.", "많은 사람이 원해도 소수에게 너무 큰 불이익을 주는지 봐야 해.", "Even if most people agree, we should consider whether the decision unfairly harms a smaller group.", "Then what should we look at besides the vote?", "We should look at rights, impact, and whether everyone had a meaningful voice.", "권리와 영향, 모두가 제대로 의견을 낼 수 있었는지도 봐야 해."),
        Seed(95, "규칙의 목적이 뭔지도 같이 봐야 해", "📜", "규칙을 문자 그대로만 적용하기 어려울 때", "We should also consider what the rule is meant to achieve.", "그 규칙이 무엇을 위해 만들어졌는지도 같이 봐야 해.", "규칙의 글자만 볼 게 아니라 왜 필요한 규칙인지 생각해보자.", "We should look at the purpose of the rule, not only the exact wording.", "Why does the purpose matter?", "It helps us apply the rule consistently when the situation isn't obvious.", "애매한 상황에서도 규칙을 일관되게 적용하는 데 도움이 돼."),
        Seed(96, "내가 가진 이점이 모두에게 있는 건 아닐 수 있어", "🌍", "자신에게 쉬운 일이 다른 사람에게도 쉽다고 가정할 때", "The advantages I have may not be available to everyone.", "내가 가진 이점이 모두에게 있는 건 아닐 수 있어.", "내가 쉽게 접근할 수 있는 시간이나 도움, 기회가 다른 사람에게는 없을 수도 있어.", "The time, support, or opportunities I have may not be equally available to other people.", "How should that affect your judgment?", "I should be careful before assuming someone had the same options I did.", "다른 사람도 나와 같은 선택지가 있었다고 단정하지 않아야 해."),
        Seed(97, "좋은 토론은 사람이 아니라 생각을 비판해야 해", "💬", "의견 차이가 인신공격으로 번질 때", "A good discussion criticizes ideas, not people.", "좋은 토론은 사람이 아니라 생각을 비판해야 해.", "상대가 틀렸다고 공격하기보다 그 주장 중 어떤 부분에 동의하지 않는지 말하자.", "We should challenge the argument without attacking the person making it.", "What would that sound like?", "I can say, 'I disagree with that reason,' instead of calling the person ignorant.", "사람을 무시하기보다 '그 이유에는 동의하지 않아'라고 말할 수 있어."),
        Seed(98, "생각을 바꾸는 건 배우는 과정일 수 있어", "🌱", "새로운 근거 때문에 기존 의견을 바꿀 때", "Changing my mind can be part of learning, not a weakness.", "생각을 바꾸는 건 약한 게 아니라 배우는 과정일 수 있어.", "더 좋은 근거를 보고 의견을 바꾸는 걸 부끄럽게 생각하고 싶지 않아.", "I don't want to treat changing my view after better evidence as a failure.", "What makes changing your mind reasonable?", "It makes sense when the evidence or my understanding genuinely changes.", "근거나 이해가 실제로 달라졌다면 생각을 바꾸는 게 자연스러워."),
        Seed(99, "확신 없을 땐 모른다고 말할 수 있어야 해", "🤔", "충분한 정보가 없는데 아는 척하고 싶지 않을 때", "I should be able to say I don't know when I'm not sure.", "확신이 없을 때는 모른다고 말할 수 있어야 해.", "모르는 걸 숨기기보다 어디까지 아는지 솔직하게 말하고 싶어.", "I want to be honest about what I know and what I still don't know.", "Does saying 'I don't know' end the conversation?", "No. It can be the start of asking a better question or checking the facts.", "아니. 더 좋은 질문을 하거나 사실을 확인하는 시작이 될 수 있어."),
        Seed(100, "내 목소리를 내면서 다른 사람의 공간도 남기고 싶어", "🎤", "자기표현과 경청을 함께 지키고 싶을 때", "I want to use my voice while leaving room for others.", "내 목소리를 내면서도 다른 사람의 공간을 남기고 싶어.", "내 생각을 분명히 말하되 대화를 혼자 차지하고 싶지는 않아.", "I want to express my view clearly without taking over the whole conversation.", "What does that balance look like?", "I can speak up, ask questions, and make sure quieter people have a chance to respond.", "내 의견을 말하고 질문하면서 조용한 사람도 답할 기회를 갖게 할 수 있어.")
    )

    val lessons: List<Lesson> = seeds.map { seed ->
        Lesson(
            id = 400 + seed.number,
            title = seed.title,
            emoji = seed.emoji,
            situation = seed.situation,
            target = seed.target,
            meaning = seed.meaning,
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = seed.ownPromptKo,
            accepted = listOf(seed.acceptedVariant, seed.target),
            coachLine = seed.coachLine,
            course = CourseLevel.AGE_14_16,
            courseLessonNumber = seed.number
        )
    }

    internal fun supportLine(lessonId: Int): Pair<String, String>? =
        seeds.firstOrNull { 400 + it.number == lessonId }?.let { it.supportEnglish to it.supportKorean }
}
