package com.yamone.english

object Age1113PronunciationQaExpansionCatalog {
    val guides = listOf(
        PronunciationQaGuide(351, "There's a ●WEAK-ness in that ●AR-gu-ment ↘", "데어즈 / 어 / 위크니스 / 인 / 댓 / 아규먼트", "데어저 ●위크니스 인 댓 ●아규먼트↘", "약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(352, "That could be ●EV-i-dence a●GAINST‿it ↘", "댓 / 쿠드 / 비 / 에버던스 / 어겐스트 / 잇", "댓 쿠드 비 ●에버던스 어●겐스팃↘", "약-약-약-강-강-약 ↘"),
        PronunciationQaGuide(353, "I a●GREE with PART of what you're ●SAY-ing ↘", "아이 / 어그리 / 위드 / 파트 / 어브 / 왓 / 유어 / 세잉", "아이 어●그리 윗 ●파트 어브 왓츄어 ●세잉↘", "약-강-약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(354, "But I REACH a different con●CLU-sion ↘", "벗 / 아이 / 리치 / 어 / 디프런트 / 컨클루전", "벗 아이 ●리처 디프런트 컨●클루전↘", "약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(355, "We NEED to CHECK whether that as●SUMP-tion is TRUE ↘", "위 / 니드 / 투 / 체크 / 웨더 / 댓 / 어썸션 / 이즈 / 트루", "위 ●니드 터 ●체크 웨더 댓 어●썸션 이즈 ●트루↘", "약-강-약-강-약-약-강-약-강 ↘"),
        PronunciationQaGuide(356, "That's a GOOD counter●AR-gu-ment ↘", "댓츠 / 어 / 굿 / 카운터아규먼트", "댓처 ●굿 카운터●아규먼트↘", "약-약-강-강 ↘"),
        PronunciationQaGuide(357, "I might CHANGE my MIND if there's new ●EV-i-dence ↘", "아이 / 마잇 / 체인지 / 마이 / 마인드 / 이프 / 데어즈 / 뉴 / 에버던스", "아이 마잇 ●체인지 마이 ●마인드 이프 데어즈 뉴 ●에버던스↘", "약-약-강-약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(358, "Let's WEIGH the PROS and CONS before de●CID-ing ↘", "렛츠 / 웨이 / 더 / 프로즈 / 앤드 / 칸즈 / 비포어 / 디사이딩", "렛츠 ●웨이 더 ●프로즈 앤 ●칸즈 비포어 디●사이딩↘", "약-강-약-강-약-강-약-강 ↘"),
        PronunciationQaGuide(359, "NEI-ther option is ●PER-fect ↘", "니더 / 압션 / 이즈 / 퍼펙트", "●니더 압션 이즈 ●퍼펙트↘", "강-약-약-강 ↘"),
        PronunciationQaGuide(360, "This CHOICE could affect us ●LA-ter ↘", "디스 / 초이스 / 쿠드 / 어펙트 / 어스 / 레이터", "디스 ●초이스 쿠드 어펙터스 ●레이럴↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(361, "We NEED to THINK about the ●CON-se-quen-ces ↘", "위 / 니드 / 투 / 띵크 / 어바웃 / 더 / 칸서퀀시즈", "위 ●니드 터 ●띵커바웃 더 ●칸서퀀시즈↘", "약-강-약-강-약-약-강 ↘"),
        PronunciationQaGuide(362, "We NEED a BACK-up plan in case it doesn't ●WORK ↘", "위 / 니드 / 어 / 백업 / 플랜 / 인 / 케이스 / 잇 / 더즌트 / 워크", "위 ●니더 ●백업 플랜 인 케이스 잇 더즌 ●워크↘", "약-강-약-강-약-약-약-약-약-강 ↘"),
        PronunciationQaGuide(363, "Is it WORTH the ●RISK ↗", "이즈 / 잇 / 워쓰 / 더 / 리스크", "이짓 ●워쓰 더 ●리스크↗", "약-약-강-약-강 ↗"),
        PronunciationQaGuide(364, "The EAS-i-est choice isn't always the BEST one ↘", "더 / 이지어스트 / 초이스 / 이즌트 / 올웨이즈 / 더 / 베스트 / 원", "디 ●이지어스트 초이스 이즌 올웨이즈 더 ●베스트 원↘", "약-강-약-약-약-약-강-약 ↘"),
        PronunciationQaGuide(365, "It might HELP in the SHORT TERM ↘", "잇 / 마잇 / 헬프 / 인 / 더 / 쇼트 / 텀", "잇 마잇 ●헬프 인 더 ●쇼트 텀↘", "약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(366, "It could be BET-ter in the LONG RUN ↘", "잇 / 쿠드 / 비 / 베러 / 인 / 더 / 롱 / 런", "잇 쿠드 비 ●베러 인 더 ●롱 런↘", "약-약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(367, "Let's THINK about WHO might be af●FECT-ed ↘", "렛츠 / 띵크 / 어바웃 / 후 / 마잇 / 비 / 어펙티드", "렛츠 ●띵커바웃 ●후 마잇 비 어●펙티드↘", "약-강-약-강-약-약-강 ↘"),
        PronunciationQaGuide(368, "We should ALSO ask whether it's FAIR ↘", "위 / 슈드 / 올소우 / 애스크 / 웨더 / 잇츠 / 페어", "위 슈드 ●올소우 애스크 웨더 잇츠 ●페어↘", "약-약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(369, "It's o●KAY to change a de●CI-sion when new information comes IN ↘", "잇츠 / 오케이 / 투 / 체인지 / 어 / 디시전 / 웬 / 뉴 / 인퍼메이션 / 컴즈 / 인", "잇츠 오●케이 터 체인지 어 디●시전 웬 뉴 인퍼메이션 컴즈 ●인↘", "약-강-약-약-약-강-약-약-약-약-강 ↘"),
        PronunciationQaGuide(370, "We HAVE to take re-spon-si●BIL-i-ty for the CHOICE ↘", "위 / 해브 / 투 / 테이크 / 리스판서빌러티 / 포 / 더 / 초이스", "위 ●해프 터 테이크 리스판서●빌러리 퍼 더 ●초이스↘", "약-강-약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(371, "TEXT messages can be EASY to misunder●STAND ↘", "텍스트 / 메서지즈 / 캔 / 비 / 이지 / 투 / 미선더스탠드", "●텍스트 메서지즈 컨 비 ●이지 터 미선더●스탠드↘", "강-약-약-약-강-약-강 ↘"),
        PronunciationQaGuide(372, "That MES-sage could come a●CROSS differently ↘", "댓 / 메서지 / 쿠드 / 컴 / 어크로스 / 디프런틀리", "댓 ●메서지 쿠드 컴 어●크로스 디프런틀리↘", "약-강-약-약-강-약 ↘"),
        PronunciationQaGuide(373, "THINK before you POST something on●LINE ↘", "띵크 / 비포어 / 유 / 포스트 / 썸띵 / 온라인", "●띵크 비포어 유 ●포스트 썸띵 온●라인↘", "강-약-약-강-약-강 ↘"),
        PronunciationQaGuide(374, "You SHOULDN'T share personal infor●MA-tion CARE-less-ly ↘", "유 / 슈든트 / 쉐어 / 퍼서널 / 인퍼메이션 / 케얼러스리", "유 ●슈든 쉐어 퍼서널 인퍼●메이션 ●케얼러스리↘", "약-강-약-약-강-강 ↘"),
        PronunciationQaGuide(375, "ASK before POST-ing someone else's ●PHO-to ↘", "애스크 / 비포어 / 포스팅 / 썸원 / 엘시즈 / 포우토우", "●애스크 비포어 ●포스팅 썸원 엘시즈 ●포우토우↘", "강-약-강-약-약-강 ↘"),
        PronunciationQaGuide(376, "Let's NOT argue over ●TEXT ↘", "렛츠 / 낫 / 아규 / 오버 / 텍스트", "렛츠 ●낫 아규 오버 ●텍스트↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(377, "I THINK it'd be BET-ter to talk in ●PER-son ↘", "아이 / 띵크 / 잇드 / 비 / 베러 / 투 / 톡 / 인 / 퍼슨", "아이 ●띵크 잇드 비 ●베러 터 톡 인 ●퍼슨↘", "약-강-약-약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(378, "Let's CHECK whether that POST is REAL ↘", "렛츠 / 체크 / 웨더 / 댓 / 포스트 / 이즈 / 리얼", "렛츠 ●체크 웨더 댓 ●포스트 이즈 ●리얼↘", "약-강-약-약-강-약-강 ↘"),
        PronunciationQaGuide(379, "I'm NOT going to re●SPOND right a●WAY ↘", "아임 / 낫 / 고잉 / 투 / 리스판드 / 라잇 / 어웨이", "아임 ●낫 거너 리●스판드 라잇 어●웨이↘", "약-강-약-약-강-약-강 ↘"),
        PronunciationQaGuide(380, "We should be re●SPECT-ful on●LINE too ↘", "위 / 슈드 / 비 / 리스펙트풀 / 온라인 / 투", "위 슈드 비 리●스펙트풀 온●라인 투↘", "약-약-약-강-강-약 ↘"),
        PronunciationQaGuide(381, "I WANT to handle this on my OWN ↘", "아이 / 원트 / 투 / 핸들 / 디스 / 온 / 마이 / 오운", "아이 ●워너 핸들 디스 온 마이 ●오운↘", "약-강-약-약-약-약-약-강 ↘"),
        PronunciationQaGuide(382, "I'll ASK for HELP if I NEED it ↘", "아일 / 애스크 / 포 / 헬프 / 이프 / 아이 / 니드 / 잇", "아일 ●애스크 퍼 ●헬프 이파이 ●니딧↘", "약-강-약-강-약-약-강-약 ↘"),
        PronunciationQaGuide(383, "I NEED to manage my OWN SCHED-ule ↘", "아이 / 니드 / 투 / 매니지 / 마이 / 오운 / 스케줄", "아이 ●니드 터 매니지 마이 ●오운 ●스케줄↘", "약-강-약-약-약-강-강 ↘"),
        PronunciationQaGuide(384, "I'll take re-spon-si●BIL-i-ty for FIX-ing my mis●TAKE ↘", "아일 / 테이크 / 리스판서빌러티 / 포 / 픽싱 / 마이 / 미스테이크", "아일 테이크 리스판서●빌러리 퍼 ●픽싱 마이 미스●테이크↘", "약-약-강-약-강-약-강 ↘"),
        PronunciationQaGuide(385, "I don't WANT to make ex●CUS-es ↘", "아이 / 돈트 / 원트 / 투 / 메이크 / 익스큐시즈", "아이 돈 ●원트 터 메이크 익스●큐시즈↘", "약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(386, "I WAS-n't pre●PARED e●NOUGH ↘", "아이 / 워즌트 / 프리페어드 / 이너프", "아이 ●워즌 프리●페어드 이●너프↘", "약-강-강-강 ↘"),
        PronunciationQaGuide(387, "I'll pre●PARE EAR-li-er NEXT time ↘", "아일 / 프리페어 / 얼리어 / 넥스트 / 타임", "아일 프리●페어 ●얼리어 ●넥스트 타임↘", "약-강-강-강-약 ↘"),
        PronunciationQaGuide(388, "It was my CHOICE | so I'll take re-spon-si●BIL-i-ty ↘", "잇 / 워즈 / 마이 / 초이스 / 쏘 / 아일 / 테이크 / 리스판서빌러티", "잇 워즈 마이 ●초이스 | 쏘 아일 테이크 리스판서●빌러리↘", "약-약-약-강 | 약-약-약-강 ↘"),
        PronunciationQaGuide(389, "I'll TRY to work it OUT on my OWN ↘", "아일 / 트라이 / 투 / 워크 / 잇 / 아웃 / 온 / 마이 / 오운", "아일 ●트라이 터 워키다웃 온 마이 ●오운↘", "약-강-약-약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(390, "Knowing WHEN to ask for HELP is important TOO ↘", "노잉 / 웬 / 투 / 애스크 / 포 / 헬프 / 이즈 / 임포턴트 / 투", "노잉 ●웬 터 애스크 퍼 ●헬프 이즈 임포턴트 ●투↘", "약-강-약-약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(391, "I've been getting MORE ●IN-ter-est-ed in THIS lately ↘", "아이브 / 빈 / 게팅 / 모어 / 인터레스티드 / 인 / 디스 / 레잇리", "아이브 빈 게링 ●모어 ●인트러스티드 인 ●디스 레잇리↘", "약-약-약-강-강-약-강-약 ↘"),
        PronunciationQaGuide(392, "I WANT to under●STAND why that HAP-pens ↘", "아이 / 원트 / 투 / 언더스탠드 / 와이 / 댓 / 해픈즈", "아이 ●워너 언더●스탠드 와이 댓 ●해픈즈↘", "약-강-약-강-약-약-강 ↘"),
        PronunciationQaGuide(393, "I THINK this is something I'm GOOD at ↘", "아이 / 띵크 / 디스 / 이즈 / 썸띵 / 아임 / 굿 / 앳", "아이 ●띵크 디스 이즈 썸띵 아임 ●구댓↘", "약-강-약-약-약-약-강 ↘"),
        PronunciationQaGuide(394, "This PART still feels ●CHAL-leng-ing ↘", "디스 / 파트 / 스틸 / 필즈 / 챌린징", "디스 ●파트 스틸 필즈 ●챌린징↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(395, "I'd LIKE to learn MORE about it ↘", "아이드 / 라익 / 투 / 런 / 모어 / 어바웃 / 잇", "아이드 ●라익 터 런 ●모러바우릿↘", "약-강-약-약-강-약 ↘"),
        PronunciationQaGuide(396, "I'd LIKE to TRY this in real LIFE ↘", "아이드 / 라익 / 투 / 트라이 / 디스 / 인 / 리얼 / 라이프", "아이드 ●라익 터 ●트라이 디스 인 리얼 ●라이프↘", "약-강-약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(397, "I'm STILL figuring out what I'm ●IN-ter-est-ed in ↘", "아임 / 스틸 / 피겨링 / 아웃 / 왓 / 아임 / 인터레스티드 / 인", "아임 ●스틸 피겨링아웃 왓 아임 ●인트러스티드 인↘", "약-강-약-약-약-약-강-약 ↘"),
        PronunciationQaGuide(398, "I don't HAVE to de●CIDE everything right NOW ↘", "아이 / 돈트 / 해브 / 투 / 디사이드 / 에브리띵 / 라잇 / 나우", "아이 돈 ●해프 터 디●사이드 에브리띵 라잇 ●나우↘", "약-약-강-약-강-약-약-강 ↘"),
        PronunciationQaGuide(399, "I WANT to ex●PLORE different THINGS ↘", "아이 / 원트 / 투 / 익스플로어 / 디프런트 / 띵즈", "아이 ●워너 익스●플로어 디프런트 ●띵즈↘", "약-강-약-강-약-강 ↘"),
        PronunciationQaGuide(400, "I WANT to ex●PRESS myself more ●CON-fi-dent-ly ↘", "아이 / 원트 / 투 / 익스프레스 / 마이셀프 / 모어 / 칸피던틀리", "아이 ●워너 익스●프레스 마이셀프 모어 ●칸피던틀리↘", "약-강-약-강-약-약-강 ↘")
    )
}
