package com.yamone.english

object Age810LessonCatalog {
    private val baseLessons = listOf(
        Lesson(
            id = 201,
            title = "숙제를 깜빡했어",
            emoji = "📚",
            situation = "숙제를 가져오지 않았을 때",
            target = "I forgot my homework.",
            meaning = "숙제를 깜빡했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "숙제 가져오는 걸 깜빡했어.",
            accepted = listOf("I forgot to bring my homework.", "I forgot my homework."),
            coachLine = "Did you bring your homework?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 1
        ),
        Lesson(
            id = 202,
            title = "벌써 끝냈어",
            emoji = "✅",
            situation = "해야 할 일을 이미 끝냈을 때",
            target = "I finished it already.",
            meaning = "나 그거 벌써 끝냈어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "숙제 벌써 끝냈어.",
            accepted = listOf("I already finished my homework.", "I finished it already."),
            coachLine = "Are you done yet?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 2
        ),
        Lesson(
            id = 203,
            title = "다시 설명해 줄래?",
            emoji = "🙋",
            situation = "수업 내용을 다시 듣고 싶을 때",
            target = "Could you explain that again?",
            meaning = "그거 다시 설명해 줄래?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "조금 더 쉽게 다시 설명해 줄래?",
            accepted = listOf("Could you explain it one more time?", "Could you explain that again?"),
            coachLine = "Which part is confusing?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 3
        ),
        Lesson(
            id = 204,
            title = "이제 알 것 같아",
            emoji = "💡",
            situation = "설명을 듣고 이해했을 때",
            target = "I think I understand.",
            meaning = "이제 알 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "응, 이제 이해한 것 같아.",
            accepted = listOf("I think I get it now.", "I think I understand."),
            coachLine = "Does it make sense now?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 4
        ),
        Lesson(
            id = 205,
            title = "시간이 더 필요해",
            emoji = "⏱️",
            situation = "과제를 끝내는 데 시간이 필요할 때",
            target = "I need more time.",
            meaning = "시간이 더 필요해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이거 끝내려면 시간이 조금 더 필요해.",
            accepted = listOf("I need a little more time.", "I need more time."),
            coachLine = "How much more time do you need?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 5
        ),
        Lesson(
            id = 206,
            title = "이 단어 무슨 뜻이야?",
            emoji = "🔤",
            situation = "모르는 단어의 뜻을 물을 때",
            target = "What does this word mean?",
            meaning = "이 단어 무슨 뜻이야?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이 단어 뜻이 뭐야?",
            accepted = listOf("What does this mean?", "What does this word mean?"),
            coachLine = "Which word?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 6
        ),
        Lesson(
            id = 207,
            title = "철자가 어떻게 돼?",
            emoji = "✍️",
            situation = "단어 철자를 물을 때",
            target = "How do you spell it?",
            meaning = "그거 철자가 어떻게 돼?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "네 이름 철자가 어떻게 돼?",
            accepted = listOf("How do you spell your name?", "How do you spell it?"),
            coachLine = "I'll spell it for you.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 7
        ),
        Lesson(
            id = 208,
            title = "같이 해도 돼?",
            emoji = "🤝",
            situation = "친구와 과제를 함께하고 싶을 때",
            target = "Can I work with you?",
            meaning = "너랑 같이 해도 돼?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이거 같이 해도 돼?",
            accepted = listOf("Can we work on this together?", "Can I work with you?"),
            coachLine = "Sure. Let's do it together.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 8
        ),
        Lesson(
            id = 209,
            title = "같이 해결해 보자",
            emoji = "🧩",
            situation = "문제를 함께 풀 때",
            target = "Let's figure it out.",
            meaning = "같이 알아내 보자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "우리 같이 해결해 보자.",
            accepted = listOf("Let's figure this out together.", "Let's figure it out."),
            coachLine = "Okay. Let's think.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 9
        ),
        Lesson(
            id = 210,
            title = "내가 실수했어",
            emoji = "📝",
            situation = "자신의 실수를 인정할 때",
            target = "I made a mistake.",
            meaning = "내가 실수했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "여기서 실수한 것 같아.",
            accepted = listOf("I think I made a mistake here.", "I made a mistake."),
            coachLine = "It's okay. You can fix it.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 10
        ),
        Lesson(
            id = 211,
            title = "어제 공원에 갔어",
            emoji = "🌳",
            situation = "어제 한 일을 말할 때",
            target = "I went to the park yesterday.",
            meaning = "어제 공원에 갔어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "어제 친구랑 공원에 갔어.",
            accepted = listOf("I went to the park with my friend yesterday.", "I went to the park yesterday."),
            coachLine = "What did you do there?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 11
        ),
        Lesson(
            id = 212,
            title = "두 시간 동안 놀았어",
            emoji = "⏰",
            situation = "얼마나 오래 했는지 말할 때",
            target = "We played for two hours.",
            meaning = "우리 두 시간 동안 놀았어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "우리는 밖에서 두 시간 동안 놀았어.",
            accepted = listOf("We played outside for two hours.", "We played for two hours."),
            coachLine = "Was it fun?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 12
        ),
        Lesson(
            id = 213,
            title = "재미있는 걸 봤어",
            emoji = "👀",
            situation = "흥미로운 경험을 말할 때",
            target = "I saw something interesting.",
            meaning = "재미있는 걸 봤어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "오늘 정말 재미있는 걸 봤어.",
            accepted = listOf("I saw something really interesting today.", "I saw something interesting."),
            coachLine = "What did you see?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 13
        ),
        Lesson(
            id = 214,
            title = "그다음엔 무슨 일이 있었어?",
            emoji = "➡️",
            situation = "이야기의 다음 내용을 물을 때",
            target = "What happened after that?",
            meaning = "그다음엔 무슨 일이 있었어?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그래서 그다음엔 어떻게 됐어?",
            accepted = listOf("So what happened next?", "What happened after that?"),
            coachLine = "Then something funny happened.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 14
        ),
        Lesson(
            id = 215,
            title = "그러고 집에 갔어",
            emoji = "🏠",
            situation = "일어난 일을 순서대로 말할 때",
            target = "Then we went home.",
            meaning = "그러고 나서 우리는 집에 갔어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그다음에 바로 집에 갔어.",
            accepted = listOf("Then we went straight home.", "Then we went home."),
            coachLine = "What did you do at home?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 15
        ),
        Lesson(
            id = 216,
            title = "전에 해본 적 없어",
            emoji = "🆕",
            situation = "처음 해보는 경험을 말할 때",
            target = "I've never tried that before.",
            meaning = "그거 전에 해본 적 없어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "난 이런 거 한 번도 해본 적 없어.",
            accepted = listOf("I've never done anything like that before.", "I've never tried that before."),
            coachLine = "Do you want to try it?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 16
        ),
        Lesson(
            id = 217,
            title = "혼자 했어",
            emoji = "💪",
            situation = "도움 없이 해냈다고 말할 때",
            target = "I did it by myself.",
            meaning = "나 혼자 했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "도움 없이 혼자 했어.",
            accepted = listOf("I did it without any help.", "I did it by myself."),
            coachLine = "Nice job!",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 17
        ),
        Lesson(
            id = 218,
            title = "생각보다 쉬웠어",
            emoji = "🙂",
            situation = "예상과 실제를 비교할 때",
            target = "It was easier than I thought.",
            meaning = "생각보다 쉬웠어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "시험이 생각보다 쉬웠어.",
            accepted = listOf("The test was easier than I thought.", "It was easier than I thought."),
            coachLine = "Were you worried about it?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 18
        ),
        Lesson(
            id = 219,
            title = "이게 더 좋아",
            emoji = "⭐",
            situation = "두 가지를 비교할 때",
            target = "This one is better.",
            meaning = "이게 더 좋아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내 생각엔 이게 더 좋아.",
            accepted = listOf("I think this one is better.", "This one is better."),
            coachLine = "Why do you think so?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 19
        ),
        Lesson(
            id = 220,
            title = "어느 게 더 좋아?",
            emoji = "⚖️",
            situation = "상대의 선호를 물을 때",
            target = "Which one do you prefer?",
            meaning = "어느 게 더 좋아?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "둘 중 어느 게 더 좋아?",
            accepted = listOf("Which one do you like better?", "Which one do you prefer?"),
            coachLine = "I prefer this one.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 20
        ),
        Lesson(
            id = 221,
            title = "이게 좋은 이유는...",
            emoji = "💬",
            situation = "좋아하는 이유를 설명할 때",
            target = "I like this one because it's easier.",
            meaning = "이게 더 쉬워서 좋아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "난 이게 더 재미있어서 좋아.",
            accepted = listOf("I like this one because it's more fun.", "I like this one because it's easier."),
            coachLine = "Why do you like it?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 21
        ),
        Lesson(
            id = 222,
            title = "난 동의하지 않아",
            emoji = "🙅",
            situation = "다른 의견을 말할 때",
            target = "I don't agree.",
            meaning = "난 동의하지 않아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "나는 그 생각에는 동의하지 않아.",
            accepted = listOf("I don't agree with that.", "I don't agree."),
            coachLine = "Why not?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 22
        ),
        Lesson(
            id = 223,
            title = "무슨 말인지 알겠어",
            emoji = "🤔",
            situation = "상대의 관점을 이해했을 때",
            target = "I see what you mean.",
            meaning = "무슨 말인지 알겠어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "네가 왜 그렇게 말하는지 알겠어.",
            accepted = listOf("I understand what you mean.", "I see what you mean."),
            coachLine = "Thanks for listening.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 23
        ),
        Lesson(
            id = 224,
            title = "네 말이 맞을지도 몰라",
            emoji = "🙂",
            situation = "상대 의견을 받아들일 때",
            target = "Maybe you're right.",
            meaning = "네 말이 맞을지도 몰라.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "생각해 보니 네 말이 맞을지도 몰라.",
            accepted = listOf("Maybe you're right about that.", "Maybe you're right."),
            coachLine = "Let's check.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 24
        ),
        Lesson(
            id = 225,
            title = "경우에 따라 달라",
            emoji = "🔀",
            situation = "상황에 따라 답이 다를 때",
            target = "It depends.",
            meaning = "경우에 따라 달라.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그건 상황에 따라 달라.",
            accepted = listOf("It depends on the situation.", "It depends."),
            coachLine = "What does it depend on?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 25
        ),
        Lesson(
            id = 226,
            title = "뭐 할 거야?",
            emoji = "📅",
            situation = "앞으로의 계획을 물을 때",
            target = "What are you going to do?",
            meaning = "뭐 할 거야?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "학교 끝나고 뭐 할 거야?",
            accepted = listOf("What are you going to do after school?", "What are you going to do?"),
            coachLine = "I'm going to meet my friend.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 26
        ),
        Lesson(
            id = 227,
            title = "이거부터 끝낼 거야",
            emoji = "1️⃣",
            situation = "할 일의 순서를 말할 때",
            target = "I'm going to finish this first.",
            meaning = "이거부터 끝낼 거야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "숙제부터 먼저 끝낼 거야.",
            accepted = listOf("I'm going to finish my homework first.", "I'm going to finish this first."),
            coachLine = "What will you do after that?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 27
        ),
        Lesson(
            id = 228,
            title = "나중에 갈지도 몰라",
            emoji = "🚶",
            situation = "확실하지 않은 계획을 말할 때",
            target = "I might go later.",
            meaning = "나중에 갈지도 몰라.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "오늘 오후에 갈지도 몰라.",
            accepted = listOf("I might go this afternoon.", "I might go later."),
            coachLine = "Let me know if you go.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 28
        ),
        Lesson(
            id = 229,
            title = "아직 결정 안 했어",
            emoji = "🤷",
            situation = "계획을 아직 정하지 않았을 때",
            target = "I haven't decided yet.",
            meaning = "아직 결정 안 했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "아직 뭘 할지 결정 못 했어.",
            accepted = listOf("I haven't decided what to do yet.", "I haven't decided yet."),
            coachLine = "Take your time.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 29
        ),
        Lesson(
            id = 230,
            title = "비가 오면 어떡하지?",
            emoji = "🌧️",
            situation = "가능한 문제를 생각할 때",
            target = "What if it rains?",
            meaning = "비가 오면 어떡하지?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내일 비가 오면 어떡하지?",
            accepted = listOf("What if it rains tomorrow?", "What if it rains?"),
            coachLine = "We can stay inside.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 30
        ),
        Lesson(
            id = 231,
            title = "다른 걸 하면 돼",
            emoji = "🔄",
            situation = "대안을 제시할 때",
            target = "We can do something else.",
            meaning = "다른 걸 하면 돼.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그럼 다른 걸 하면 돼.",
            accepted = listOf("Then we can do something else.", "We can do something else."),
            coachLine = "Like what?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 31
        ),
        Lesson(
            id = 232,
            title = "좋은 생각이 있어",
            emoji = "💡",
            situation = "아이디어를 제안할 때",
            target = "I have an idea.",
            meaning = "나 좋은 생각이 있어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "우리한테 좋은 생각이 하나 있어.",
            accepted = listOf("I have a good idea for us.", "I have an idea."),
            coachLine = "Tell me!",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 32
        ),
        Lesson(
            id = 233,
            title = "이거 해보는 건 어때?",
            emoji = "🧪",
            situation = "새 방법을 제안할 때",
            target = "Why don't we try this?",
            meaning = "우리 이거 해보는 건 어때?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이번에는 다른 방법으로 해보는 건 어때?",
            accepted = listOf("Why don't we try a different way?", "Why don't we try this?"),
            coachLine = "Okay. Let's try it.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 33
        ),
        Lesson(
            id = 234,
            title = "좋은 생각 같은데",
            emoji = "👍",
            situation = "제안에 긍정적으로 반응할 때",
            target = "That sounds like a good idea.",
            meaning = "좋은 생각 같은데.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 계획 좋은 것 같아.",
            accepted = listOf("That sounds like a good plan.", "That sounds like a good idea."),
            coachLine = "Let's do it.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 34
        ),
        Lesson(
            id = 235,
            title = "계획을 세우자",
            emoji = "🗓️",
            situation = "함께 계획할 때",
            target = "Let's make a plan.",
            meaning = "계획을 세우자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "우리 먼저 계획을 세우자.",
            accepted = listOf("Let's make a plan first.", "Let's make a plan."),
            coachLine = "Okay. What's first?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 35
        ),
        Lesson(
            id = 236,
            title = "먼저 이게 필요해",
            emoji = "📌",
            situation = "첫 번째 필요한 것을 말할 때",
            target = "First, we need to get the materials.",
            meaning = "먼저 준비물을 가져와야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "먼저 필요한 걸 다 준비해야 해.",
            accepted = listOf("First, we need to get everything ready.", "First, we need to get the materials."),
            coachLine = "What do we need?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 36
        ),
        Lesson(
            id = 237,
            title = "다음엔 뭘 해야 해?",
            emoji = "➡️",
            situation = "다음 단계를 물을 때",
            target = "What should we do next?",
            meaning = "다음엔 뭘 해야 해?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이제 다음으로 뭘 해야 해?",
            accepted = listOf("What do we need to do next?", "What should we do next?"),
            coachLine = "Let's check the instructions.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 37
        ),
        Lesson(
            id = 238,
            title = "조심해야 해",
            emoji = "⚠️",
            situation = "주의가 필요한 상황에서",
            target = "We need to be careful.",
            meaning = "우리 조심해야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "여기서는 정말 조심해야 해.",
            accepted = listOf("We need to be really careful here.", "We need to be careful."),
            coachLine = "You're right.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 38
        ),
        Lesson(
            id = 239,
            title = "뭔가 잘못된 것 같아",
            emoji = "🔧",
            situation = "문제가 생겼음을 알아챘을 때",
            target = "I think something is wrong.",
            meaning = "뭔가 잘못된 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이게 제대로 안 되는 것 같아.",
            accepted = listOf("I don't think this is working right.", "I think something is wrong."),
            coachLine = "Let's take a look.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 39
        ),
        Lesson(
            id = 240,
            title = "도움을 요청하자",
            emoji = "🆘",
            situation = "혼자 해결하기 어려울 때",
            target = "Let's ask for help.",
            meaning = "도움을 요청하자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "선생님께 도움을 요청하자.",
            accepted = listOf("Let's ask the teacher for help.", "Let's ask for help."),
            coachLine = "Good idea.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 40
        ),
        Lesson(
            id = 241,
            title = "내일이 걱정돼",
            emoji = "😟",
            situation = "앞으로의 일 때문에 긴장할 때",
            target = "I'm nervous about tomorrow.",
            meaning = "내일이 걱정돼.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내일 발표 때문에 긴장돼.",
            accepted = listOf("I'm nervous about my presentation tomorrow.", "I'm nervous about tomorrow."),
            coachLine = "You'll do fine.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 41
        ),
        Lesson(
            id = 242,
            title = "너무 걱정하지 마",
            emoji = "🌿",
            situation = "친구를 안심시킬 때",
            target = "Don't worry too much.",
            meaning = "너무 걱정하지 마.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "시험 때문에 너무 걱정하지 마.",
            accepted = listOf("Don't worry too much about the test.", "Don't worry too much."),
            coachLine = "I'll try not to.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 42
        ),
        Lesson(
            id = 243,
            title = "내가 자랑스러워",
            emoji = "🏅",
            situation = "자신의 성취를 말할 때",
            target = "I'm proud of myself.",
            meaning = "내가 자랑스러워.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "끝까지 해낸 내가 자랑스러워.",
            accepted = listOf("I'm proud of myself for finishing it.", "I'm proud of myself."),
            coachLine = "You should be!",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 43
        ),
        Lesson(
            id = 244,
            title = "실망했어",
            emoji = "😞",
            situation = "기대한 결과가 아니었을 때",
            target = "I was disappointed.",
            meaning = "실망했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "결과를 보고 조금 실망했어.",
            accepted = listOf("I was a little disappointed with the result.", "I was disappointed."),
            coachLine = "What happened?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 44
        ),
        Lesson(
            id = 245,
            title = "그거 놀라웠어",
            emoji = "😮",
            situation = "예상하지 못한 일에 반응할 때",
            target = "That surprised me.",
            meaning = "그거 놀라웠어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 말을 듣고 정말 놀랐어.",
            accepted = listOf("I was really surprised to hear that.", "That surprised me."),
            coachLine = "Me too.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 45
        ),
        Lesson(
            id = 246,
            title = "상처 주려던 건 아니야",
            emoji = "🙏",
            situation = "친구의 기분을 상하게 했을 때",
            target = "I didn't mean to hurt your feelings.",
            meaning = "네 기분을 상하게 하려던 건 아니야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그렇게 말해서 상처 주려던 건 아니야.",
            accepted = listOf("I didn't mean to upset you.", "I didn't mean to hurt your feelings."),
            coachLine = "I know.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 46
        ),
        Lesson(
            id = 247,
            title = "그거 괜찮아?",
            emoji = "🤝",
            situation = "상대가 동의하는지 확인할 때",
            target = "Are you okay with that?",
            meaning = "그거 괜찮아?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이렇게 해도 괜찮아?",
            accepted = listOf("Are you okay with doing it this way?", "Are you okay with that?"),
            coachLine = "Yeah, that's fine.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 47
        ),
        Lesson(
            id = 248,
            title = "이해해 줘서 고마워",
            emoji = "💛",
            situation = "상대가 이해해 준 데 감사할 때",
            target = "Thanks for understanding.",
            meaning = "이해해 줘서 고마워.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내 말 이해해 줘서 고마워.",
            accepted = listOf("Thanks for understanding what I meant.", "Thanks for understanding."),
            coachLine = "Of course.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 48
        ),
        Lesson(
            id = 249,
            title = "오늘 새로운 걸 배웠어",
            emoji = "🌱",
            situation = "새롭게 배운 것을 말할 때",
            target = "I learned something new today.",
            meaning = "오늘 새로운 걸 배웠어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "오늘 학교에서 새로운 걸 배웠어.",
            accepted = listOf("I learned something new at school today.", "I learned something new today."),
            coachLine = "What did you learn?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 49
        ),
        Lesson(
            id = 250,
            title = "그 얘기 더 해줘",
            emoji = "🗣️",
            situation = "상대 이야기를 더 듣고 싶을 때",
            target = "Tell me more about it.",
            meaning = "그 얘기 더 해줘.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그다음에 무슨 일이 있었는지 더 말해줘.",
            accepted = listOf("Tell me more about what happened.", "Tell me more about it."),
            coachLine = "Okay. So then...",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 50
        )
    )

    val lessons: List<Lesson> = baseLessons + Age810LessonExpansionCatalog.lessons
}
