package com.yamone.english

object Age810PronunciationQaCatalog {
    val guides = listOf(
        PronunciationQaGuide(201, "I for●GOT my ●HOME-work ↘", "아이 / 퍼갓 / 마이 / 홈워크", "아이 퍼●갓 마이 ●홈웍↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(202, "I ●FIN-ished‿it al●READ-y ↘", "아이 / 피니쉬트 / 잇 / 얼레디", "아이 ●피니쉬딧 얼●레디↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(203, "Could‿you ex●PLAIN that‿a●GAIN ↗", "쿠드 / 유 / 익스플레인 / 댓 / 어겐", "쿠쥬 익스●플레인 대러●겐↗", "약-약-강-약-강 ↗"),
        PronunciationQaGuide(204, "I ●THINK‿I under●STAND ↘", "아이 / 띵크 / 아이 / 언더스탠드", "아이 ●띵카이 언더●스탠드↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(205, "I NEED more ●TIME ↘", "아이 / 니드 / 모어 / 타임", "아이 니드 모어 ●타임↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(206, "What does this word ●MEAN ↘", "왓 / 더즈 / 디스 / 워드 / 민", "워더즈 디스 워드 ●민↘", "강-약-약-약-강 ↘"),
        PronunciationQaGuide(207, "HOW do‿you ●SPELL‿it ↘", "하우 / 두 / 유 / 스펠 / 잇", "하우쥬 ●스펠릿↘", "강-약-약-강-약 ↘"),
        PronunciationQaGuide(208, "Can‿I ●WORK with‿YOU ↗", "캔 / 아이 / 워크 / 위드 / 유", "커나이 ●워크 위쥬↗", "약-약-강-약-강 ↗"),
        PronunciationQaGuide(209, "Let's ●FIG-ure‿it ●OUT ↘", "렛츠 / 피겨 / 잇 / 아웃", "렛츠 ●피겨릿 ●아웃↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(210, "I MADE‿a mis●TAKE ↘", "아이 / 메이드 / 어 / 미스테이크", "아이 메이더 미스●테이크↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(211, "I WENT to the ●PARK yesterday ↘", "아이 / 웬트 / 투 / 더 / 파크 / 예스터데이", "아이 웬터더 ●파크 예스터데이↘", "약-강-약-약-강-약 ↘"),
        PronunciationQaGuide(212, "We ●PLAYED for two ●HOURS ↘", "위 / 플레이드 / 포 / 투 / 아워즈", "위 ●플레이드 퍼 투 ●아워즈↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(213, "I ●SAW something ●IN-ter-est-ing ↘", "아이 / 쏘 / 썸띵 / 인터레스팅", "아이 ●쏘 썸띵 ●인트러스팅↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(214, "What ●HAP-pened after ●THAT ↘", "왓 / 해픈드 / 애프터 / 댓", "왓 ●해픈드 애프터 ●댓↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(215, "THEN we went ●HOME ↘", "덴 / 위 / 웬트 / 홈", "●덴 위 웬트 ●홈↘", "강-약-약-강 ↘"),
        PronunciationQaGuide(216, "I've ●NEV-er tried that be●FORE ↘", "아이브 / 네버 / 트라이드 / 댓 / 비포어", "아이브 ●네버 트라이드 댓 비●포어↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(217, "I DID‿it by my●SELF ↘", "아이 / 디드 / 잇 / 바이 / 마이셀프", "아이 ●디딧 바이 마이●셀프↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(218, "It was ●EAS-i-er than I ●THOUGHT ↘", "잇 / 워즈 / 이지어 / 댄 / 아이 / 쏫", "잇 워즈 ●이지어 댄 아이 ●쏫↘", "약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(219, "THIS one is ●BET-ter ↘", "디스 / 원 / 이즈 / 베러", "●디스 원 이즈 ●베러↘", "강-약-약-강 ↘"),
        PronunciationQaGuide(220, "WHICH one do‿you pre●FER ↘", "위치 / 원 / 두 / 유 / 프리퍼", "●위치원 더유 프리●퍼↘", "강-약-약-약-강 ↘"),
        PronunciationQaGuide(221, "I LIKE this one because it's ●EAS-i-er ↘", "아이 / 라익 / 디스원 / 비커즈 / 잇츠 / 이지어", "아이 ●라익 디스원 비커즈 잇츠 ●이지어↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(222, "I don't a●GREE ↘", "아이 / 돈트 / 어그리", "아이 돈 어●그리↘", "약-약-강 ↘"),
        PronunciationQaGuide(223, "I SEE what‿you ●MEAN ↘", "아이 / 씨 / 왓 / 유 / 민", "아이 ●씨 왓츄 ●민↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(224, "MAY-be you're ●RIGHT ↘", "메이비 / 유어 / 라잇", "●메이비 유어 ●라잇↘", "강-약-강 ↘"),
        PronunciationQaGuide(225, "It de●PENDS ↘", "잇 / 디펜즈", "잇 디●펜즈↘", "약-강 ↘"),
        PronunciationQaGuide(226, "WHAT are‿you going to ●DO ↘", "왓 / 아 / 유 / 고잉 / 투 / 두", "●워러유 거너 ●두↘", "강-약-약-약-약-강 ↘"),
        PronunciationQaGuide(227, "I'm going to ●FIN-ish this ●FIRST ↘", "아임 / 고잉 / 투 / 피니쉬 / 디스 / 퍼스트", "아임 거너 ●피니쉬 디스 ●퍼스트↘", "약-약-약-강-약-강 ↘"),
        PronunciationQaGuide(228, "I MIGHT go ●LA-ter ↘", "아이 / 마잇 / 고 / 레이터", "아이 ●마잇 고 ●레이럴↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(229, "I HAV-en't de●CID-ed yet ↘", "아이 / 해븐트 / 디사이디드 / 옛", "아이 ●해븐 디●사이딧 옛↘", "약-강-강-약 ↘"),
        PronunciationQaGuide(230, "WHAT if‿it ●RAINS ↗", "왓 / 이프 / 잇 / 레인즈", "●워리핏 ●레인즈↗", "강-약-약-강 ↗"),
        PronunciationQaGuide(231, "We can DO something ●ELSE ↘", "위 / 캔 / 두 / 썸띵 / 엘스", "위 컨 ●두 썸띵 ●엘스↘", "약-약-강-약-강 ↘"),
        PronunciationQaGuide(232, "I HAVE‿an i●DE-a ↘", "아이 / 해브 / 언 / 아이디어", "아이 해번 아이●디어↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(233, "WHY don't‿we ●TRY this ↗", "와이 / 돈트 / 위 / 트라이 / 디스", "●와이 돈위 ●트라이 디스↗", "강-약-약-강-약 ↗"),
        PronunciationQaGuide(234, "That SOUNDS like‿a good i●DE-a ↘", "댓 / 사운즈 / 라익 / 어 / 굿 / 아이디어", "댓 ●사운즈 라이커 굿 아이●디어↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(235, "Let's MAKE‿a ●PLAN ↘", "렛츠 / 메이크 / 어 / 플랜", "렛츠 메이커 ●플랜↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(236, "FIRST | we need to get the ma●TE-ri-als ↘", "퍼스트 / 위 / 니드 / 투 / 겟 / 더 / 머티리얼즈", "●퍼스트 | 위 니드 터 겟 더 머●티리얼즈↘", "강 | 약-강-약-강-약-강 ↘"),
        PronunciationQaGuide(237, "WHAT should‿we do ●NEXT ↘", "왓 / 슈드 / 위 / 두 / 넥스트", "●왓 슈드위 두 ●넥스트↘", "강-약-약-약-강 ↘"),
        PronunciationQaGuide(238, "We NEED to be ●CARE-ful ↘", "위 / 니드 / 투 / 비 / 케어풀", "위 ●니드 터 비 ●케어풀↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(239, "I THINK something is ●WRONG ↘", "아이 / 띵크 / 썸띵 / 이즈 / 롱", "아이 ●띵크 썸띵 이즈 ●롱↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(240, "Let's ASK for ●HELP ↘", "렛츠 / 애스크 / 포 / 헬프", "렛츠 ●애스크 퍼 ●헬프↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(241, "I'm ●NER-vous about to●MOR-row ↘", "아임 / 너버스 / 어바웃 / 투마로우", "아임 ●너버스 어바웃 투●마로우↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(242, "Don't WOR-ry too ●MUCH ↘", "돈트 / 워리 / 투 / 머치", "돈 ●워리 투 ●머치↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(243, "I'm ●PROUD of my●SELF ↘", "아임 / 프라우드 / 어브 / 마이셀프", "아임 ●프라우더브 마이●셀프↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(244, "I was disap●POINT-ed ↘", "아이 / 워즈 / 디서포인티드", "아이 워즈 디서●포인릿↘", "약-약-강 ↘"),
        PronunciationQaGuide(245, "That sur●PRISED me ↘", "댓 / 서프라이즈드 / 미", "댓 서●프라이즈드 미↘", "약-강-약 ↘"),
        PronunciationQaGuide(246, "I didn't MEAN to hurt your ●FEEL-ings ↘", "아이 / 디든트 / 민 / 투 / 허트 / 유어 / 필링즈", "아이 디든 ●민 터 허츄어 ●필링즈↘", "약-약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(247, "Are‿you o●KAY with ●THAT ↗", "아 / 유 / 오케이 / 위드 / 댓", "얼유 오●케이 위드 ●댓↗", "약-약-강-약-강 ↗"),
        PronunciationQaGuide(248, "THANKS for under●STAND-ing ↘", "땡크스 / 포 / 언더스탠딩", "●땡크스 퍼 언더●스탠딩↘", "강-약-강 ↘"),
        PronunciationQaGuide(249, "I LEARNED something NEW to●DAY ↘", "아이 / 런드 / 썸띵 / 뉴 / 투데이", "아이 ●런드 썸띵 ●뉴 터●데이↘", "약-강-약-강-강 ↘"),
        PronunciationQaGuide(250, "TELL me MORE about‿it ↘", "텔 / 미 / 모어 / 어바웃 / 잇", "●텔미 ●모어 어바우릿↘", "강-약-강-약-약 ↘")
    )
}
