package com.yamone.english

object Age810PronunciationQaExpansionCatalog {
    val guides = listOf(
        PronunciationQaGuide(251, "I NEED to re●MEM-ber to ●BRING‿it ↘", "아이 / 니드 / 투 / 리멤버 / 투 / 브링 / 잇", "아이 니드 터 리●멤버 터 ●브링잇↘", "약-강-약-강-약-강-약 ↘"),
        PronunciationQaGuide(252, "It's my re-spon-si●BIL-i-ty ↘", "잇츠 / 마이 / 리스판서빌러티", "잇츠 마이 리스판서●빌러리↘", "약-약-강 ↘"),
        PronunciationQaGuide(253, "I ●PROM-ised I would ●DO‿it ↘", "아이 / 프라미스트 / 아이 / 우드 / 두 / 잇", "아이 ●프라미스타이 우드 ●두윗↘", "약-강-약-약-강-약 ↘"),
        PronunciationQaGuide(254, "I HAVE to ●FIN-ish this ●FIRST ↘", "아이 / 해브 / 투 / 피니쉬 / 디스 / 퍼스트", "아이 해프 터 ●피니쉬 디스 ●퍼스트↘", "약-강-약-강-약-강 ↘"),
        PronunciationQaGuide(255, "I can DO‿it ●LA-ter ↘", "아이 / 캔 / 두 / 잇 / 레이터", "아이 컨 ●두윗 ●레이럴↘", "약-약-강-약-강 ↘"),
        PronunciationQaGuide(256, "I NEED to get ●OR-ga-nized ↘", "아이 / 니드 / 투 / 겟 / 오거나이즈드", "아이 니드 터 겟 ●오거나이즈드↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(257, "I AL-most for●GOT ↘", "아이 / 올모스트 / 퍼갓", "아이 ●올모스트 퍼●갓↘", "약-강-강 ↘"),
        PronunciationQaGuide(258, "I was sup●POSED to do ●THAT ↘", "아이 / 워즈 / 서포우즈드 / 투 / 두 / 댓", "아이 워즈 서●포우즈 터 두 ●댓↘", "약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(259, "I didn't HAVE e●NOUGH TIME ↘", "아이 / 디든트 / 해브 / 이너프 / 타임", "아이 디든 ●해브 이●너프 ●타임↘", "약-약-강-강-강 ↘"),
        PronunciationQaGuide(260, "I ●MAN-aged to ●FIN-ish‿it ↘", "아이 / 매니지드 / 투 / 피니쉬 / 잇", "아이 ●매니지드 터 ●피니쉬잇↘", "약-강-약-강-약 ↘"),
        PronunciationQaGuide(261, "I didn't MEAN‿it that ●WAY ↘", "아이 / 디든트 / 민 / 잇 / 댓 / 웨이", "아이 디든 ●미닛 댓 ●웨이↘", "약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(262, "Can‿we TALK about what ●HAP-pened ↗", "캔 / 위 / 톡 / 어바웃 / 왓 / 해픈드", "컨위 ●토커바웃 왓 ●해픈드↗", "약-약-강-약-약-강 ↗"),
        PronunciationQaGuide(263, "I under●STAND why you're up●SET ↘", "아이 / 언더스탠드 / 와이 / 유어 / 업셋", "아이 언더●스탠드 와이 유어 업●셋↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(264, "That WAS-n't very ●NICE ↘", "댓 / 워즌트 / 베리 / 나이스", "댓 ●워즌 베리 ●나이스↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(265, "Let's START ●O-ver ↘", "렛츠 / 스타트 / 오버", "렛츠 ●스타트 ●오버↘", "약-강-강 ↘"),
        PronunciationQaGuide(266, "We BOTH made mis●TAKES ↘", "위 / 보우쓰 / 메이드 / 미스테익스", "위 ●보우쓰 메이드 미스●테익스↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(267, "I SHOULD have ●LIS-tened ↘", "아이 / 슈드 / 해브 / 리슨드", "아이 ●슈더브 ●리슨드↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(268, "You can COUNT on ●ME ↘", "유 / 캔 / 카운트 / 온 / 미", "유 컨 ●카운던 ●미↘", "약-약-강-약-강 ↘"),
        PronunciationQaGuide(269, "THANKS for being ●HON-est ↘", "땡크스 / 포 / 비잉 / 아너스트", "●땡크스 퍼 비잉 ●아너스트↘", "강-약-약-강 ↘"),
        PronunciationQaGuide(270, "I for●GIVE you ↘", "아이 / 퍼기브 / 유", "아이 퍼●기브유↘", "약-강-약 ↘"),
        PronunciationQaGuide(271, "I THINK it happened because of ●THAT ↘", "아이 / 띵크 / 잇 / 해픈드 / 비커즈 / 어브 / 댓", "아이 ●띵킷 해픈드 비커저브 ●댓↘", "약-강-약-약-약-약-강 ↘"),
        PronunciationQaGuide(272, "THAT'S why it ●HAP-pened ↘", "댓츠 / 와이 / 잇 / 해픈드", "●댓츠 와이 잇 ●해픈드↘", "강-약-약-강 ↘"),
        PronunciationQaGuide(273, "If‿we DO this | it should ●WORK ↘", "이프 / 위 / 두 / 디스 / 잇 / 슈드 / 워크", "이프위 ●두 디스 | 잇 슈드 ●워크↘", "약-약-강-약 | 약-약-강 ↘"),
        PronunciationQaGuide(274, "WHAT do‿you think will ●HAP-pen ↘", "왓 / 두 / 유 / 띵크 / 윌 / 해픈", "●왓 더유 띵크 윌 ●해픈↘", "강-약-약-강-약-강 ↘"),
        PronunciationQaGuide(275, "My GUESS is that it'll ●FLOAT ↘", "마이 / 게스 / 이즈 / 댓 / 이럴 / 플로우트", "마이 ●게스 이즈 댓 이럴 ●플로우트↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(276, "Let's TEST‿it and ●SEE ↘", "렛츠 / 테스트 / 잇 / 앤드 / 씨", "렛츠 ●테스릿 앤 ●씨↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(277, "The re●SULT was ●DIFF-er-ent ↘", "더 / 리절트 / 워즈 / 디퍼런트", "더 리●절트 워즈 ●디프런트↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(278, "I ●NO-ticed SOME-thing ↘", "아이 / 노우티스트 / 썸띵", "아이 ●노우티스트 ●썸띵↘", "약-강-강 ↘"),
        PronunciationQaGuide(279, "It CHANG-es when the ●TEM-per-a-ture changes ↘", "잇 / 체인지즈 / 웬 / 더 / 템퍼러처 / 체인지즈", "잇 ●체인지즈 웬 더 ●템프러처 체인지즈↘", "약-강-약-약-강-약 ↘"),
        PronunciationQaGuide(280, "That ex●PLAINS‿it ↘", "댓 / 익스플레인즈 / 잇", "댓 익스●플레인짓↘", "약-강-약 ↘"),
        PronunciationQaGuide(281, "I HAVE too much to ●DO ↘", "아이 / 해브 / 투 / 머치 / 투 / 두", "아이 ●해브 투 머치 터 ●두↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(282, "Let's de●CIDE what's most im●POR-tant ↘", "렛츠 / 디사이드 / 왓츠 / 모스트 / 임포턴트", "렛츠 디●사이드 왓츠 모스트 임●포런트↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(283, "I'll DO this FIRST | and that ●LA-ter ↘", "아일 / 두 / 디스 / 퍼스트 / 앤드 / 댓 / 레이터", "아일 ●두 디스 ●퍼스트 | 앤 댓 ●레이럴↘", "약-강-약-강 | 약-약-강 ↘"),
        PronunciationQaGuide(284, "I NEED‿a short ●BREAK ↘", "아이 / 니드 / 어 / 쇼트 / 브레이크", "아이 니더 쇼트 ●브레이크↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(285, "I'm RUN-ning out of ●TIME ↘", "아임 / 러닝 / 아웃 / 어브 / 타임", "아임 ●러닝 아우러브 ●타임↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(286, "We STILL have enough ●TIME ↘", "위 / 스틸 / 해브 / 이너프 / 타임", "위 ●스틸 해브 이너프 ●타임↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(287, "Let's LEAVE‿a little ●EAR-li-er ↘", "렛츠 / 리브 / 어 / 리를 / 얼리어", "렛츠 ●리버 리를 ●얼리어↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(288, "I CHANGED my ●MIND ↘", "아이 / 체인지드 / 마이 / 마인드", "아이 ●체인지드 마이 ●마인드↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(289, "I'd RATH-er do ●THIS ↘", "아이드 / 래더 / 두 / 디스", "아이드 ●래더 두 ●디스↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(290, "That WORKS better for ●ME ↘", "댓 / 웍스 / 베러 / 포 / 미", "댓 ●웍스 베러 퍼 ●미↘", "약-강-약-약-강 ↘"),
        PronunciationQaGuide(291, "At FIRST | I thought it'd be ●EAS-y ↘", "앳 / 퍼스트 / 아이 / 쏫 / 잇드 / 비 / 이지", "앳 ●퍼스트 | 아이 쏫 잇드비 ●이지↘", "약-강 | 약-약-약-약-강 ↘"),
        PronunciationQaGuide(292, "Then I ●RE-al-ized it was HARD-er than I ●THOUGHT ↘", "덴 / 아이 / 리얼라이즈드 / 잇 / 워즈 / 하더 / 댄 / 아이 / 쏫", "덴 아이 ●리얼라이즈딧 워즈 ●하더 댄 아이 ●쏫↘", "약-약-강-약-약-강-약-약-강 ↘"),
        PronunciationQaGuide(293, "In the END | it WORKED ●OUT ↘", "인 / 더 / 엔드 / 잇 / 웍트 / 아웃", "인 디 ●엔드 | 잇 웍트 ●아웃↘", "약-약-강 | 약-약-강 ↘"),
        PronunciationQaGuide(294, "The BEST part was doing it to●GETH-er ↘", "더 / 베스트 / 파트 / 워즈 / 두잉 / 잇 / 터게더", "더 ●베스트 파트 워즈 두잉잇 터●게더↘", "약-강-약-약-약-약-강 ↘"),
        PronunciationQaGuide(295, "The HARD-est part was getting ●START-ed ↘", "더 / 하디스트 / 파트 / 워즈 / 게팅 / 스타티드", "더 ●하디스트 파트 워즈 게링 ●스타리드↘", "약-강-약-약-약-강 ↘"),
        PronunciationQaGuide(296, "NEXT time | I'll START ●EAR-li-er ↘", "넥스트 / 타임 / 아일 / 스타트 / 얼리어", "●넥스트 타임 | 아일 스타트 ●얼리어↘", "강-약 | 약-약-강 ↘"),
        PronunciationQaGuide(297, "I LEARNED that PRACTICE really ●HELPS ↘", "아이 / 런드 / 댓 / 프랙티스 / 리얼리 / 헬프스", "아이 ●런드 댓 ●프랙티스 리얼리 ●헬프스↘", "약-강-약-강-약-강 ↘"),
        PronunciationQaGuide(298, "I WISH I could DO‿it a●GAIN ↘", "아이 / 위시 / 아이 / 쿠드 / 두 / 잇 / 어겐", "아이 ●위샤이 쿠드 ●두윗 어●겐↘", "약-강-약-약-강-약-강 ↘"),
        PronunciationQaGuide(299, "I'm GLAD I ●TRIED ↘", "아임 / 글래드 / 아이 / 트라이드", "아임 ●글래다이 ●트라이드↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(300, "I THINK I've gotten ●BET-ter ↘", "아이 / 띵크 / 아이브 / 가튼 / 베러", "아이 ●띵카이브 가튼 ●베러↘", "약-강-약-약-강 ↘")
    )
}
