package com.yamone.english

object Age810LessonExpansionCatalog {
    val lessons = listOf(
        Lesson(
            id = 251,
            title = "기억해야 해",
            emoji = "🧠",
            situation = "해야 할 일을 잊지 않으려 할 때",
            target = "I need to remember to bring it.",
            meaning = "그거 가져오는 걸 기억해야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내일 책 가져오는 걸 기억해야 해.",
            accepted = listOf("I need to remember to bring my book tomorrow.", "I need to remember to bring it."),
            coachLine = "What do you need to remember?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 51
        ),
        Lesson(
            id = 252,
            title = "내 책임이야",
            emoji = "🎯",
            situation = "자신이 맡은 일을 말할 때",
            target = "It's my responsibility.",
            meaning = "그건 내 책임이야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이 일을 끝내는 건 내 책임이야.",
            accepted = listOf("It's my responsibility to finish this.", "It's my responsibility."),
            coachLine = "Who is responsible for it?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 52
        ),
        Lesson(
            id = 253,
            title = "내가 하겠다고 약속했어",
            emoji = "🤝",
            situation = "한 약속을 지키려 할 때",
            target = "I promised I would do it.",
            meaning = "내가 하겠다고 약속했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "오늘 끝내겠다고 약속했어.",
            accepted = listOf("I promised I would finish it today.", "I promised I would do it."),
            coachLine = "Did you promise?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 53
        ),
        Lesson(
            id = 254,
            title = "먼저 끝내야 해",
            emoji = "⏳",
            situation = "다른 일을 하기 전 해야 할 일이 있을 때",
            target = "I have to finish this first.",
            meaning = "이걸 먼저 끝내야 해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "놀기 전에 숙제를 끝내야 해.",
            accepted = listOf("I have to finish my homework first.", "I have to finish this first."),
            coachLine = "What do you have to finish?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 54
        ),
        Lesson(
            id = 255,
            title = "나중에 해도 돼",
            emoji = "🕒",
            situation = "급하지 않은 일을 미룰 수 있을 때",
            target = "I can do it later.",
            meaning = "그건 나중에 해도 돼.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이건 저녁에 해도 돼.",
            accepted = listOf("I can do this later tonight.", "I can do it later."),
            coachLine = "Does it need to be done now?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 55
        ),
        Lesson(
            id = 256,
            title = "정리해야겠어",
            emoji = "🗂️",
            situation = "물건이나 할 일을 정리할 때",
            target = "I need to get organized.",
            meaning = "정리해야겠어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내 책상부터 정리해야겠어.",
            accepted = listOf("I need to organize my desk first.", "I need to get organized."),
            coachLine = "What do you need to organize?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 56
        ),
        Lesson(
            id = 257,
            title = "거의 잊을 뻔했어",
            emoji = "😅",
            situation = "해야 할 일을 막 기억했을 때",
            target = "I almost forgot.",
            meaning = "거의 잊을 뻔했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "숙제 내는 걸 거의 잊을 뻔했어.",
            accepted = listOf("I almost forgot to turn in my homework.", "I almost forgot."),
            coachLine = "What did you almost forget?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 57
        ),
        Lesson(
            id = 258,
            title = "하기로 되어 있었어",
            emoji = "📌",
            situation = "원래 해야 했던 일을 말할 때",
            target = "I was supposed to do that.",
            meaning = "그거 내가 하기로 되어 있었어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내가 쓰레기를 버리기로 되어 있었어.",
            accepted = listOf("I was supposed to take out the trash.", "I was supposed to do that."),
            coachLine = "Were you supposed to do it?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 58
        ),
        Lesson(
            id = 259,
            title = "시간이 부족했어",
            emoji = "⌛",
            situation = "시간이 모자라 일을 끝내지 못했을 때",
            target = "I didn't have enough time.",
            meaning = "시간이 충분하지 않았어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "다 끝내기엔 시간이 부족했어.",
            accepted = listOf("I didn't have enough time to finish everything.", "I didn't have enough time."),
            coachLine = "Why didn't you finish?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 59
        ),
        Lesson(
            id = 260,
            title = "결국 끝냈어",
            emoji = "🏁",
            situation = "어려웠지만 일을 마쳤을 때",
            target = "I managed to finish it.",
            meaning = "결국 끝냈어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "시간은 걸렸지만 결국 끝냈어.",
            accepted = listOf("It took a while, but I managed to finish it.", "I managed to finish it."),
            coachLine = "Did you finish in the end?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 60
        ),
        Lesson(
            id = 261,
            title = "그런 뜻은 아니었어",
            emoji = "💬",
            situation = "말이 잘못 전달됐을 때",
            target = "I didn't mean it that way.",
            meaning = "그런 뜻으로 말한 건 아니야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "네 기분을 나쁘게 하려던 뜻은 아니었어.",
            accepted = listOf("I didn't mean it in a bad way.", "I didn't mean it that way."),
            coachLine = "What did you mean?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 61
        ),
        Lesson(
            id = 262,
            title = "무슨 일이었는지 얘기하자",
            emoji = "🗣️",
            situation = "갈등이 생긴 뒤 대화하려 할 때",
            target = "Can we talk about what happened?",
            meaning = "무슨 일이 있었는지 얘기할 수 있을까?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "아까 무슨 일이 있었는지 얘기하자.",
            accepted = listOf("Can we talk about what happened earlier?", "Can we talk about what happened?"),
            coachLine = "Sure. Let's talk.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 62
        ),
        Lesson(
            id = 263,
            title = "왜 화났는지 이해해",
            emoji = "🤍",
            situation = "상대 감정을 인정할 때",
            target = "I understand why you're upset.",
            meaning = "네가 왜 속상한지 이해해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "네가 왜 나한테 화났는지 이해해.",
            accepted = listOf("I understand why you're upset with me.", "I understand why you're upset."),
            coachLine = "Do you really understand?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 63
        ),
        Lesson(
            id = 264,
            title = "그건 좀 심했어",
            emoji = "🚫",
            situation = "상대 행동이 좋지 않았다고 말할 때",
            target = "That wasn't very nice.",
            meaning = "그건 별로 친절하지 않았어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그렇게 말한 건 좀 심했어.",
            accepted = listOf("That wasn't a very nice thing to say.", "That wasn't very nice."),
            coachLine = "What wasn't nice?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 64
        ),
        Lesson(
            id = 265,
            title = "다시 시작하자",
            emoji = "🔄",
            situation = "갈등 뒤 관계를 회복하려 할 때",
            target = "Let's start over.",
            meaning = "다시 시작하자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "우리 그냥 처음부터 다시 시작하자.",
            accepted = listOf("Let's just start over from the beginning.", "Let's start over."),
            coachLine = "Okay. Let's start over.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 65
        ),
        Lesson(
            id = 266,
            title = "우리 둘 다 실수했어",
            emoji = "⚖️",
            situation = "서로 잘못이 있었음을 인정할 때",
            target = "We both made mistakes.",
            meaning = "우리 둘 다 실수했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "생각해 보니 우리 둘 다 잘못했어.",
            accepted = listOf("I think we both made mistakes.", "We both made mistakes."),
            coachLine = "What could we do differently?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 66
        ),
        Lesson(
            id = 267,
            title = "내가 들었어야 했어",
            emoji = "👂",
            situation = "상대 말을 듣지 않은 것을 후회할 때",
            target = "I should have listened.",
            meaning = "내가 들었어야 했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "네 말을 더 잘 들었어야 했어.",
            accepted = listOf("I should have listened to you.", "I should have listened."),
            coachLine = "What will you do next time?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 67
        ),
        Lesson(
            id = 268,
            title = "나 믿어도 돼",
            emoji = "🛡️",
            situation = "책임 있게 하겠다고 말할 때",
            target = "You can count on me.",
            meaning = "나 믿어도 돼.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이번에는 정말 나 믿어도 돼.",
            accepted = listOf("You can count on me this time.", "You can count on me."),
            coachLine = "Can I really count on you?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 68
        ),
        Lesson(
            id = 269,
            title = "솔직히 말해줘서 고마워",
            emoji = "💛",
            situation = "상대의 솔직함에 감사할 때",
            target = "Thanks for being honest.",
            meaning = "솔직히 말해줘서 고마워.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "나한테 솔직히 말해줘서 고마워.",
            accepted = listOf("Thanks for being honest with me.", "Thanks for being honest."),
            coachLine = "You're welcome.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 69
        ),
        Lesson(
            id = 270,
            title = "용서할게",
            emoji = "🌿",
            situation = "사과를 받아들일 때",
            target = "I forgive you.",
            meaning = "용서할게.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "괜찮아, 이번엔 용서할게.",
            accepted = listOf("It's okay. I forgive you.", "I forgive you."),
            coachLine = "Are we okay now?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 70
        ),
        Lesson(
            id = 271,
            title = "아마 그 때문인 것 같아",
            emoji = "🔍",
            situation = "원인을 추측할 때",
            target = "I think it happened because of that.",
            meaning = "그것 때문에 그런 일이 생긴 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "물이 들어가서 멈춘 것 같아.",
            accepted = listOf("I think it stopped because water got inside.", "I think it happened because of that."),
            coachLine = "Why do you think that happened?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 71
        ),
        Lesson(
            id = 272,
            title = "그래서 그런 거야",
            emoji = "➡️",
            situation = "원인과 결과를 연결할 때",
            target = "That's why it happened.",
            meaning = "그래서 그런 일이 생긴 거야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그래서 불이 꺼진 거야.",
            accepted = listOf("That's why the light went out.", "That's why it happened."),
            coachLine = "So that's the reason?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 72
        ),
        Lesson(
            id = 273,
            title = "이렇게 하면 어떻게 될까",
            emoji = "🧪",
            situation = "조건과 결과를 생각할 때",
            target = "If we do this, it should work.",
            meaning = "이렇게 하면 될 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이걸 먼저 하면 더 잘 될 거야.",
            accepted = listOf("If we do this first, it should work better.", "If we do this, it should work."),
            coachLine = "What happens if we do that?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 73
        ),
        Lesson(
            id = 274,
            title = "어떻게 될 것 같아?",
            emoji = "🔮",
            situation = "결과를 예상하게 할 때",
            target = "What do you think will happen?",
            meaning = "어떻게 될 것 같아?",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "이걸 섞으면 어떻게 될 것 같아?",
            accepted = listOf("What do you think will happen if we mix them?", "What do you think will happen?"),
            coachLine = "I think it will change color.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 74
        ),
        Lesson(
            id = 275,
            title = "내 생각엔...",
            emoji = "💭",
            situation = "자신의 추측을 말할 때",
            target = "My guess is that it will float.",
            meaning = "내 생각엔 그게 뜰 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "내 생각엔 더 빨리 녹을 것 같아.",
            accepted = listOf("My guess is that it will melt faster.", "My guess is that it will float."),
            coachLine = "Why do you think so?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 75
        ),
        Lesson(
            id = 276,
            title = "시험해 보자",
            emoji = "🧫",
            situation = "추측을 확인하려 할 때",
            target = "Let's test it and see.",
            meaning = "시험해 보고 확인하자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "우리 직접 해보고 확인하자.",
            accepted = listOf("Let's try it and see what happens.", "Let's test it and see."),
            coachLine = "Okay. Let's test it.",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 76
        ),
        Lesson(
            id = 277,
            title = "결과가 달랐어",
            emoji = "📊",
            situation = "예상과 결과가 다를 때",
            target = "The result was different.",
            meaning = "결과가 달랐어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "우리가 예상한 것과 결과가 달랐어.",
            accepted = listOf("The result was different from what we expected.", "The result was different."),
            coachLine = "What was different?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 77
        ),
        Lesson(
            id = 278,
            title = "뭔가 알아챘어",
            emoji = "👀",
            situation = "관찰한 특징을 말할 때",
            target = "I noticed something.",
            meaning = "뭔가 알아챘어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "한쪽이 더 빨리 녹는 걸 알아챘어.",
            accepted = listOf("I noticed that one side melted faster.", "I noticed something."),
            coachLine = "What did you notice?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 78
        ),
        Lesson(
            id = 279,
            title = "온도에 따라 달라져",
            emoji = "🌡️",
            situation = "조건에 따른 변화를 말할 때",
            target = "It changes when the temperature changes.",
            meaning = "온도가 바뀌면 달라져.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "더 따뜻해지면 더 빨리 변해.",
            accepted = listOf("It changes faster when it gets warmer.", "It changes when the temperature changes."),
            coachLine = "What makes it change?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 79
        ),
        Lesson(
            id = 280,
            title = "이제 이유를 알겠어",
            emoji = "💡",
            situation = "원인을 이해했을 때",
            target = "That explains it.",
            meaning = "이제 이유를 알겠어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "아, 그게 왜 그랬는지 이제 설명되네.",
            accepted = listOf("That explains why it happened.", "That explains it."),
            coachLine = "Does it make sense now?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 80
        ),
        Lesson(
            id = 281,
            title = "할 일이 너무 많아",
            emoji = "📚",
            situation = "해야 할 일이 많다고 느낄 때",
            target = "I have too much to do.",
            meaning = "할 일이 너무 많아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "오늘 해야 할 게 너무 많아.",
            accepted = listOf("I have too much to do today.", "I have too much to do."),
            coachLine = "What do you have to do?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 81
        ),
        Lesson(
            id = 282,
            title = "뭐가 제일 중요한지 정하자",
            emoji = "🎯",
            situation = "우선순위를 정할 때",
            target = "Let's decide what's most important.",
            meaning = "뭐가 제일 중요한지 정하자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "먼저 해야 할 일을 정하자.",
            accepted = listOf("Let's decide what we need to do first.", "Let's decide what's most important."),
            coachLine = "What's most important?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 82
        ),
        Lesson(
            id = 283,
            title = "이건 먼저, 저건 나중에",
            emoji = "🧭",
            situation = "일의 순서를 정할 때",
            target = "I'll do this first and that later.",
            meaning = "이건 먼저 하고 저건 나중에 할게.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "숙제를 먼저 하고 청소는 나중에 할게.",
            accepted = listOf("I'll do my homework first and clean later.", "I'll do this first and that later."),
            coachLine = "What will you do first?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 83
        ),
        Lesson(
            id = 284,
            title = "잠깐 쉬어야겠어",
            emoji = "🧘",
            situation = "집중력이 떨어져 휴식이 필요할 때",
            target = "I need a short break.",
            meaning = "잠깐 쉬어야겠어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "10분만 쉬고 다시 할게.",
            accepted = listOf("I need a ten-minute break before I keep going.", "I need a short break."),
            coachLine = "Do you need a break?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 84
        ),
        Lesson(
            id = 285,
            title = "시간이 얼마 안 남았어",
            emoji = "⏰",
            situation = "마감이 가까울 때",
            target = "I'm running out of time.",
            meaning = "시간이 얼마 안 남았어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "끝내려면 시간이 얼마 안 남았어.",
            accepted = listOf("I'm running out of time to finish this.", "I'm running out of time."),
            coachLine = "How much time is left?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 85
        ),
        Lesson(
            id = 286,
            title = "아직 시간은 충분해",
            emoji = "⌚",
            situation = "서두를 필요가 없을 때",
            target = "We still have enough time.",
            meaning = "아직 시간은 충분해.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "아직 끝낼 시간은 충분해.",
            accepted = listOf("We still have enough time to finish.", "We still have enough time."),
            coachLine = "Do we need to hurry?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 86
        ),
        Lesson(
            id = 287,
            title = "조금 일찍 출발하자",
            emoji = "🚗",
            situation = "늦지 않으려 일찍 움직일 때",
            target = "Let's leave a little earlier.",
            meaning = "조금 일찍 출발하자.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "늦지 않게 10분 일찍 출발하자.",
            accepted = listOf("Let's leave ten minutes early so we're not late.", "Let's leave a little earlier."),
            coachLine = "What time should we leave?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 87
        ),
        Lesson(
            id = 288,
            title = "생각이 바뀌었어",
            emoji = "🔁",
            situation = "결정을 바꿨을 때",
            target = "I changed my mind.",
            meaning = "생각이 바뀌었어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "생각해 보니 다른 걸 하고 싶어.",
            accepted = listOf("I changed my mind. I want to do something else.", "I changed my mind."),
            coachLine = "Why did you change your mind?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 88
        ),
        Lesson(
            id = 289,
            title = "차라리 이걸 할래",
            emoji = "⭐",
            situation = "두 선택 중 더 원하는 것을 말할 때",
            target = "I'd rather do this.",
            meaning = "난 차라리 이걸 할래.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "밖에 나가기보다 집에 있을래.",
            accepted = listOf("I'd rather stay home than go out.", "I'd rather do this."),
            coachLine = "Which would you rather do?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 89
        ),
        Lesson(
            id = 290,
            title = "이게 나한테 더 잘 맞아",
            emoji = "👌",
            situation = "자신에게 더 편한 방법을 말할 때",
            target = "That works better for me.",
            meaning = "그게 나한테 더 잘 맞아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "오후에 하는 게 나한테 더 좋아.",
            accepted = listOf("Doing it in the afternoon works better for me.", "That works better for me."),
            coachLine = "What time works for you?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 90
        ),
        Lesson(
            id = 291,
            title = "처음엔 이렇게 생각했어",
            emoji = "📖",
            situation = "생각이 변한 과정을 말할 때",
            target = "At first, I thought it would be easy.",
            meaning = "처음엔 쉬울 거라고 생각했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "처음엔 금방 끝날 줄 알았어.",
            accepted = listOf("At first, I thought I would finish quickly.", "At first, I thought it would be easy."),
            coachLine = "What did you think at first?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 91
        ),
        Lesson(
            id = 292,
            title = "그러다 알게 됐어",
            emoji = "💡",
            situation = "중간에 깨달은 점을 말할 때",
            target = "Then I realized it was harder than I thought.",
            meaning = "그러다 생각보다 어렵다는 걸 알게 됐어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그러다 내가 틀렸다는 걸 알게 됐어.",
            accepted = listOf("Then I realized I was wrong.", "Then I realized it was harder than I thought."),
            coachLine = "When did you realize that?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 92
        ),
        Lesson(
            id = 293,
            title = "결국 잘됐어",
            emoji = "🏁",
            situation = "마지막 결과를 정리할 때",
            target = "In the end, it worked out.",
            meaning = "결국 잘됐어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "결국 모든 게 잘 해결됐어.",
            accepted = listOf("In the end, everything worked out.", "In the end, it worked out."),
            coachLine = "How did it end?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 93
        ),
        Lesson(
            id = 294,
            title = "제일 좋았던 건...",
            emoji = "🌟",
            situation = "경험의 좋은 부분을 말할 때",
            target = "The best part was doing it together.",
            meaning = "제일 좋았던 건 같이 한 거였어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "제일 좋았던 건 마지막 게임이었어.",
            accepted = listOf("The best part was the last game.", "The best part was doing it together."),
            coachLine = "What was the best part?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 94
        ),
        Lesson(
            id = 295,
            title = "제일 어려웠던 건...",
            emoji = "⛰️",
            situation = "힘들었던 부분을 말할 때",
            target = "The hardest part was getting started.",
            meaning = "제일 어려웠던 건 시작하는 거였어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "제일 어려웠던 건 집중하는 거였어.",
            accepted = listOf("The hardest part was staying focused.", "The hardest part was getting started."),
            coachLine = "What was the hardest part?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 95
        ),
        Lesson(
            id = 296,
            title = "다음엔 이렇게 할 거야",
            emoji = "🔜",
            situation = "다음번 개선점을 말할 때",
            target = "Next time, I'll start earlier.",
            meaning = "다음엔 더 일찍 시작할 거야.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "다음엔 먼저 계획을 세울 거야.",
            accepted = listOf("Next time, I'll make a plan first.", "Next time, I'll start earlier."),
            coachLine = "What will you do next time?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 96
        ),
        Lesson(
            id = 297,
            title = "이걸 배웠어",
            emoji = "🌱",
            situation = "경험에서 배운 점을 말할 때",
            target = "I learned that practice really helps.",
            meaning = "연습이 정말 도움이 된다는 걸 배웠어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "미리 준비하는 게 중요하다는 걸 배웠어.",
            accepted = listOf("I learned that being prepared is important.", "I learned that practice really helps."),
            coachLine = "What did you learn?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 97
        ),
        Lesson(
            id = 298,
            title = "한 번 더 해보고 싶어",
            emoji = "🔁",
            situation = "좋았던 경험을 다시 하고 싶을 때",
            target = "I wish I could do it again.",
            meaning = "한 번 더 해볼 수 있으면 좋겠어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "그 여행을 다시 갈 수 있으면 좋겠어.",
            accepted = listOf("I wish I could go on that trip again.", "I wish I could do it again."),
            coachLine = "Would you do it again?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 98
        ),
        Lesson(
            id = 299,
            title = "해보길 잘했어",
            emoji = "😊",
            situation = "도전한 것을 긍정적으로 돌아볼 때",
            target = "I'm glad I tried.",
            meaning = "해보길 잘했어.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "긴장됐지만 해보길 잘했어.",
            accepted = listOf("I was nervous, but I'm glad I tried.", "I'm glad I tried."),
            coachLine = "Are you glad you did it?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 99
        ),
        Lesson(
            id = 300,
            title = "나 좀 늘은 것 같아",
            emoji = "📈",
            situation = "자신의 발전을 느낄 때",
            target = "I think I've gotten better.",
            meaning = "나 좀 늘은 것 같아.",
            soundEnglish = "",
            soundKorean = "",
            connectedNote = "",
            ownPromptKo = "전보다 영어가 좀 늘은 것 같아.",
            accepted = listOf("I think I've gotten better at English.", "I think I've gotten better."),
            coachLine = "What do you think improved?",
            course = CourseLevel.AGE_8_10,
            courseLessonNumber = 100
        )
    )
}
