package com.yamone.english

object Age810ThinkingExpansionCatalog {
    val guides = listOf(
        ThinkingGuide(251, "나는 → 필요해 → 기억하는 것이 → 그것을 가져오는 것을"),
        ThinkingGuide(252, "그것은 → 나의 → 책임이야"),
        ThinkingGuide(253, "나는 → 약속했어 → 내가 그것을 할 거라고"),
        ThinkingGuide(254, "나는 → 해야 해 → 끝내는 것을 → 이것부터"),
        ThinkingGuide(255, "나는 → 할 수 있어 → 그것을 → 나중에"),
        ThinkingGuide(256, "나는 → 필요해 → 정리되는 것이"),
        ThinkingGuide(257, "나는 → 거의 → 잊었어"),
        ThinkingGuide(258, "나는 → 하기로 되어 있었어 → 그것을"),
        ThinkingGuide(259, "나는 → 가지고 있지 않았어 → 충분한 시간을"),
        ThinkingGuide(260, "나는 → 결국 해냈어 → 끝내는 것을 → 그것을"),
        ThinkingGuide(261, "나는 → 의도하지 않았어 → 그것을 → 그런 식으로"),
        ThinkingGuide(262, "할 수 있을까 → 우리가 이야기하는 것을 → 무슨 일이 있었는지?"),
        ThinkingGuide(263, "나는 → 이해해 → 왜 네가 속상한지"),
        ThinkingGuide(264, "그것은 → 아니었어 → 매우 친절한"),
        ThinkingGuide(265, "우리 → 다시 시작하자"),
        ThinkingGuide(266, "우리 둘 다 → 만들었어 → 실수를"),
        ThinkingGuide(267, "나는 → 들었어야 했어"),
        ThinkingGuide(268, "너는 → 믿어도 돼 → 나를"),
        ThinkingGuide(269, "고마워 → 솔직하게 말해줘서"),
        ThinkingGuide(270, "나는 → 용서해 → 너를"),
        ThinkingGuide(271, "나는 → 생각해 → 그것이 일어났다고 → 그것 때문에"),
        ThinkingGuide(272, "그것이 → 이유야 → 그것이 일어난"),
        ThinkingGuide(273, "만약 우리가 → 이렇게 한다면 → 그것은 → 작동할 거야"),
        ThinkingGuide(274, "무엇이 → 일어날 거라고 생각해 → 너는?"),
        ThinkingGuide(275, "나의 추측은 → 그것이 뜰 거라는 거야"),
        ThinkingGuide(276, "우리 → 시험해 보자 → 그것을 → 그리고 보자"),
        ThinkingGuide(277, "그 결과는 → 달랐어"),
        ThinkingGuide(278, "나는 → 알아챘어 → 무언가를"),
        ThinkingGuide(279, "그것은 → 변해 → 온도가 변할 때"),
        ThinkingGuide(280, "그것이 → 설명해 → 그것을"),
        ThinkingGuide(281, "나는 → 가지고 있어 → 너무 많은 것을 → 해야 할"),
        ThinkingGuide(282, "우리 → 결정하자 → 무엇이 가장 중요한지"),
        ThinkingGuide(283, "나는 → 할게 → 이것을 먼저 → 그리고 저것을 나중에"),
        ThinkingGuide(284, "나는 → 필요해 → 짧은 휴식을"),
        ThinkingGuide(285, "나는 → 시간이 → 거의 없어지고 있어"),
        ThinkingGuide(286, "우리는 → 아직 가지고 있어 → 충분한 시간을"),
        ThinkingGuide(287, "우리 → 출발하자 → 조금 더 일찍"),
        ThinkingGuide(288, "나는 → 바꿨어 → 나의 마음을"),
        ThinkingGuide(289, "나는 → 차라리 할래 → 이것을"),
        ThinkingGuide(290, "그것이 → 더 잘 맞아 → 나에게"),
        ThinkingGuide(291, "처음에 → 나는 → 생각했어 → 그것이 쉬울 거라고"),
        ThinkingGuide(292, "그다음 → 나는 → 깨달았어 → 그것이 더 어렵다고"),
        ThinkingGuide(293, "결국 → 그것은 → 잘 해결됐어"),
        ThinkingGuide(294, "가장 좋은 부분은 → 같이 하는 것이었어"),
        ThinkingGuide(295, "가장 어려운 부분은 → 시작하는 것이었어"),
        ThinkingGuide(296, "다음에는 → 나는 → 시작할 거야 → 더 일찍"),
        ThinkingGuide(297, "나는 → 배웠어 → 연습이 정말 도움이 된다는 것을"),
        ThinkingGuide(298, "나는 → 바라 → 내가 그것을 다시 할 수 있기를"),
        ThinkingGuide(299, "나는 → 기뻐 → 내가 시도해서"),
        ThinkingGuide(300, "나는 → 생각해 → 내가 더 나아졌다고")
    )
}
