package com.yamone.english

object Age810ThinkingCatalog {
    private val baseGuides = listOf(
        ThinkingGuide(201, "나는 → 깜빡했어 → 나의 숙제를"),
        ThinkingGuide(202, "나는 → 끝냈어 → 그것을 → 이미"),
        ThinkingGuide(203, "해줄 수 있어 → 네가 설명하는 것을 → 그것을 → 다시?"),
        ThinkingGuide(204, "나는 → 생각해 → 내가 이해한다고"),
        ThinkingGuide(205, "나는 → 필요해 → 더 많은 시간을"),
        ThinkingGuide(206, "무엇을 → 의미해 → 이 단어가?"),
        ThinkingGuide(207, "어떻게 → 철자를 말해 → 너는 → 그것을?"),
        ThinkingGuide(208, "할 수 있을까 → 내가 함께 일하는 것을 → 너와?"),
        ThinkingGuide(209, "우리 → 알아내자 → 그것을"),
        ThinkingGuide(210, "나는 → 만들었어 → 실수를"),
        ThinkingGuide(211, "나는 → 갔어 → 공원에 → 어제"),
        ThinkingGuide(212, "우리는 → 놀았어 → 두 시간 동안"),
        ThinkingGuide(213, "나는 → 봤어 → 무언가 흥미로운 것을"),
        ThinkingGuide(214, "무엇이 → 일어났어 → 그 후에?"),
        ThinkingGuide(215, "그다음 → 우리는 → 갔어 → 집에"),
        ThinkingGuide(216, "나는 → 한 번도 시도해본 적 없어 → 그것을 → 전에"),
        ThinkingGuide(217, "나는 → 했어 → 그것을 → 혼자서"),
        ThinkingGuide(218, "그것은 → 더 쉬웠어 → 내가 생각했던 것보다"),
        ThinkingGuide(219, "이것은 → 더 좋아"),
        ThinkingGuide(220, "어느 것을 → 선호해 → 너는?"),
        ThinkingGuide(221, "나는 → 좋아해 → 이것을 → 왜냐하면 더 쉽기 때문에"),
        ThinkingGuide(222, "나는 → 동의하지 않아"),
        ThinkingGuide(223, "나는 → 알아 → 네가 의미하는 것을"),
        ThinkingGuide(224, "아마 → 너가 → 맞아"),
        ThinkingGuide(225, "그것은 → 달라져 → 상황에 따라"),
        ThinkingGuide(226, "무엇을 → 할 예정이야 → 너는?"),
        ThinkingGuide(227, "나는 → 할 예정이야 → 끝내는 것을 → 이것부터"),
        ThinkingGuide(228, "나는 → 갈지도 몰라 → 나중에"),
        ThinkingGuide(229, "나는 → 아직 결정하지 않았어"),
        ThinkingGuide(230, "어떻게 하지 → 만약 비가 온다면?"),
        ThinkingGuide(231, "우리는 → 할 수 있어 → 다른 것을"),
        ThinkingGuide(232, "나는 → 가지고 있어 → 아이디어 하나를"),
        ThinkingGuide(233, "왜 → 우리 → 시도하지 않을까 → 이것을?"),
        ThinkingGuide(234, "그것은 → 들려 → 좋은 생각처럼"),
        ThinkingGuide(235, "우리 → 만들자 → 계획을"),
        ThinkingGuide(236, "먼저 → 우리는 → 필요해 → 준비물을 가져오는 것이"),
        ThinkingGuide(237, "무엇을 → 해야 해 → 우리는 → 다음으로?"),
        ThinkingGuide(238, "우리는 → 필요해 → 조심하는 것이"),
        ThinkingGuide(239, "나는 → 생각해 → 무언가 잘못됐다고"),
        ThinkingGuide(240, "우리 → 요청하자 → 도움을"),
        ThinkingGuide(241, "나는 → 긴장돼 → 내일에 대해"),
        ThinkingGuide(242, "하지 마 → 걱정하는 것을 → 너무 많이"),
        ThinkingGuide(243, "나는 → 자랑스러워 → 나 자신이"),
        ThinkingGuide(244, "나는 → 실망했어"),
        ThinkingGuide(245, "그것이 → 놀라게 했어 → 나를"),
        ThinkingGuide(246, "나는 → 의도하지 않았어 → 상처 주는 것을 → 네 감정을"),
        ThinkingGuide(247, "괜찮아 → 너는 → 그것에 대해?"),
        ThinkingGuide(248, "고마워 → 이해해줘서"),
        ThinkingGuide(249, "나는 → 배웠어 → 무언가 새로운 것을 → 오늘"),
        ThinkingGuide(250, "말해줘 → 나에게 → 더 많이 → 그것에 대해")
    )

    val guides: List<ThinkingGuide> =
        baseGuides + Age810ThinkingExpansionCatalog.guides
}
