package com.yamone.english

object LessonExpansionCatalog {
    val lessons = listOf(
        Lesson(51, "날씨가 맑아", "☀️", "맑은 날씨를 말할 때", "It's sunny.", "날씨가 맑아.", "It's ●SUN-ny ↘", "잇츠 ●써니↘", "", "오늘 날씨가 맑아.", listOf("It's sunny today.", "It's nice and sunny."), "What's the weather like?"),
        Lesson(52, "바람이 불어", "🌬️", "바람 부는 날씨를 말할 때", "It's windy.", "바람이 불어.", "It's ●WIND-y ↘", "잇츠 ●윈디↘", "", "밖에 바람이 많이 불어.", listOf("It's really windy outside.", "It's windy today."), "Is it windy outside?"),
        Lesson(53, "신발 신어", "👟", "밖에 나갈 준비를 할 때", "Put on your shoes.", "신발 신어.", "Put ON your ●SHOES ↘", "푸던 유어 ●슈즈↘", "", "신발부터 신어.", listOf("Put your shoes on.", "Put on your shoes."), "Are your shoes on?"),
        Lesson(54, "재킷 벗어", "🧥", "겉옷을 벗으라고 할 때", "Take off your jacket.", "재킷 벗어.", "Take OFF your ●JACK-et ↘", "테이코프 유어 ●재킷↘", "", "코트 벗어.", listOf("Take off your coat.", "Take your jacket off."), "Are you warm now?"),
        Lesson(55, "손 씻어", "🧼", "식사 전이나 밖에서 들어왔을 때", "Wash your hands.", "손 씻어.", "Wash your ●HANDS ↘", "워시 유어 ●핸즈↘", "", "밥 먹기 전에 손 씻어.", listOf("Wash your hands first.", "Go wash your hands."), "Did you wash your hands?"),
        Lesson(56, "이 닦아", "🪥", "양치할 때", "Brush your teeth.", "이 닦아.", "Brush your ●TEETH ↘", "브러시 유어 ●티쓰↘", "", "자기 전에 이 닦아.", listOf("Brush your teeth before bed.", "Go brush your teeth."), "Did you brush your teeth?"),
        Lesson(57, "잘 시간이야", "🛏️", "잠자리에 들 시간일 때", "It's time for bed.", "잘 시간이야.", "It's TIME for ●BED ↘", "잇츠 타임 퍼 ●베드↘", "", "이제 잘 시간이야.", listOf("It's bedtime.", "It's time to go to bed."), "Are you ready for bed?"),
        Lesson(58, "일어나", "⏰", "아침에 깨울 때", "Wake up.", "일어나.", "WAKE ●UP ↘", "웨이컵↘", "", "이제 일어나.", listOf("Wake up now.", "Time to wake up."), "Are you awake?"),
        Lesson(59, "졸려", "🥱", "졸릴 때", "I'm sleepy.", "나 졸려.", "I'm ●SLEEP-y ↘", "아임 ●슬리피↘", "", "나 정말 졸려.", listOf("I'm really sleepy.", "I'm getting sleepy."), "Are you sleepy?"),
        Lesson(60, "심심해", "😐", "할 일이 없을 때", "I'm bored.", "나 심심해.", "I'm ●BORED ↘", "아임 ●보어드↘", "", "너무 심심해.", listOf("I'm really bored.", "I'm bored right now."), "What do you want to do?"),
        Lesson(61, "신나!", "🤩", "기대되거나 신날 때", "I'm excited!", "나 신나!", "I'm ex●CIT-ed ↘", "아임 익●사이티드↘", "", "내일이 정말 기대돼.", listOf("I'm so excited!", "I'm excited for tomorrow."), "What are you excited about?"),
        Lesson(62, "화났어", "😠", "화가 났을 때", "I'm angry.", "나 화났어.", "I'm ●AN-gry ↘", "아임 ●앵그리↘", "", "나 지금 조금 화났어.", listOf("I'm a little angry.", "I'm mad."), "Why are you angry?"),
        Lesson(63, "아파", "🩹", "몸의 한 부분이 아플 때", "It hurts.", "아파.", "It ●HURTS ↘", "잇 ●허츠↘", "", "여기가 아파.", listOf("It hurts here.", "This hurts."), "Where does it hurt?"),
        Lesson(64, "머리가 아파", "🤕", "두통이 있을 때", "My head hurts.", "머리가 아파.", "My HEAD ●HURTS ↘", "마이 헤드 ●허츠↘", "", "머리가 조금 아파.", listOf("My head hurts a little.", "I have a headache."), "Does your head hurt?"),
        Lesson(65, "화장실 가야 해", "🚻", "화장실이 급할 때", "I need to go to the bathroom.", "화장실 가야 해.", "I NEED to go to the ●BATH-room ↘", "아이 니드 터 고 터 더 ●배쓰룸↘", "", "화장실 좀 다녀올게.", listOf("I need the bathroom.", "I have to go to the bathroom."), "Do you need to go now?"),
        Lesson(66, "이거 써도 돼?", "🧩", "물건 사용 허락을 구할 때", "Can I use this?", "이거 써도 돼?", "Can‿I USE ●THIS ↗", "커나이 유즈 ●디스↗", "", "이 펜 써도 돼?", listOf("Can I use this pen?", "Can I use it?"), "What do you want to use?"),
        Lesson(67, "여기 앉아도 돼?", "🪑", "자리에 앉아도 되는지 물을 때", "Can I sit here?", "여기 앉아도 돼?", "Can‿I SIT ●HERE ↗", "커나이 싯 ●히어↗", "", "옆에 앉아도 돼?", listOf("Can I sit next to you?", "Can I sit here?"), "Sure. Sit here."),
        Lesson(68, "이거 빌려도 돼?", "🖍️", "친구 물건을 빌릴 때", "Can I borrow this?", "이거 빌려도 돼?", "Can‿I ●BOR-row this ↗", "커나이 ●바로우 디스↗", "", "네 크레용 빌려도 돼?", listOf("Can I borrow your crayons?", "Can I borrow this?"), "Sure. Here you go."),
        Lesson(69, "돌려줘", "↩️", "빌려준 물건을 돌려받을 때", "Please give it back.", "돌려줘.", "Please GIVE‿it ●BACK ↘", "플리즈 기빗 ●백↘", "", "이제 돌려줘.", listOf("Can I have it back?", "Please give it back."), "Okay. Here you go."),
        Lesson(70, "그건 불공평해", "⚖️", "공평하지 않다고 말할 때", "That's not fair.", "그건 불공평해.", "That's not ●FAIR ↘", "댓츠 낫 ●페어↘", "", "그건 진짜 불공평해.", listOf("That's really not fair.", "It's not fair."), "Why isn't it fair?"),
        Lesson(71, "그만해줘", "✋", "상대 행동을 멈춰 달라고 할 때", "Stop it, please.", "그만해줘.", "STOP‿it | please ↘", "스타핏 | 플리즈↘", "", "이제 그만해줘.", listOf("Please stop.", "Stop it, please."), "Okay. I'll stop."),
        Lesson(72, "그거 만지지 마", "🚫", "만지면 안 되는 것을 알려줄 때", "Don't touch that.", "그거 만지지 마.", "Don't TOUCH ●THAT ↘", "돈 터치 ●댓↘", "", "뜨거우니까 만지지 마.", listOf("Don't touch it.", "Please don't touch that."), "Okay. I won't."),
        Lesson(73, "번갈아 하자", "🔄", "친구와 차례를 나눌 때", "Let's take turns.", "번갈아 하자.", "Let's take ●TURNS ↘", "렛츠 테익 ●턴즈↘", "", "우리 번갈아 하자.", listOf("We can take turns.", "Let's take turns."), "Okay. Who goes first?"),
        Lesson(74, "네가 먼저 해", "1️⃣", "상대에게 먼저 하라고 할 때", "You go first.", "네가 먼저 해.", "You go ●FIRST ↘", "유 고 ●퍼스트↘", "", "이번엔 네가 먼저 해.", listOf("You can go first.", "You go first this time."), "Okay. I'll go first."),
        Lesson(75, "내가 이겼어!", "🏆", "게임에서 이겼을 때", "I won!", "내가 이겼어!", "I ●WON ↘", "아이 ●원↘", "", "이번엔 내가 이겼어.", listOf("I won this time!", "I did it! I won!"), "Nice! Want to play again?"),
        Lesson(76, "해냈네!", "🎉", "상대를 칭찬할 때", "You did it!", "해냈네!", "You DID‿it ↘", "유 ●디딧↘", "", "와, 네가 해냈네!", listOf("You did it!", "Great job! You did it!"), "Thanks!"),
        Lesson(77, "다시 해봐", "🔁", "실패 후 다시 시도하라고 할 때", "Try again.", "다시 해봐.", "Try a●GAIN ↘", "트라이 어●겐↘", "", "괜찮아, 다시 해봐.", listOf("It's okay. Try again.", "Give it another try."), "Okay. I'll try again."),
        Lesson(78, "내가 만들었어", "🧱", "직접 만든 것을 보여줄 때", "I made this.", "내가 이거 만들었어.", "I MADE ●THIS ↘", "아이 메이드 ●디스↘", "", "내가 혼자 만들었어.", listOf("I made it myself.", "I made this."), "Wow! What did you make?"),
        Lesson(79, "그림 그렸어", "🖍️", "그린 그림을 보여줄 때", "I drew a picture.", "나 그림 그렸어.", "I DREW a ●PIC-ture ↘", "아이 드루 어 ●픽처↘", "", "오늘 그림 하나 그렸어.", listOf("I drew this picture.", "I made a drawing."), "What did you draw?"),
        Lesson(80, "찾았어!", "🔍", "잃어버린 것을 찾았을 때", "I found it!", "찾았어!", "I FOUND‿it ↘", "아이 ●파운딧↘", "", "드디어 찾았어.", listOf("I found it!", "Here it is!"), "Where was it?"),
        Lesson(81, "잃어버렸어", "😟", "물건을 잃어버렸을 때", "I lost it.", "잃어버렸어.", "I LOST‿it ↘", "아이 ●로스팃↘", "", "내 장난감을 잃어버렸어.", listOf("I lost my toy.", "I can't find it."), "Where did you have it last?"),
        Lesson(82, "무슨 일이야?", "❗", "무슨 일이 있었는지 물을 때", "What happened?", "무슨 일이야?", "What ●HAP-pened ↘", "왓 ●해픈드↘", "", "여기 무슨 일이 있었어?", listOf("What happened here?", "What happened?"), "I'll tell you what happened."),
        Lesson(83, "누가 그랬어?", "🕵️", "누가 했는지 물을 때", "Who did that?", "누가 그랬어?", "Who did ●THAT ↘", "후 딛 ●댓↘", "", "이거 누가 했어?", listOf("Who did this?", "Who did that?"), "I don't know."),
        Lesson(84, "왜 울어?", "😭", "우는 이유를 물을 때", "Why are you crying?", "왜 울어?", "WHY‿are‿you ●CRY-ing ↘", "와이얼유 ●크라잉↘", "", "왜 지금 울고 있어?", listOf("Why are you crying?", "What's making you cry?"), "I'm sad."),
        Lesson(85, "슬퍼서 그래", "💧", "이유를 말할 때", "Because I'm sad.", "슬퍼서 그래.", "Be●CAUSE I'm ●SAD ↘", "비●커즈 아임 ●새드↘", "", "친구가 가서 슬퍼.", listOf("Because my friend left.", "I'm sad because my friend left."), "I'm sorry you're sad."),
        Lesson(86, "언제 출발해?", "🚗", "출발 시간을 물을 때", "When are we leaving?", "언제 출발해?", "WHEN‿are‿we ●LEAV-ing ↘", "웨너위 ●리빙↘", "", "우리 언제 가?", listOf("When are we going?", "When do we leave?"), "We're leaving soon."),
        Lesson(87, "지금 출발해", "🚙", "지금 떠난다고 말할 때", "We're leaving now.", "지금 출발해.", "We're LEAV-ing ●NOW ↘", "위어 리빙 ●나우↘", "", "우리 이제 가.", listOf("We're going now.", "We're leaving now."), "Okay. I'm ready."),
        Lesson(88, "몇 시야?", "🕒", "시간을 물을 때", "What time is it?", "몇 시야?", "What TIME is‿it ↘", "왓 타임 이짓↘", "", "지금 몇 시야?", listOf("What time is it now?", "Do you know what time it is?"), "It's almost three."),
        Lesson(89, "거의 시간이야", "⌛", "곧 시작하거나 떠날 때", "It's almost time.", "거의 시간이야.", "It's AL-most ●TIME ↘", "잇츠 올모스트 ●타임↘", "", "이제 거의 갈 시간이야.", listOf("It's almost time to go.", "We're almost ready."), "Are you ready?"),
        Lesson(90, "책 펴", "📖", "수업에서 책을 펼 때", "Open your book.", "책 펴.", "Open your ●BOOK ↘", "오픈 유어 ●북↘", "", "책 10쪽 펴.", listOf("Open your book to page ten.", "Please open your book."), "What page?"),
        Lesson(91, "문 닫아줘", "🚪", "문을 닫아 달라고 할 때", "Close the door, please.", "문 닫아줘.", "Close the ●DOOR | please ↘", "클로우즈 더 ●도어 | 플리즈↘", "", "들어오면 문 닫아줘.", listOf("Please close the door.", "Close the door behind you."), "Okay."),
        Lesson(92, "연필 빌려도 돼?", "✏️", "학교에서 연필을 빌릴 때", "Can I borrow a pencil?", "연필 빌려도 돼?", "Can‿I BOR-row a ●PEN-cil ↗", "커나이 바로우 어 ●펜슬↗", "", "연필 하나 빌려줄래?", listOf("Can I borrow your pencil?", "Do you have a pencil I can use?"), "Sure. Here you go."),
        Lesson(93, "자, 여기 있어", "🤲", "물건을 건넬 때", "Here you go.", "자, 여기 있어.", "HERE you ●GO ↘", "히어 유 ●고우↘", "", "응, 여기 있어.", listOf("Here you are.", "Here you go."), "Thanks!"),
        Lesson(94, "뭐 먹고 싶어?", "🍽️", "먹고 싶은 것을 물을 때", "What do you want to eat?", "뭐 먹고 싶어?", "WHAT do you want to ●EAT ↘", "왓 더유 워너 ●잇↘", "", "점심 뭐 먹고 싶어?", listOf("What do you want for lunch?", "What would you like to eat?"), "I want pizza."),
        Lesson(95, "피자 먹고 싶어", "🍕", "먹고 싶은 음식을 말할 때", "I want some pizza.", "피자 좀 먹고 싶어.", "I WANT some ●PIZ-za ↘", "아이 원트 썸 ●피자↘", "", "난 피자 먹고 싶어.", listOf("I'd like some pizza.", "I want pizza."), "Sounds good."),
        Lesson(96, "좀 먹을래?", "🍪", "음식을 나눠 줄 때", "Do you want some?", "좀 먹을래?", "Do you WANT ●SOME ↗", "더유 원트 ●썸↗", "", "쿠키 좀 먹을래?", listOf("Do you want a cookie?", "Want some?"), "Yes, please."),
        Lesson(97, "아니, 괜찮아", "🙅", "정중하게 거절할 때", "No, thank you.", "아니, 괜찮아.", "NO | thank ●YOU ↘", "노우 | 땡큐↘", "", "아니, 난 괜찮아.", listOf("No, thanks.", "I'm okay, thanks."), "Okay."),
        Lesson(98, "맛있어", "😋", "음식 맛을 말할 때", "It tastes good.", "맛있어.", "It tastes ●GOOD ↘", "잇 테이스츠 ●굿↘", "", "이거 정말 맛있어.", listOf("This tastes really good.", "It's delicious."), "Do you like it?"),
        Lesson(99, "배불러", "🍽️", "충분히 먹었을 때", "I'm full.", "나 배불러.", "I'm ●FULL ↘", "아임 ●풀↘", "", "이제 배불러.", listOf("I'm full now.", "I've had enough."), "Do you want any more?"),
        Lesson(100, "잘 자", "🌙", "잠들기 전에 인사할 때", "Good night.", "잘 자.", "Good ●NIGHT ↘", "굿 ●나잇↘", "", "잘 자, 내일 봐.", listOf("Good night. See you tomorrow.", "Sleep well."), "Good night!")
    )
}
