package com.yamone.english

data class PronunciationQaGuide(
    val lessonId: Int,
    val rhythmEnglish: String,
    val slowKorean: String,
    val naturalKorean: String,
    val rhythm: String
)

object PronunciationQaCatalog {
    private val guides = listOf(
        PronunciationQaGuide(1, "●HI | I'm ●MI-na ↘", "하이 / 아임 / 미나", "●하이 | 아임 ●미나↘", "강 | 약-강 ↘"),
        PronunciationQaGuide(2, "●HOW‿are‿you ↗", "하우 / 아 / 유", "●하워유↗", "강-약-약 ↗"),
        PronunciationQaGuide(3, "I ●LIKE this ↘", "아이 / 라익 / 디스", "아이 ●라익 디스↘", "약-강-약 ↘"),
        PronunciationQaGuide(4, "I don't ●LIKE‿it ↘", "아이 / 돈트 / 라익 / 잇", "아이 돈(트) ●라이킷↘", "약-약-강-약 ↘"),
        PronunciationQaGuide(5, "I'm ●HUN-gry ↘", "아임 / 헝그리", "아임 ●헝그리↘", "약-강 ↘"),
        PronunciationQaGuide(6, "I'm ●THIRS-ty ↘", "아임 / 써얼스티", "아임 ●써얼스티↘", "약-강 ↘"),
        PronunciationQaGuide(7, "Can‿I ●HAVE this ↗", "캔 / 아이 / 해브 / 디스", "커나이 ●해브 디스↗", "약-약-강-약 ↗"),
        PronunciationQaGuide(8, "Can‿you ●HELP me ↗", "캔 / 유 / 헬프 / 미", "컨유 ●헬프 미↗", "약-약-강-약 ↗"),
        PronunciationQaGuide(9, "WAIT‿a ●SEC-ond ↘", "웨잇 / 어 / 세컨드", "웨이러 ●세컨드↘", "강-약-강 ↘"),
        PronunciationQaGuide(10, "SAY that‿a●GAIN | please ↘", "세이 / 댓 / 어겐 / 플리즈", "세이 대러●겐 | 플리즈↘", "강-약-강 | 약 ↘"),
        PronunciationQaGuide(11, "I don't ●KNOW ↘", "아이 / 돈트 / 노우", "아이 돈 ●노우↘", "약-약-강 ↘"),
        PronunciationQaGuide(12, "I ●GOT‿it ↘", "아이 / 갓 / 잇", "아이 ●가릿↘", "약-강-약 ↘"),
        PronunciationQaGuide(13, "●WHERE‿are‿you ●GO-ing ↘", "웨어 / 아 / 유 / 고잉", "●웨어러유 ●고잉↘", "강-약-약-강 ↘"),
        PronunciationQaGuide(14, "I'm ●GO-ing ●HOME ↘", "아임 / 고잉 / 홈", "아임 ●고잉 ●홈↘", "약-강-강 ↘"),
        PronunciationQaGuide(15, "Let's DO‿it to●GE-ther ↘", "렛츠 / 두 / 잇 / 터게더", "렛츠 두윗 터●게더↘", "강-강-약-강 ↘"),
        PronunciationQaGuide(16, "It's my ●TURN ↘", "잇츠 / 마이 / 턴", "잇츠 마이 ●턴↘", "약-약-강 ↘"),
        PronunciationQaGuide(17, "It's o●KAY ↘", "잇츠 / 오케이", "잇츠 오●케이↘", "약-강 ↘"),
        PronunciationQaGuide(18, "I'm ●SOR-ry ↘", "아임 / 사리", "아임 ●싸리↘", "약-강 ↘"),
        PronunciationQaGuide(19, "●THANK‿you ↘", "쌩크 / 유", "●쌩큐↘", "강-약 ↘"),
        PronunciationQaGuide(20, "That was ●FUN ↘", "댓 / 워즈 / 펀", "댓 워즈 ●펀↘", "약-약-강 ↘"),
        PronunciationQaGuide(21, "I'm ●TIRED ↘", "아임 / 타이얼드", "아임 ●타이얼드↘", "약-강 ↘"),
        PronunciationQaGuide(22, "●WHAT‿are‿you ●DO-ing ↘", "왓 / 아 / 유 / 두잉", "●워러유 ●두잉↘", "강-약-약-강 ↘"),
        PronunciationQaGuide(23, "I'm ●READ-y ↘", "아임 / 레디", "아임 ●레디↘", "약-강 ↘"),
        PronunciationQaGuide(24, "SEE‿you ●LA-ter ↘", "씨 / 유 / 레이터", "씨유 ●레이럴↘", "강-약-강 ↘"),
        PronunciationQaGuide(25, "THIS‿is my ●MOM ↘", "디스 / 이즈 / 마이 / 맘", "디시즈 마이 ●맘↘", "강-약-약-강 ↘"),
        PronunciationQaGuide(26, "THAT'S my ●DAD ↘", "댓츠 / 마이 / 대드", "댓츠 마이 ●대드↘", "강-약-강 ↘"),
        PronunciationQaGuide(27, "I HAVE‿a ●BRO-ther ↘", "아이 / 해브 / 어 / 브러더", "아이 해버 ●브러더↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(28, "SHE'S my ●SIS-ter ↘", "쉬즈 / 마이 / 시스터", "쉬즈 마이 ●시스터↘", "강-약-강 ↘"),
        PronunciationQaGuide(29, "WHERE'S my ●TOY ↘", "웨어즈 / 마이 / 토이", "웨어즈 마이 ●토이↘", "강-약-강 ↘"),
        PronunciationQaGuide(30, "It's O-ver ●THERE ↘", "잇츠 / 오버 / 데어", "잇츠 오버 ●데어↘", "약-약-강 ↘"),
        PronunciationQaGuide(31, "THIS‿is ●MINE ↘", "디스 / 이즈 / 마인", "디시즈 ●마인↘", "강-약-강 ↘"),
        PronunciationQaGuide(32, "Is this ●YOURS ↗", "이즈 / 디스 / 요얼즈", "이즈 디스 ●요얼즈↗", "약-약-강 ↗"),
        PronunciationQaGuide(33, "WHAT‿is ●THIS ↘", "왓 / 이즈 / 디스", "워리즈 ●디스↘", "강-약-강 ↘"),
        PronunciationQaGuide(34, "WHICH‿one do‿you ●WANT ↘", "위치 / 원 / 두 / 유 / 원트", "위치원 더유 ●원트↘", "강-약-약-약-강 ↘"),
        PronunciationQaGuide(35, "I WANT the ●RED‿one ↘", "아이 / 원트 / 더 / 레드 / 원", "아이 원트 더 ●레드원↘", "약-강-약-강-약 ↘"),
        PronunciationQaGuide(36, "I NEED‿a ●PEN-cil ↘", "아이 / 니드 / 어 / 펜슬", "아이 니더 ●펜슬↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(37, "Can‿I go out●SIDE ↗", "캔 / 아이 / 고 / 아웃사이드", "커나이 고 아웃●사이드↗", "약-약-약-강 ↗"),
        PronunciationQaGuide(38, "Can‿I PLAY with‿●YOU ↗", "캔 / 아이 / 플레이 / 위드 / 유", "커나이 플레이 위쥬↗", "약-약-강-약-강 ↗"),
        PronunciationQaGuide(39, "I can ●DO‿it ↘", "아이 / 캔 / 두 / 잇", "아이 컨 ●두윗↘", "약-약-강-약 ↘"),
        PronunciationQaGuide(40, "I can't ●REACH‿it ↘", "아이 / 캔트 / 리치 / 잇", "아이 캔트 ●리칫↘", "약-강-강-약 ↘"),
        PronunciationQaGuide(41, "COME ●HERE | please ↘", "컴 / 히어 / 플리즈", "컴 ●히어 | 플리즈↘", "강-강 | 약 ↘"),
        PronunciationQaGuide(42, "LOOK‿at ●THIS ↘", "룩 / 앳 / 디스", "루커트 ●디스↘", "강-약-강 ↘"),
        PronunciationQaGuide(43, "Be ●CARE-ful ↘", "비 / 케어풀", "비 ●케어풀↘", "약-강 ↘"),
        PronunciationQaGuide(44, "I'm ●SCARED ↘", "아임 / 스케어드", "아임 ●스케어드↘", "약-강 ↘"),
        PronunciationQaGuide(45, "I'm ●HAP-py ↘", "아임 / 해피", "아임 ●해피↘", "약-강 ↘"),
        PronunciationQaGuide(46, "I'm ●SAD ↘", "아임 / 새드", "아임 ●새드↘", "약-강 ↘"),
        PronunciationQaGuide(47, "I'm ●COLD ↘", "아임 / 코울드", "아임 ●코울드↘", "약-강 ↘"),
        PronunciationQaGuide(48, "I'm ●HOT ↘", "아임 / 핫", "아임 ●핫↘", "약-강 ↘"),
        PronunciationQaGuide(49, "I don't feel ●GOOD ↘", "아이 / 돈트 / 필 / 굿", "아이 돈 필 ●굿↘", "약-약-약-강 ↘"),
        PronunciationQaGuide(50, "It's ●RAIN-ing ↘", "잇츠 / 레이닝", "잇츠 ●레이닝↘", "약-강 ↘"),
        PronunciationQaGuide(51, "It's ●SUN-ny ↘", "잇츠 / 써니", "잇츠 ●써니↘", "약-강 ↘"),
        PronunciationQaGuide(52, "It's ●WIND-y ↘", "잇츠 / 윈디", "잇츠 ●윈디↘", "약-강 ↘"),
        PronunciationQaGuide(53, "Put‿ON your ●SHOES ↘", "풋 / 온 / 유어 / 슈즈", "푸란 유어 ●슈즈↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(54, "Take‿OFF your ●JACK-et ↘", "테이크 / 오프 / 유어 / 재킷", "테이카프 유어 ●재킷↘", "강-강-약-강 ↘"),
        PronunciationQaGuide(55, "Wash your ●HANDS ↘", "워시 / 유어 / 핸즈", "와쉬어 ●핸즈↘", "강-약-강 ↘"),
        PronunciationQaGuide(56, "Brush your ●TEETH ↘", "브러시 / 유어 / 티쓰", "브러쉬어 ●티쓰↘", "강-약-강 ↘"),
        PronunciationQaGuide(57, "It's TIME for ●BED ↘", "잇츠 / 타임 / 포 / 베드", "잇츠 타임 퍼 ●베드↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(58, "WAKE‿●UP ↘", "웨이크 / 업", "●웨이컵↘", "강-강 ↘"),
        PronunciationQaGuide(59, "I'm ●SLEEP-y ↘", "아임 / 슬리피", "아임 ●슬리피↘", "약-강 ↘"),
        PronunciationQaGuide(60, "I'm ●BORED ↘", "아임 / 보어드", "아임 ●보어드↘", "약-강 ↘"),
        PronunciationQaGuide(61, "I'm ex●CIT-ed ↘", "아임 / 익사이티드", "아임 익●사이릿↘", "약-강 ↘"),
        PronunciationQaGuide(62, "I'm ●AN-gry ↘", "아임 / 앵그리", "아임 ●앵그리↘", "약-강 ↘"),
        PronunciationQaGuide(63, "It ●HURTS ↘", "잇 / 허츠", "잇 ●허츠↘", "약-강 ↘"),
        PronunciationQaGuide(64, "My HEAD ●HURTS ↘", "마이 / 헤드 / 허츠", "마이 헤드 ●허츠↘", "약-강-강 ↘"),
        PronunciationQaGuide(65, "I NEED to go to the ●BATH-room ↘", "아이 / 니드 / 투 / 고 / 투 / 더 / 배쓰룸", "아이 니드 터 고우 터 더 ●배쓰룸↘", "약-강-약-강-약-약-강 ↘"),
        PronunciationQaGuide(66, "Can‿I USE ●THIS ↗", "캔 / 아이 / 유즈 / 디스", "커나이 유즈 ●디스↗", "약-약-강-강 ↗"),
        PronunciationQaGuide(67, "Can‿I SIT ●HERE ↗", "캔 / 아이 / 싯 / 히어", "커나이 싯 ●히어↗", "약-약-강-강 ↗"),
        PronunciationQaGuide(68, "Can‿I ●BOR-row this ↗", "캔 / 아이 / 바로우 / 디스", "커나이 ●바로우 디스↗", "약-약-강-약 ↗"),
        PronunciationQaGuide(69, "Please GIVE‿it ●BACK ↘", "플리즈 / 기브 / 잇 / 백", "플리즈 기빗 ●백↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(70, "That's not ●FAIR ↘", "댓츠 / 낫 / 페어", "댓츠 낫 ●페어↘", "약-약-강 ↘"),
        PronunciationQaGuide(71, "STOP‿it | please ↘", "스탑 / 잇 / 플리즈", "스타핏 | 플리즈↘", "강-약 | 약 ↘"),
        PronunciationQaGuide(72, "Don't TOUCH ●THAT ↘", "돈트 / 터치 / 댓", "돈 터치 ●댓↘", "약-강-강 ↘"),
        PronunciationQaGuide(73, "Let's take ●TURNS ↘", "렛츠 / 테이크 / 턴즈", "렛츠 테익 ●턴즈↘", "약-강-강 ↘"),
        PronunciationQaGuide(74, "You go ●FIRST ↘", "유 / 고 / 퍼스트", "유 고 ●퍼스트↘", "약-약-강 ↘"),
        PronunciationQaGuide(75, "I ●WON ↘", "아이 / 원", "아이 ●원↘", "약-강 ↘"),
        PronunciationQaGuide(76, "You DID‿it ↘", "유 / 디드 / 잇", "유 ●디딧↘", "약-강-약 ↘"),
        PronunciationQaGuide(77, "Try a●GAIN ↘", "트라이 / 어겐", "트라이 어●겐↘", "강-강 ↘"),
        PronunciationQaGuide(78, "I MADE ●THIS ↘", "아이 / 메이드 / 디스", "아이 메이드 ●디스↘", "약-강-강 ↘"),
        PronunciationQaGuide(79, "I DREW a ●PIC-ture ↘", "아이 / 드루 / 어 / 픽처", "아이 드루 어 ●픽처↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(80, "I FOUND‿it ↘", "아이 / 파운드 / 잇", "아이 ●파운딧↘", "약-강-약 ↘"),
        PronunciationQaGuide(81, "I LOST‿it ↘", "아이 / 로스트 / 잇", "아이 ●로스팃↘", "약-강-약 ↘"),
        PronunciationQaGuide(82, "What ●HAP-pened ↘", "왓 / 해픈드", "왓 ●해픈드↘", "약-강 ↘"),
        PronunciationQaGuide(83, "Who did ●THAT ↘", "후 / 디드 / 댓", "후 딛 ●댓↘", "약-약-강 ↘"),
        PronunciationQaGuide(84, "WHY‿are‿you ●CRY-ing ↘", "와이 / 아 / 유 / 크라잉", "와이얼유 ●크라잉↘", "강-약-약-강 ↘"),
        PronunciationQaGuide(85, "Be●CAUSE I'm ●SAD ↘", "비커즈 / 아임 / 새드", "비●커즈 아임 ●새드↘", "강-약-강 ↘"),
        PronunciationQaGuide(86, "WHEN‿are‿we ●LEAV-ing ↘", "웬 / 아 / 위 / 리빙", "웨너위 ●리빙↘", "강-약-약-강 ↘"),
        PronunciationQaGuide(87, "We're LEAV-ing ●NOW ↘", "위어 / 리빙 / 나우", "위어 리빙 ●나우↘", "약-강-강 ↘"),
        PronunciationQaGuide(88, "What TIME is‿it ↘", "왓 / 타임 / 이즈 / 잇", "왓 타임 이짓↘", "약-강-약-약 ↘"),
        PronunciationQaGuide(89, "It's AL-most ●TIME ↘", "잇츠 / 올모스트 / 타임", "잇쏠모스트 ●타임↘", "약-강-강 ↘"),
        PronunciationQaGuide(90, "Open your ●BOOK ↘", "오픈 / 유어 / 북", "오픈 유어 ●북↘", "강-약-강 ↘"),
        PronunciationQaGuide(91, "Close the ●DOOR | please ↘", "클로우즈 / 더 / 도어 / 플리즈", "클로우즈 더 ●도어 | 플리즈↘", "강-약-강 | 약 ↘"),
        PronunciationQaGuide(92, "Can‿I BOR-row‿a ●PEN-cil ↗", "캔 / 아이 / 바로우 / 어 / 펜슬", "커나이 바로워 ●펜슬↗", "약-약-강-약-강 ↗"),
        PronunciationQaGuide(93, "HERE you ●GO ↘", "히어 / 유 / 고", "히어여 ●고우↘", "강-약-강 ↘"),
        PronunciationQaGuide(94, "WHAT do‿you want to ●EAT ↘", "왓 / 두 / 유 / 원트 / 투 / 잇", "왓 더유 워너 ●잇↘", "강-약-약-강-약-강 ↘"),
        PronunciationQaGuide(95, "I WANT some ●PIZ-za ↘", "아이 / 원트 / 썸 / 피자", "아이 원트 썸 ●피자↘", "약-강-약-강 ↘"),
        PronunciationQaGuide(96, "Do‿you WANT ●SOME ↗", "두 / 유 / 원트 / 썸", "더유 원트 ●썸↗", "약-약-강-강 ↗"),
        PronunciationQaGuide(97, "NO | thank ●YOU ↘", "노우 / 쌩크 / 유", "노우 | 쌩●큐↘", "강 | 약-강 ↘"),
        PronunciationQaGuide(98, "It tastes ●GOOD ↘", "잇 / 테이스츠 / 굿", "잇 테이스츠 ●굿↘", "약-강-강 ↘"),
        PronunciationQaGuide(99, "I'm ●FULL ↘", "아임 / 풀", "아임 ●풀↘", "약-강 ↘"),
        PronunciationQaGuide(100, "Good ●NIGHT ↘", "굿 / 나잇", "굿 ●나잇↘", "약-강 ↘")
    )

    private val allGuides =
        guides +
            Age810PronunciationQaCatalog.guides +
            Age1113PronunciationQaCatalog.guides +
            Age1416PronunciationQaCatalog.guides +
            Age1416PronunciationQaExpansionCatalog.guides +
            Age1720PronunciationQaCatalog.guides

    fun byLessonId(id: Int): PronunciationQaGuide =
        allGuides.firstOrNull { it.lessonId == id }
            ?: PronunciationQaGuide(id, "", "", "", "")
}
