package com.yamone.english

object ThinkingExpansionCatalog {
    val guides = listOf(
        ThinkingGuide(51, "그것은 → 맑아"),
        ThinkingGuide(52, "그것은 → 바람이 불어"),
        ThinkingGuide(53, "신어 → 너의 신발을"),
        ThinkingGuide(54, "벗어 → 너의 재킷을"),
        ThinkingGuide(55, "씻어 → 너의 손을"),
        ThinkingGuide(56, "닦아 → 너의 이를"),
        ThinkingGuide(57, "그것은 → 시간이야 → 잠자리에 들"),
        ThinkingGuide(58, "일어나"),
        ThinkingGuide(59, "나는 → 졸려"),
        ThinkingGuide(60, "나는 → 심심해"),
        ThinkingGuide(61, "나는 → 신나"),
        ThinkingGuide(62, "나는 → 화났어"),
        ThinkingGuide(63, "그것은 → 아파"),
        ThinkingGuide(64, "나의 머리가 → 아파"),
        ThinkingGuide(65, "나는 → 필요해 → 가는 것이 → 화장실에"),
        ThinkingGuide(66, "할 수 있을까 → 내가 쓰는 것을 → 이것을?"),
        ThinkingGuide(67, "할 수 있을까 → 내가 앉는 것을 → 여기에?"),
        ThinkingGuide(68, "할 수 있을까 → 내가 빌리는 것을 → 이것을?"),
        ThinkingGuide(69, "부탁해 → 돌려줘 → 그것을 → 뒤로"),
        ThinkingGuide(70, "그것은 → 아니야 → 공평한"),
        ThinkingGuide(71, "멈춰 → 그것을 → 부탁해"),
        ThinkingGuide(72, "하지 마 → 만지는 것을 → 저것을"),
        ThinkingGuide(73, "우리 → 하자 → 번갈아"),
        ThinkingGuide(74, "너가 → 해 → 먼저"),
        ThinkingGuide(75, "나는 → 이겼어"),
        ThinkingGuide(76, "너는 → 해냈어 → 그것을"),
        ThinkingGuide(77, "시도해 → 다시"),
        ThinkingGuide(78, "나는 → 만들었어 → 이것을"),
        ThinkingGuide(79, "나는 → 그렸어 → 그림 하나를"),
        ThinkingGuide(80, "나는 → 찾았어 → 그것을"),
        ThinkingGuide(81, "나는 → 잃어버렸어 → 그것을"),
        ThinkingGuide(82, "무엇이 → 일어났어?"),
        ThinkingGuide(83, "누가 → 했어 → 저것을?"),
        ThinkingGuide(84, "왜 → 울고 있어 → 너는?"),
        ThinkingGuide(85, "왜냐하면 → 나는 → 슬퍼"),
        ThinkingGuide(86, "언제 → 우리는 → 떠나고 있어?"),
        ThinkingGuide(87, "우리는 → 떠나고 있어 → 지금"),
        ThinkingGuide(88, "무슨 시간이야 → 지금?"),
        ThinkingGuide(89, "그것은 → 거의 → 시간이야"),
        ThinkingGuide(90, "펴 → 너의 책을"),
        ThinkingGuide(91, "닫아 → 그 문을 → 부탁해"),
        ThinkingGuide(92, "할 수 있을까 → 내가 빌리는 것을 → 연필 하나를?"),
        ThinkingGuide(93, "여기에 → 너에게 → 간다"),
        ThinkingGuide(94, "무엇을 → 원해 → 너는 → 먹기를?"),
        ThinkingGuide(95, "나는 → 원해 → 약간의 피자를"),
        ThinkingGuide(96, "원해 → 너는 → 조금을?"),
        ThinkingGuide(97, "아니 → 고마워"),
        ThinkingGuide(98, "그것은 → 맛이 나 → 좋게"),
        ThinkingGuide(99, "나는 → 배불러"),
        ThinkingGuide(100, "좋은 → 밤")
    )
}
